from pathlib import Path
import json,sys,hashlib,zipfile,copy,os,re
from docx import Document
ROOT=Path.cwd();Q=Path(__file__).parent;R=ROOT/'regions/LME_047';MID='47_2_East_China_Sea_(2018)';O=R/'validation_reports'/MID
sys.path.insert(0,str(ROOT/'tools'));from workbooks import sha,read_book,records
def save(n,v):(O/n).write_text(json.dumps(v,ensure_ascii=False,indent=2),encoding='utf-8')
geo=json.loads((O/'geography/geographic_assessment.json').read_text(encoding='utf-8'));geo['report_A_range']='10–15%';(O/'geography/geographic_assessment.json').write_text(json.dumps(geo,ensure_ascii=False,indent=2),encoding='utf-8')
focal=R/'papers/ECS-2022';pdf=next(focal.glob('*.pdf'));supp=next(focal.glob('*.docx'));old=next((R/'papers/LME047-Li-2012').glob('*.doc'))
inventory=[]
for p in sorted((R/'papers').rglob('*')):
 if p.is_file():inventory.append({'relative_path':p.relative_to(R).as_posix(),'sha256':sha(p),'role':'Focal Xu2022 source'if p.parent==focal else 'Historical alternative/context; not substituted'})
save('source_identity_verification.json',{'selected_model_id':MID,'canonical_sha256':sha(R/'models'/MID/'model.json'),'required_canonical_sha256':'31b1f6c360ce1d454db528e050100e5521cbf663cdb9d3001f0f39724a14ed16','focal_source_doi':'10.3389/fmars.2022.865645','focal_pdf_sha256':sha(pdf),'focal_supplement_sha256':sha(supp),'source_files':inventory,'roles':'Focal PDF and publisher DOCX verified by titles/tables, not filename alone. LegacyLi2012 supplement audited A1.8; focalLi2012 andCheng2009 main PDFs remain unavailable. No native EwE model file found.'})
dd=Document(supp);can={int(g['group_seq']):g for g in json.loads((R/'models'/MID/'model.json').read_text(encoding='utf-8'))['group']};cols={p:{}for p in range(2,24)}
for row in list(dd.tables[5].rows)[1:]:
 v=[c.text.strip()for c in row.cells]
 if v[0].isdigit():
  for pred,val in zip(range(2,24),v[2:]):cols[pred][int(v[0])]=float(val or 0)
proof=[]
for pred,vals in cols.items():
 s=sum(vals.values());ds=can[pred]['diet_descr']['diet'];ds=ds if isinstance(ds,list)else[ds];cv={int(x['prey_seq']):float(x['proportion'])for x in ds};gap=max(abs(v/s-cv.get(prey,0))for prey,v in vals.items());proof.append({'predator_id':pred,'source_column_sum':s,'maximum_abs_difference_after_column_normalization':gap,'normalized_column_matches':gap<1e-12})
save('diet_normalization_provenance.json',{'source_table':'S3 M2018','published_cell_checks':528,'unmodified_canonical':'Canonical incorporates normalized published diet columns. Exact raw decimal comparison identifies91differences; all normalized columns match to1e-12. Current accepted loader normalization is retained.','columns':proof,'all_normalized_columns_match':all(x['normalized_column_matches']for x in proof)});assert all(x['normalized_column_matches']for x in proof)
sources=[
{'id':'Xu2022_S1','title':'Xu et al.2022 — publisher supplement TableS1','supports':'Exact focal group representatives; source16/17 row order differs from main Table1. Representatives do not establish exhaustive modern family membership. TablesS2/S3 show1997/2018 diets; S4 is M1997 Ecosim time-series, not complete selected-M2018 model catch.','target':supp.relative_to(R).as_posix()},
{'id':'Xu2022_Table1','title':'Xu et al.2022 — main paper Table1 and §2.2','supports':'All96M2018 B/PB/QB/EE cells, including unavailable primary/detritus Q/B. All populated cells match accepted JSON. 24ecological groups; joint autumn2018/spring2019 survey; model catch from yearbook excludes unavailable discard data. Model boundary/area not explicitly provided.','target':pdf.relative_to(R).as_posix()+'#page=5'},
{'id':'allocation','title':'Reviewed source catch and biomass allocation evidence','supports':'27reviewed splits:12complete positive sourceS4year2018catch proxies underW4Medium;15incomplete/censored candidate sets use complete M2018 source biomass underW9Medium. Canonical export0placeholders are not observed zeros. Whole-guild density is proxy composition, not observed target caught mass or stages.','target':'validation_reports/'+MID+'/allocation_evidence.json'},
{'id':'audit','title':'Every-label membership and confidence decisions','supports':'All276labels, including zero2019catch, broad residuals and formerHigh/Medium mappings. Exact previous rows, eligible groups, component grades and evidence retained. Weakest confidence displayed.','target':'validation_reports/'+MID+'/taxon_audit.json'},
{'id':'provider','title':'Retained Sea Around Us exploited organism keys','supports':'Exact historical reporting labels, common names, functional tags and taxon keys. Marinefish100039/finfish100139/pelagic100339 are bony categories; functional tags are evidence rather than exhaustive membership exclusions.','target':'raw/LME_047-exploited.json'},
{'id':'catch','title':'Sea Around Us v50.1 — original detailed catch archive','supports':'All1950–2019catch strata. Reference2019landings includes reported/unreported retained catch. Discards separate. Historical W5 pooled every solo-mapped guild taxon/all years, not within-target family.','target':'raw/LME_047-catch.zip'},
{'id':'donors','title':'Actual historical donor query and reporting strata','supports':'All20catch-composition fractions reproduced to≤1.7e-16; historical explicit50/50Psenopsis assessed separately. Country, gear, sector, reporting, catch basis, end use and period retained. No donor stratum establishes residual composition. Replaced by qualified 2018 source-catch or complete-biomass proxies.','target':'validation_reports/'+MID+'/identified_catch_proxy_review.json'},
{'id':'diagnostics','title':'Full direct diagnostic matrices and independent inspection','supports':'Accepted runtime settings and exact canonical bytes. All75source-recipient entries perGE/TE/WithEgestion examined including unfished groups; no negatives. WARN, strict balance true, EE0Sharks22/Mammals23, unverified canonical export0 catch remains.','target':'validation_reports/'+MID+'/matrix_inspection.json'},
{'id':'geography','title':'Original Figure1, graticule trace and water controls','supports':'Approximate displayed study footprint, about13.6%target coverage. Methods identify2018/2019survey, without exact modeled boundary. Native graticule, offshore coastal gap and bends retained. NaturalEarth1:50million land mask. Coverage not multiplier.','target':'validation_reports/'+MID+'/geography/calibration_and_controls.json'},
{'id':'legacy','title':'Li & Zhang2012 — publisher legacy supplement A1.8','supports':'Older ECS Crabs pool explicitly includes lobsters with Portunus/Charybdis. Compatible transfer to focalCrabs8 supports M12Medium for four lobster labels; no focal native membership or transferred coefficients claimed. FocalLi2012main unavailable.','target':old.relative_to(R).as_posix()},
{'id':'sunfish','title':'Nakamura, Goto & Sato2015 — sunfish feeding observations','supports':'Primary Japan camera/tag observations show deep siphonophore foraging and surface rewarming. Supports positive zooplankton-fish analogue and severe habitat/size/gelatinous feeding mismatch; not source model membership.','target':'https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2656.12346'},
{'id':'scarid','title':'FAO2002 Western Central Atlantic — Scaridae diagnosis','supports':'Printedp1723: reef grazing on algal/bacterial mat, seagrass and some coral-associated invertebrates. Supports weak coastal mixed-feeding Omnivores19 analogue; reef scraping/grazing is poorly represented.','target':'https://www.fao.org/4/y4162e/y4162e42.pdf'},
{'id':'synonyms','title':'WoRMS — Trachysalambria curvirostris accepted name','supports':'Trachypenaeus curvirostris source name is an accepted synonym; sourceShrimps9 membership preserved underM2.','target':'https://www.marinespecies.org/aphia.php?id=107113&p=taxdetails'},
{'id':'hardwickii','title':'WoRMS — Mierspenaeopsis hardwickii accepted name','supports':'Parapenaeopsis hardwickii source name connects to accepted target Mierspenaeopsis hardwickii; preservesM2High.','target':'https://www.marinespecies.org/aphia.php?id=585389&p=taxdetails'},
{'id':'gempylid','title':'FAO2001 Western Central Pacific — Gempylidae and Rexea','supports':'Scombroidei includes Gempylidae; printed3704/PDF7 describes source-listed Rexea prometheoides meso-/benthopelagic135–540m. Supports retaining mixed18 in pelagic residual and historical Scombroidei candidate sets; pooling remains uncertain.','target':'https://www.fao.org/docrep/pdf/009/y0870e/y0870e34.pdf'},
{'id':'pennahia','title':'WoRMS — Pennahia argentata accepted taxon','supports':'AuthorS1argentata/argentatus spellings resolve to a shared croaker label; native duplicate source13/18 retained as author union, 2018 source-catch split explicitly assumed.','target':'https://www.marinespecies.org/aphia.php?id=282196&p=taxdetails'},
{'id':'classic','title':'Independent classic coefficient and saved bounds','supports':'Saved SAU taxon-TL coefficient×2019landings÷9once. 22missing coefficients have zero2019landings/PPR; TL stays?. Nopositive2019catch lacks a coefficient. Classic TL/coefs/bounds preserved.','target':'LME_047.xlsx#%27Classic%20PPR%27!A1'}]
for s in sources:s['date']='2026-10-01'
save('appendix_sources.json',sources)
body=f'''# East China Sea source review — {MID}

Selected Xu et al.2022 static M2018 reconstruction is retained; M1997 remains separate. [Main paper]({Path(os.path.relpath(pdf,O)).as_posix()}) and [publisher supplement]({Path(os.path.relpath(supp,O)).as_posix()}) provide the focal source identity, Table1 parameters, S1 membership and S3 diet. No native EwE export was recovered. Retained source hashes are in [identity proof](source_identity_verification.json).

All96Table1 B/PB/QB/EE entries were reviewed; all populated cells match the canonical accepted inputs. The528published S3diet cells include91exact decimal differences: published rounded columns sum between0.999 and1.001 and the accepted canonical JSON uses normalized proportions. All22normalized predator columns match to1e-12. See [parameter comparison](source_parameter_cell_review.json), [raw diet cell comparison](source_diet_cell_review.json) and [normalization provenance](diet_normalization_provenance.json). No numerical input repair was made.

Canonical selected catch fields are absent. Effective group catch0 across25groups is the loader default, not complete measured group catches. S4caption identifies M1997Ecosim time-series; its partial2018catch entries do not constitute a selectedM2018catch vector. Missing GS, migration and accumulation inputs produce accepted defaults/derived accounting closure. Detritus24publishedEE0.241 becomes effectiveEE1; single-detritus routing, syntheticdiet_import25, GS0.2 and accepted diet normalization are preserved. There are no same-taxon stage pairs: large/small yellow croaker names identify distinct species.

[Full direct diagnostics](direct_diagnostics/direct_reports.json) and [all-source inspection](matrix_inspection.json) retain WARN forGE,TEandWithEgestion. Strict production/consumption and primary-production budget balance pass. Sharks22andMammals23haveEE0. TE EEfix yields0for these groups; it is preserved as the accepted method consequence. The direct diagnostic footprint0 uses unverified canonical export0catch, whereas positive SAUlandings generate regional PPR. GE/WithEgestion largest coefficients belong to unfished mammals, so their magnitude does not drive this catch universe. TE living spectral radius0.78412356 is a divergence-proximity warning, not a negative-source failure. Finite coefficients do not establish scientific model approval. Existing production_eligible=true is preserved because no explicit eligibility gate failure was demonstrated.

[All276taxon decisions](taxon_audit.json) compare exact old and revised confidence/components, including zero-catch labels. S1representatives do not define exhaustive family membership. Exact source members retainHigh; extensions and ecological interpretation retainMedium; weak analogues are explicitVerylow. Pennahiaargentata13/18 and Psenopsisanomala16/17 retain both author memberships. Harpadonnehereus retains dedicatedBombayduck15 because the main methods explicitly establish that economic single-species group. Bony residual provider keys100039/100139/100339 exclude dedicatedSharks22but retain eligible ray/bony mixedBenthivores12 and all meaningful named bony source groups. Cartilage and invertebrate broad labels each receive their own rationale. Mola and Scaridae now have positive, weak, alternative-tested analogues rather than unresolved placeholders.

[HistoricalW5review](identified_catch_proxy_review.json) reproduces every20catch-composition fraction from the actual builder: all1950–2019totalcatch rounded annually to0.001t; every solo-mapped label in the eligible guild, no lineage filter. Raw country/gear/sector/reporting/basis/end-use/year strata and donor labels retained; separately reported labels do not prove absence from broad catch. Current27splits use [source-catch/biomass evidence](allocation_evidence.json):12complete positive2018S4catch candidate sets useW4Medium, and15incomplete/censored sets use complete M2018biomass underW9Medium. Same-article2018CFSYcatch lineage overlaps the selected2018/2019survey, but is a calibration/source-catch proxy rather than a verified static-model catch vector. Whole-guild proportions assume target caught-mass composition and common area; fixed proportions transfer acrossyears/fleets/bases. It is not observed stage/species catch composition.

Geography uses the native Figure1caption: “The study area in the East China Sea.” §2.2PDF4ties M2018data to the joint autumn2018/spring2019ECSsurvey. The paper supplies neither a modeled-area denominator nor a separate explicit model boundary. [Native graticule and controls](geography/calibration_and_controls.json) trace the displayed hatch, preserve its actual offshore gap and ordered bends, and pass eightwater controls. Approximate marine study area106,097km²within target779,590km²: A≈13.61%, B≈100%; report ranges10–15%and90–100%are descriptive. NaturalEarthne_50mmeans1:50million scale, not50metres. This is a study/survey footprint, not an exact verified model-domain boundary; no area multiplier is applied toPPR. [Historical whole-LME envelope](geography/historical_whole_LME_envelope.geojson) is preserved and a guarded article-geometry proposal is pending root.

The older Li&Zhang2012publisherDOC is available and A1.8explicitly pools lobsters with coastalPortunus/Charybdis. It supports only compatibleM12transfer for four lobster labels; no coefficients/weights are transferred. FocalLi2012 andCheng2009main PDFs remain unavailable and no historical retrieval count is rewritten. Shared source metadata, geometry/UI, global output, graph andGit integration remain pending root.
'''
# Relative paths from the actual source review directory, preserving parentheses-safe Markdown targets.
import os
body=body.replace(pdf.relative_to(O).as_posix()if pdf.is_relative_to(O)else'__none__','__none__')if False else body
body=re.sub(r'(?<=[A-Za-z])(?=\d)|(?<=\d)(?=[A-Za-z])',' ',body) if False else body
(O/'source_review.md').write_text(body,encoding='utf-8')
snap=Q.parent.parent/'central_source_metadata_current.json';s=json.loads(snap.read_text(encoding='utf-8'));current=sha(ROOT/'Project.xlsx');assert s['project_sha256']==current,(s['project_sha256'],current)
save('central_snapshot_authentication.json',{'project_sha256':current,'snapshot_file_sha256':sha(snap),'authenticated':True,'note':'Expected-old keyed fields retained in proposal; root re-authenticates against newer integration state.'})
print('SOURCE',len(inventory),'dietnormalized',all(x['normalized_column_matches']for x in proof))
