import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {Workbook,SpreadsheetFile,FileBlob} from '@oai/artifact-tool';
const q=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(q,'../../../../..'),region=path.join(root,'regions/LME_035'),mid='35_412_Gulf_of_Thailande_(1963)',ev=path.join(region,'validation_reports',mid),qa=path.join(ev,'qa');
await fs.mkdir(qa,{recursive:true});
const rows=JSON.parse(await fs.readFile(path.join(ev,'taxon_audit.json'),'utf8')).sort((a,b)=>((b.simple_chain_ppr_tC??-Infinity)-(a.simple_chain_ppr_tC??-Infinity))||a.taxon.localeCompare(b.taxon,'en'));
const a=JSON.parse(await fs.readFile(path.join(ev,'coverage_summary.json'),'utf8'));
const sources=JSON.parse(await fs.readFile(path.join(ev,'appendix_sources.json'),'utf8'));
const output=path.join(region,'LME035_taxon_mapping_appendix.xlsx');
if(process.argv.includes('--render')){
 const wb=await SpreadsheetFile.importXlsx(await FileBlob.load(output));
 const longest=rows.map((r,i)=>({i,len:r.reason.length+r.mapping_display.length})).sort((a,b)=>b.len-a.len)[0];
 const previews=[['Taxon mapping','A1:G12','appendix_top'],['Taxon mapping','A128:G133','appendix_middle'],['Taxon mapping','A249:G254','appendix_bottom'],['Taxon mapping',`A${longest.i+8}:G${longest.i+9}`,'appendix_longest'],['Sources','A1:D10','sources_top'],['Sources',`A11:D${sources.length+4}`,'sources_bottom']];
 for(const [sheetName,range,name] of previews){const blob=await wb.render({sheetName,range,scale:1,format:'png'});await fs.writeFile(path.join(qa,name+'.png'),new Uint8Array(await blob.arrayBuffer()));}
 console.log('Final appendix imported and rendered',longest);process.exit(0);
}
const nativeLinks=[];const wb=Workbook.create();const s=wb.worksheets.add('Taxon mapping'),src=wb.worksheets.add('Sources');s.showGridLines=false;src.showGridLines=false;
const last=7+rows.length;s.getRange(`A1:G${last}`).format.font={name:'Calibri',size:11,color:'#222222'};s.getRange('A1:G1').merge();s.getRange('A1').values=[['Gulf of Thailand LME_035 — taxon mapping appendix']];s.getRange('A1:G1').format={fill:'#193D50',font:{name:'Calibri',size:17,bold:true,color:'#FFFFFF'},rowHeightPx:42};
const notes=[`Reference: 2019 landings; selected model ${mid}. All247 exact catch labels.`,`Independent simple trophic chain: saved classic wet coefficient × catch /9 once; tonnes C. Sorted by full unrounded PPR descending; taxon breaks ties.`,`33 labels lack a classic coefficient/TL; all have zero2019 catch and zero annual PPR. ? means unavailable. Mapping coverage does not establish ecological validity.`,`Landings ${a.total_catch_tonnes.toFixed(6)} t; classic PPR ${a.total_simple_chain_ppr_tC.toFixed(6)} t C. Confidence is the weaker membership/allocation component. Very low ${a.confidence_summary.find(r=>r.label==='Very low').taxa} labels contribute ${a.confidence_summary.find(r=>r.label==='Very low').ppr_percentage.toFixed(4)}% of classic PPR.`];
notes.forEach((n,i)=>{const r=i+2;s.getRange(`A${r}:G${r}`).merge();s.getRange(`A${r}`).values=[[n.replaceAll('All247','All 247').replaceAll('zero2019','zero 2019').replaceAll('low116','low 116').replaceAll('contribute60','contribute 60')]];s.getRange(`A${r}:G${r}`).format={wrapText:true,rowHeightPx:i===0?30:36};});
s.getRange('A6:C6').merge();s.getRange('A6').values=[['Sources and limitations']];nativeLinks.push({sheet:1,ref:'A6',target:"#'Sources'!A1"});s.getRange('D6:G6').merge();s.getRange('D6').values=[['Complete candidate decisions and mapping evidence']];nativeLinks.push({sheet:1,ref:'D6',target:'validation_reports/'+mid+'/taxon_audit.json'});s.getRange('A6:G6').format={font:{color:'#0563C1'},rowHeightPx:27};
const headers=['Taxon name','TL','Catch (t)','Simple-chain PPR (t C)','Mapped group names and weights','Confidence level','Reason'];s.getRange('A7:G7').values=[headers];
const vals=rows.map(r=>[r.taxon,r.tl??'?',r.catch_tonnes??'?',r.simple_chain_ppr_tC??'?',r.mapping_display,r.overall_confidence,`Membership ${r.membership_confidence}; allocation ${r.allocation_confidence}. ${r.reason} Sources: ${r.sources.join('; ')}.`]);s.getRange(`A8:G${last}`).values=vals;
const widths=[250,65,135,180,410,112,730];widths.forEach((v,i)=>s.getRange(`${String.fromCharCode(65+i)}1:${String.fromCharCode(65+i)}${last}`).format.columnWidthPx=v);s.getRange(`A7:G${last}`).format={wrapText:true,verticalAlignment:'top'};s.getRange('A7:G7').format={fill:'#DCE8ED',font:{bold:true},rowHeightPx:44};
rows.forEach((r,i)=>{const height=Math.max(95,Math.ceil(vals[i][6].length/100)*19+25,Math.ceil(r.mapping_display.length/54)*19+25);s.getRange(`A${i+8}:G${i+8}`).format.rowHeightPx=Math.min(520,height);if(r.overall_confidence==='Very low')s.getRange(`F${i+8}`).format.fill='#FAE6CE';});
s.getRange(`B8:B${last}`).setNumberFormat('0.00');s.getRange(`C8:D${last}`).setNumberFormat('#,##0.000000;[Red](#,##0.000000);0.000000');s.tables.add(`A7:G${last}`,true,'ThailandMappingTable');s.freezePanes.freezeRows(7);s.freezePanes.freezeColumns(1);
const sl=sources.length+4;src.getRange(`A1:D${sl}`).format.font={name:'Calibri',size:11,color:'#222222'};src.getRange('A1:D1').merge();src.getRange('A1').values=[['Descriptive sources — scope and limitations']];src.getRange('A1:D1').format={fill:'#193D50',font:{bold:true,color:'#FFFFFF',size:17},rowHeightPx:40};src.getRange('A2:D2').merge();src.getRange('A2').values=[['Local links are relative to this workbook. Ecology/taxonomy supports membership; model catch/biomass weights remain historical composition assumptions.']];src.getRange('A2:D2').format={wrapText:true,rowHeightPx:32};src.getRange('A3:D3').merge();src.getRange('A3').values=[['Return to taxon mapping']];nativeLinks.push({sheet:2,ref:'A3',target:"#'Taxon mapping'!A1"});src.getRange('A3:D3').format={font:{color:'#0563C1'},rowHeightPx:25};src.getRange('A4:D4').values=[['Source / material','What it supports / limits','Link','Retrieved / reviewed']];src.getRange(`A5:D${sl}`).values=sources.map(r=>[`${r.id}: ${r.title}`,r.supports,'Open source',r.date??'2026-09-30']);
sources.forEach((r,i)=>nativeLinks.push({sheet:2,ref:`C${i+5}`,target:r.target}));src.getRange(`C5:C${sl}`).format.font={color:'#0563C1'};[380,740,190,160].forEach((v,i)=>src.getRange(`${String.fromCharCode(65+i)}1:${String.fromCharCode(65+i)}${sl}`).format.columnWidthPx=v);src.getRange(`A4:D${sl}`).format={wrapText:true,verticalAlignment:'top'};src.getRange('A4:D4').format={fill:'#DCE8ED',font:{bold:true},rowHeightPx:35};src.getRange(`A5:D${sl}`).format.rowHeightPx=115;src.tables.add(`A4:D${sl}`,true,'ThailandSourcesTable');src.freezePanes.freezeRows(4);
wb.recalculate();const blob=await SpreadsheetFile.exportXlsx(wb);await blob.save(output);await fs.writeFile(path.join(q,'hyperlinks.json'),JSON.stringify(nativeLinks,null,2),'utf8');await fs.writeFile(path.join(qa,'appendix_inspection.ndjson'),(await wb.inspect({kind:'table',range:'Taxon mapping!A7:G10',include:'values,formulas',maxChars:2500})).ndjson);console.log('APPENDIX_EXPORTED',rows.length,sources.length);
