from pathlib import Path
import json,hashlib
P=Path(__file__).resolve().parent
sources=[]
def add(i,title,loc,url,scope,read='Local original read'):
 sources.append({'id':i,'description':title,'locator':loc,'link_from_region':url,'supports':scope,'material_read':read,'retrieved':'2026-10-03' if url.startswith('http') else None})
pdf='papers/CAN-2014/file-e30dfe50.pdf';doc='papers/CAN-2014/pone.0094742.s001-eb18ca66.docx'
add('SRC_P2','Guénette, Meissa & Gascuel (2014). Assessing the Contribution of Marine Protected Areas to the Trophic Functioning of Ecosystems. PLoS ONE9:e94742.','PDF p2, Model structure',pdf+'#page=2','Modeled shelf <200 m; fish habitat categories; six juvenile age0–1/adult pairs; no discard observations.')
add('SRC_T1','Guénette et al. (2014), original publisher Table1 XLS and article Table1.','XLS Table_1; group ID in A, name B, biomass D, reported total catch N','papers/CAN-2014/Table_1-f0424c0e.xls','Exact final 51 source group identities; Base catches and biomass. Catch zeros are source reported. Fleet sums differ from printed totals for some rows; allocation uses the explicit reported Total field.')
add('SRC_S1','Guénette et al. (2014), Supplement Text S1, Table S1: Composition of fish functional groups.','DOCX table1, body element72',doc,'Verbatim source fish membership. Hake ID30 conflicts with final Octopus ID30; apparent wrasse/selacian placement retained as conflict.')
add('SRC_S1_TEXT','Guénette et al. (2014), Supplement Text S1.','Fish, Fishing data, Cephalopods, Plankton, Benthic fauna sections',doc,'Composition and habitat descriptions; octopus versus other cephalopods. Diet-study examples are not exhaustive species inventories.')
add('SRC_S6','Guénette et al. (2014), Supplement Table S6: Benthos biomass and production.','DOCX table8, body element101',doc,'Banc/shelf large and small crustaceans, molluscs, worms, other invertebrate composition; source taxonomic inconsistencies retained.')
add('SRC_S8','Guénette et al. (2014), Supplement Table S8.','DOCX table10, body element113',doc,'Variant-specific biomass values. Shared composition/catch not independently republished for M30/P30; Base inheritance is explicit.')
add('CATCH','Sea Around Us regional catch labels and annual quantities, frozen from LME_027 workbook.','Catch / Catch; one exact taxon per basis;1950–2019','LME_027.xlsx','Exact label/common name/functional/commercial context. Provider functional class alone is not an exhaustive membership boundary.')
add('CLASSIC','Frozen independent classic/simple trophic-chain coefficients and regional settings.','Classic PPR / Taxa and Annual; Overview transfer_efficiency=0.1','LME_027.xlsx','Existing taxon-specific TL/coefficient reused without imputation. Catch×coefficient÷9=t C. Zero catch contributes0 despite absent coefficient.')
add('TAX_ARIUS','WoRMS taxonomy: Arius heudelotii accepted as Carlarius heudelotii.','Arius species list','https://marinespecies.org/traits/aphia.php?p=taxlist&pid=154659&rComp=%3E%3D&tRank=220','Verified source/catch synonym for catfish stage pair.','Search-returned taxon list read')
add('TAX_CHELON','OBIS/WoRMS taxon126978: Liza aurata accepted as Chelon auratus.','Taxon126978','https://obis.org/taxon/126978','Verified source/catch synonym.','Search-returned entry read')
add('TAX_BALISTES','World Register of Marine Species dataset: Balistes capriscus.','WoRMS taxname154721, synonym Balistes carolinensis','https://www.gbif.org/dataset/2d59e5db-57ad-41ff-97d6-11f5fb264527/taxon/urn%3Alsid%3Amarinespecies.org%3Ataxname%3A154721','Verified source/catch synonym; corroborated by Eschmeyer catalog species23282.','Search-returned WoRMS dataset entry and CAS nomenclatural note read')
add('TAX_DASYATIS','WoRMS Dasyatis taxon list.','Dasyatis centroura accepted as Bathytoshia centroura','https://www.marinespecies.org/aphia.php?p=taxlist&tName=Dasyatis','Verified source/catch synonym, retaining the source historical geographic concept.','Search-returned taxon list read')
add('TAX_RHINOBATOS','WoRMS Rhinobatos taxon list.','Rhinobatos cemiculus accepted as Glaucostegus cemiculus','https://www.marinespecies.org/aphia.php?p=taxlist&tName=Rhinobatos','Verified source/catch synonym.','Search-returned taxon list read')
add('TAX_TRIGLOPORUS','OBIS/WoRMS taxon154462: Trigloporus lastoviza.','Accepted name Chelidonichthys lastoviza','https://obis.org/taxon/154462','Verified source/catch synonym; also visible in regional Canary biodiversity taxonomic record.','Search-returned entry read')
add('TAX_AETOMYLAEUS','IUCN Red List2021 Aetomylaeus bovinus; taxonomic notes citing White2014.','Taxonomic notes, generic synonymy','https://doi.org/10.2305/IUCN.UK.2021-1.RLTS.T60127A124441812.en','Pteromylaeus placed in synonymy of Aetomylaeus; bull-ray name crosswalk.','Search-returned assessment text read')
add('TAX_SCOMBER','WoRMS Scomber japonicus taxon list.','S. japonicus colias accepted as S. colias','https://www.marinespecies.org/aphia.php?p=taxlist&tName=Scomber+japonicus','Supports historical Atlantic chub-mackerel interpretation, not an exact synonym claim between S. japonicus sensu stricto and S. colias.','Search-returned taxon list read')
add('IMROP_GUIDE','IMROP Guide et nomenclature nationale commerciale des espèces marines.','Alectis alexandrinus entry and synonym Scyris alexandrina','https://www.imrop.mr/wp-content/uploads/2022/01/Guide_Nomenclature_Nationales_especes_Marines.pdf','Regional authority corroborates source/catch name link.','Search excerpt read; attempted full PDF open returned Internal Error, not described as full-text access')
add('SHRIMP_HABITAT','Schaffmeister et al. (2006). Habitat use of shrimps in the intertidal and shallow subtidal seagrass beds of tropical Banc d’Arguin. Journal of Sea Research55:230–243.','Abstract and species-composition text','https://doi.org/10.1016/j.seares.2005.10.003','Penaeus nursery-to-offshore movement and Banc shrimp composition. January–March2002 small-area number densities are not all-LME caught-mass fractions.','Publisher abstract and section excerpts read')
add('WB_HABITAT','Mauritanian offshore environmental assessment archived by World Bank (2005).','Table4.7, invertebrate habitats','https://documents1.worldbank.org/curated/en/503821468056369578/pdf/E14870v10CD0En1rt0with0Appendices01.pdf','Shelf/slope habitat differences among Parapenaeus, Penaeus, Aristeus and Palinurus; no measured allocation for model Banc/shelf pools.','Search-returned Table4.7 excerpt read')
add('FAO_DEMERSAL','FAO/CECAF Working Group assessment of demersal resources, Subgroup North, Banjul2007 (10/71).','Sections3.9–3.10 croaker and grouper','https://www.fao.org/docrep/015/i2545b/i2545b00.pdf','Croaker sampling not raised to total catch; grouper young <30cm habitat. Does not supply all-group, age0–1 caught-mass partitions for target LME/bases/years.','PDF text opened; targeted returned sections read')
add('FAO_LENGTH','FAO Description et évaluation des ressources halieutiques de la ZEE mauritanienne.','Length-frequency demographic analysis','https://www.fao.org/4/R9048F/R9048F12.htm','Historical stratified survey number frequencies available for several demersal species; not adopted as catch mass without length-weight, stage-age and fleet weighting.','Search-returned detailed text read; full page open failed')
add('FAO_ANNEX','FAO regional annexes: Results from the Length Measurements.','Annex III and Arius heudeloti entry','https://www.fao.org/4/x6035e/x6035e07.htm','Length-measurement tables identified, not a matching published stage-mass allocation.','Page opened; targeted search entry/annex context read')
add('MEISSA_GROUPER','Meissa, Gascuel & Rivot2013 white grouper assessment, reproduced in IMROP thesis.','Article pp253–267; survey and handline catch context','https://www.imrop.mr/wp-content/uploads/2021/01/these_-beyah-VF-1.pdf','Mauritanian species-specific catch/survey data; no complete compatible age0–1 mass split recovered.','Search excerpt read; attempted full PDF open failed')
add('IMARES_DISCARDS','Goudswaard & Ould Meissa (2006). Discards in Mauritanian shrimp fisheries: an evaluation of lost value. IMARES C067/06.','Report pp5–7,18–19,23; meagre length-frequency discussion','https://www.researchgate.net/publication/40112515_Discards_in_the_Mauritanian_shrimp_fisheries_an_evaluation_of_lost_value','Author report describes2004–06 shrimp-fishery discards and young meagre. This contradicts treating source juvenile zero catch as observed across all target fleets/bases. Number frequencies and one fishery cannot replace the target age0–1 mass partition.','Search-returned author-report text read; not claimed as independently downloaded original PDF')
queries=[
('SEARCH_STAGE_1',['site.fao.org Mauritania meagre Argyrosomus regius juvenile catch length composition 1991','site.fao.org CECAF Mauritania Pseudotolithus Epinephelus length frequency catch 1991','site.fao.org Mauritania seabream sparid catfish catch length juvenile adult'],['FAO_DEMERSAL','FAO_LENGTH'],'No complete matching observed stage-mass vector recovered. Survey frequencies, growth and legal-size evidence cannot be used directly as age0–1 caught-mass fractions.'),
('SEARCH_STAGE_2',['site.fao.org Arius Mauritania length frequency juvenile catch','Mauritania "Arius" "length frequency" catch','Mauritania "seabream" "juvenile" "catch" age'],['FAO_ANNEX','FAO_LENGTH'],'Results include length-frequency material and out-of-region/different-species catfish studies; no matching mass fraction adopted. Unrelated Arius arius/thalassinus studies rejected.'),
('SEARCH_STAGE_3',['Mauritania "Argyrosomus" "age" "catch" juvenile 1991 2006','Mauritania "Epinephelus aeneus" "age" "catch" 1991 2013 Meissa','"Discards in the Mauritanian shrimp fisheries" C067 2006 Wageningen pdf'],['MEISSA_GROUPER','IMARES_DISCARDS'],'Regional discard evidence demonstrates juvenile catch. The study is later, one fleet, and length frequencies are numbers without a complete target age0–1 mass conversion. Retain W4 as a source proxy with consequential basis/year assumptions, not observed absence.'),
('SEARCH_GEOGRAPHY',['Mauritania Banc Arguin shrimps molluscs crustaceans catch geographical distribution mass catch composition'],['SHRIMP_HABITAT','WB_HABITAT'],'Habitat/nursery and benthic biomass studies found. No complete matching caught-mass quantities across exact Banc and shelf pools. Geographic occurrence or juvenile nursery contribution is not W10.')]
searches=[{'id':i,'date':'2026-10-03','queries':q,'material_references':refs,'result':result,'adopted_observed_weights':False,'scope_limit':'Bounded search; does not establish data are nonexistent.'} for i,q,refs,result in queries]
excerpts={'FAO_DEMERSAL':'length frequency samples not raised to total catch','FAO_LENGTH':'une unique distribution de fréquence représentative en nombre','IMARES_DISCARDS':'the great majority of the fishes are below 40 cm and immature','SHRIMP_HABITAT':'migrating offshore as adults','IMROP_GUIDE':'Scyris alexandrina','TAX_SCOMBER':'Scomber japonicus colias Gmelin, 1789 accepted as Scomber colias Gmelin, 1789'}
for s in sources:
 if s['id'] in excerpts:s['retained_short_excerpt']=excerpts[s['id']]
(P/'sources.json').write_text(json.dumps(sources,ensure_ascii=False,indent=2),encoding='utf8')
(P/'online_search_evidence.json').write_text(json.dumps({'searches':searches,'source_records':sources[8:],'taxonomy_queries':['site.marinespecies.org Scomber colias japonicus Balistes carolinensis capriscus','site.marinespecies.org "Balistes carolinensis" "capriscus"','site.marinespecies.org "Arius heudelotii" "Carlarius"','site.marinespecies.org "Pteromylaeus bovinus" "Aetomylaeus"','site.marinespecies.org "Liza aurata" "Chelon auratus"','"Bathytoshia centroura" "Dasyatis centroura" site.marinespecies.org','"Glaucostegus cemiculus" "Rhinobatos cemiculus" site.marinespecies.org','"Scyris alexandrina" "Alectis alexandrinus" site.marinespecies.org','"Chelidonichthys lastoviza" "Trigloporus lastoviza" site.marinespecies.org','"Pteromylaeus bovinus" "Aetomylaeus" White 2014 revision']},ensure_ascii=False,indent=2),encoding='utf8')
# Human-readable rule names and grouped Very-low reasons for the Word builder.
rules={'M1':'Explicit species assignment in the source composition table','M2':'Verified synonym of an explicitly listed source species','M3':'Unambiguous fit to the documented residual cephalopod group','M4':'Supported extension from listed regional representatives','M5':'Supported ecological extension to a documented guild','M6':'Partial or conflicting ecological fit','M9':'Assumed eligible group set supported by source taxonomy and ecology','M10':'Broad reporting category approximated across compatible groups','M11':'Closest represented analogue despite habitat or taxonomic mismatch','W1':'One eligible group; no allocation split needed','W4':'Source-model1991 reported catch proportions, assumed across target years and bases','W9':'Model-biomass proportions when complete candidate catches have zero total'}
maps=json.loads((P/'Base_mapping_evidence.json').read_text(encoding='utf8'))['mapping']
grouped={}
for d in maps:
 if d['overall_confidence']=='Very low':grouped.setdefault(d['membership_reason'],[]).append(d['taxon'])
(P/'report_mapping_text.json').write_text(json.dumps({'reference':'2019 landings; retained catch universe includes zero labels.','method':'Independent simple trophic chain using saved taxon coefficients; 51 source ecological groups.','confidence_note':'Overall confidence is the weaker membership or allocation confidence. Each rule percentage is its share of independent simple-chain PPR.','missing_note':'100 labels lack a saved TL/coefficient. All have zero recorded2019 landings, so each contributes zero annual PPR and the reference total is complete. Coefficients themselves remain unavailable.','unresolved_note':'No unresolved mappings remain; high mapping coverage includes explicitly assumed broad categories and analogues.','source_limit':'The source reports juvenile catches as zero and has no discard observations. Those zeros supply a historical catch-composition proxy, not evidence that target discards or later catches contain no juveniles.','rule_names':rules,'very_low_decisions':[{'taxa':names,'reason':reason} for reason,names in grouped.items()]},ensure_ascii=False,indent=2),encoding='utf8')
print('sources',len(sources),'searches',len(searches),'very-low groups',len(grouped))
