const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm'),path=require('node:path');
const root=process.cwd(),map=fs.readFileSync(path.join(root,'interactive_map/index.html'),'utf8'),trend=fs.readFileSync(path.join(root,'interactive_map/trends.html'),'utf8');
function payload(page,name){const start=page.indexOf('const '+name+'=')+('const '+name+'=').length;const ends=[page.indexOf(';\n',start),page.indexOf(';</script>',start)].filter(i=>i>=0);return JSON.parse(page.slice(start,Math.min(...ends)));}
const catalog=payload(map,'DB'),series=payload(trend,'SERIES_DB'),unit=catalog.network.units.LME_013,id='Chiaverano2018_detailed_Northern_Humboldt_1995_1998',mi=unit.models.findIndex(m=>m.id===id),model=unit.models[mi],sm=series.units.LME_013.models.find(m=>m.id===id);
const excluded=['Cetaceans','Fishery offal','Pinnipeds','Seabirds','Chrysaora plocamia'];
assert.deepEqual(model.researcher_review,sm.researcher_review);assert.equal(model.researcher_review.status,'Validated by researcher');assert.equal(model.researcher_review.researcher_name,'Ido Carmel');assert.equal(model.researcher_review.review_date,'2026-10-08');
assert(model.researcher_review.sections[2].rows[0].text.includes("det_collapse_mode='auto'"));assert.deepEqual([...model.display_ppr_excluded_group_ids].sort(),[...excluded].sort());
const start=map.indexOf('/* Shared annual denominator lookup.'),ctx={};vm.createContext(ctx);vm.runInContext(map.slice(start,map.indexOf('/* Rank the full chosen geography;',start)),ctx);
const metrics=vm.runInContext('PPRMetrics',ctx),groups=vm.runInContext('PPRGroups',ctx),selection=groups.selection(model);
assert.equal(selection.count,model.group_data.groups.length-5);assert(excluded.every(g=>!selection.ids.includes(g)));
const raw=structuredClone(model);delete raw.display_ppr_excluded_group_ids;delete raw.researcher_review;const rawUnit={...unit,models:unit.models.map((m,i)=>i===mi?raw:m)};
const close=(a,b,key)=>{if(a==null||b==null)return assert.equal(a,b,key);assert(Math.abs(a-b)<=Math.max(1e-6,Math.abs(b)*1e-12),key+': '+a+' vs '+b);};let cases=0;
for(const [scope,data] of Object.entries(model.scopes))for(const method of data.methods)for(const basis of ['landings','catch','discards']){
 const state={unit_id:'LME_013',mode:'ppr',scope,method,year:2019,catch_basis:basis,unidentified:'method',simple_unit:catalog.network.simple_units.LME_013};const a=metrics.evaluate(unit,mi,state),b=metrics.evaluate(rawUnit,mi,state);for(const key of ['catch','total_catch','coverage','total_catch_all','total_discards','unidentified_catch'])close(a[key],b[key],key);cases++;
}
assert(cases>0);for(const mode of ['b','rho_living'])assert.deepEqual(metrics.evaluate(unit,mi,{mode,te:'GE'}),metrics.evaluate(rawUnit,mi,{mode,te:'GE'}));
class Element{constructor(tag,text=''){this.tag=tag;this.textContent=text;this.children=[];this.className='';}appendChild(c){this.children.push(c);return c;}setAttribute(k,v){this[k]=v;}}
const document={createElement:tag=>new Element(tag),createTextNode:text=>new Element('#text',text)},view={document};vm.createContext(view);vm.runInContext(fs.readFileSync(path.join(root,'tools/project_core/maps/researcher_review.js'),'utf8'),view);const renderer=vm.runInContext('PPRResearcherReview',view),panel=new Element('div');assert(renderer.append(panel,model));assert(renderer.isValidated(model));const text=e=>e.textContent+e.children.map(text).join('');assert(text(panel).includes("det_collapse_mode='auto'"));assert(!text(panel).includes('Model not yet validated'));assert.equal(panel.children[0].children.filter(e=>e.tag==='h4').length,6);
const named=new Element('div');renderer.appendName(named,model);assert(named.children.some(e=>e.className==='researcher-validated-name'));
fs.writeFileSync(path.join(__dirname,'../qa/frontend_checks.json'),JSON.stringify({status:'PASS',review_source_equal_in_both_pages:true,conditional_auto_text_rendered:true,validated_filter_eligible:true,green_name_class:true,five_mandatory_exclusions:true,catch_and_coverage_cases_unchanged:cases,diagnostic_values_unchanged:true,verification:'production JavaScript evaluated in Node VM; native browser not available'},null,2));console.log('LME_013 frontend PASS: conditional auto review, green name, five exclusions, unchanged catch/coverage and diagnostics.');
