from pathlib import Path
import json

OUT=Path(__file__).resolve().parent
DATE='2026-10-03'
mapping=json.loads((OUT/'mapping_review.json').read_text(encoding='utf-8'))
rows=mapping['taxa']
records=[]
def add(identifier,taxa,raw,topics,urls,read_scope,finding,rejection):
    records.append({'id':identifier,'searched_utc_date':DATE,'taxa':taxa,'raw_search_evidence':raw,'search_topics':topics,'primary_source_urls':urls,'read_scope':read_scope,'finding':finding,'decision':'No observed allocation adopted; source landings or biomass used only as an explicit assumption where a split is required.','reason_observed_composition_not_adopted':rejection,'observed_proportion_adopted':False})

hakes=['Merluccius peruanus','Merluccius gayi','Merluccius australis','Macruronus magellanicus','Micromesistius australis','Gadiformes']
add('S01_hake_size',hakes,['search_batch_1.json','search_batch_2.json','search_batch_3.json','search_batch_4.json','search_batch_8.json','search_batch_11.json','search_final_1.json'],['IMARPE 2019 caught hake length structure','IMARPE 1995–1998 Peruvian hake length structure','IFOP 2018–2019 Merluccius gayi/australis, Macruronus and Micromesistius caught lengths'],['https://repositorio.imarpe.gob.pe/server/api/core/bitstreams/efeadc99-888b-41fb-aba1-5e0396136e06/content','https://www.ifop.cl/wp-content/contenidos/uploads/RepositorioIfop/InformeFinal/2019/P-581141b.pdf','https://www.ifop.cl/wp-content/contenidos/uploads/RepositorioIfop/InformeFinal/2020/P-682069.pdf','https://www.ifop.cl/eem/wp-content/uploads/sites/25/2025/html_docs/mgayi_spec_doc_html.html','https://revistas.utm.edu.ec/index.php/latecnica/article/view/5289'],'Primary indexed text and chart descriptions. Full IMARPE PDF failed via web (502), default network denied, then approved read-only download failed TLS certificate verification. IFOP PDF/HTML full opens exceeded provider content limits. No raw size-bin dataset or extracted full caught-mass table was obtained.','The 2019 industrial Peruvian fishery gives total-length range, mean, mode and a fraction below 28 cm. IFOP describes number-frequency histograms for particular Chilean fleets, with very different southern hake lengths; Ecuador study concerns January–August 2019 industrial catches. These are useful mismatch evidence.','The summary below 28 cm is not the source <29/30–49/>50 partition; mean/modal length, minimum legal size and counts cannot become caught-mass fractions. Source length convention and endpoint gaps are unknown. Sample fleets/geography do not cover the full LME/all bases; source-model stage landings are disclosed as a transferred proxy.')

add('S02_pelagic_family',['Scombridae','Scombroidei','Clupeidae','Clupeiformes','Carangidae'],['search_batch_5.json','search_batch_10.json','search_final_2.json','search_final_4.json'],['IMARPE 2019 Scombridae/Clupeidae/Carangidae landings','IMARPE Clupeiformes/Scombroidei reporting','Regional pelagic species composition and annual catch statistics'],['https://repositorio.imarpe.gob.pe/server/api/core/bitstreams/8428a438-715c-4a06-a742-7872f6e837a1/content','https://reportes.imarpe.gob.pe/archivos/informes/eval_poi_tercer_trim2019.pdf'],'Primary indexed passages; no complete label-specific caught-mass table.','IMARPE records multiple regional carangids, and local monitoring reports anchovy dominance in an industrial fleet and bonito dominance in a different artisanal fleet. These are observed fishery-specific compositions.','A fleet/locality catch total is not the composition of a SAU family/order residual label across Peru and Chile. Applying whole-fishery shares would mix separately reported named catches and unidentified categories. No defensible observed fraction for the exact recorded family label was established.')

add('S03_demersal_family',['Sciaenidae','Larimus pacificus','Stellifer minor','Serranidae','Haemulidae','Scorpaeniformes'],['search_batch_5.json','search_batch_7.json','search_batch_9.json','search_final_2.json','search_final_3.json'],['IMARPE Larimus/Stellifer caught lengths and regional sciaenids','2019 Sciaenidae/Serranidae/Haemulidae demersal catch composition'],['https://repositorio.imarpe.gob.pe/server/api/core/bitstreams/9b6206d2-e2e7-4f2b-b69f-dcdaf3658eae/content','https://reportes.imarpe.gob.pe/archivos/informes/eval_poi_cuarto_trim2019.pdf'],'Primary indexed species tables and regional monitoring passages, not complete full-LME caught-mass fractions.','Small sciaenids occur in coastal catches. Local annual monitoring identifies hake, snake eel, mullet, bass and butterfish proportions within one demersal fishery. Source small and medium guilds lack numerical size bounds.','Local samples do not reconstruct the exact family or species mass split into incompletely bounded model guilds. No observed regional mass allocation between Small demersal fish and Medium sciaenids/demersal fish was established; all competing eligible groups and the whole-group proxy limitation remain explicit.')

add('S04_cartilaginous',['Galeorhinus galeus','Squalus acanthias','Deania calceus','Hexanchus griseus','Batoidea','Elasmobranchii','Myliobatidae','Chondrichthyes','Mobula birostris','Callorhinchus callorynchus'],['search_batch_6.json','search_batch_9.json','search_final_3.json'],['FAO shark/batoid habitats','IMARPE elasmobranch/batoid catch compositions','Filter-feeding manta versus apex-predator source guild'],['https://www.fao.org/4/X2098E/X2098E11.htm','https://biogeodb.stri.si.edu/sftep/en/thefishes/species/81','https://repositorio.imarpe.gob.pe/bitstreams/c45cb0d0-cd7e-4720-8da8-80dc6363cb88/download'],'FAO Galeorhinus page and Smithsonian smoothhound species page opened in full; other FAO/IMARPE results read as primary indexed passages.','FAO supports bottom and pelagic Galeorhinus occurrence, regional smoothhounds are bottom-associated, and IMARPE records manta landings. Broad batoid/elasmobranch classes can include pelagic filter-feeding rays; chimaeras are Holocephali rather than Elasmobranchii.','Habitat occurrence is not measured caught-mass composition. No observed whole-LME split into the source benthic and water-column pools was established. Broad categories retain unsupported feeding/lineage constituents and receive Very low overall confidence even when some members fit well.')

add('S05_mollusc_squid',['Mollusca','Teuthida'],['search_batch_3.json','search_batch_5.json','search_batch_10.json','search_batch_11.json','search_final_4.json'],['IMARPE marine invertebrate species landings 2013/2016/2019','Teuthida squid-only catches and unidentified mollusc reporting'],['https://repositorio.imarpe.gob.pe/items/64dadf25-2e82-40fc-a9f7-991a8c4a69cb','https://repositorio.imarpe.gob.pe/bitstreams/61c16a34-a864-4cd5-8dee-edecc62f7284/download','https://www.imarpe.gob.pe/imarpe/archivos/reportes/imarpe_reportes_invertebrados_setiembre_2019.pdf','https://repositorio.imarpe.gob.pe/items/ccaf8326-3072-429e-be44-1be36234fb3d'],'Primary repository abstract and indexed paper/report text. World squid repository full open failed. No full-LME exact residual-label table.','Regional commercial reporting includes benthic molluscs and cephalopods. National 2016 invertebrate totals and 2019 Callao monthly reports contain actual landings, but include multiple invertebrate phyla, separately named species and restricted localities/periods.','These aggregates cannot give unidentified Mollusca or Teuthida composition across the full LME. Other cephalopods contains octopus as well as squid, so whole-group landings remain an assumed proxy for Teuthida; no observed squid-only fraction is claimed.')

crust=['Decapoda','Malacostraca','Miscellaneous marine crustaceans','Galatheidae','Grimothea monodon']
add('S06_crustacean',crust,['search_batch_6.json','search_batch_10.json','search_batch_11.json','search_final_4.json'],['IMARPE pelagic Grimothea/Pleuroncodes survey catches','Regional benthic/pelagic Decapoda and Malacostraca catch composition'],['https://www.imarpe.gob.pe/wp-content/uploads/2025/09/20250424_1200-Informe_Crucero_2502_04_de_Evaluacion_Hidroacustica_de_Anchoveta_y_otros_Recursos_Pelagicos-Pesca_Artesanal-1.pdf','https://revistas.imarpe.gob.pe/index.php/boletin/article/view/111'],'IMARPE crustacean catalogue HTML opened in full; 2025 scientific survey read as indexed primary passages.','The catalogue establishes taxa/distribution; midwater scientific catches contain substantial Grimothea monodon. This supports a meaningful pelagic/benthic analogue, while the source Macrozooplankton 2–20 mm size range misses larger harvested squat lobsters.','Scientific survey proportions are not commercial catch-label proportions and refer to 2025, with varying latitude. Catalogue presence is not allocation. Both source Macrozooplankton and Macrobenthos landings are explicit zeros, so no catch normalization exists; complete source biomasses are used as an assumed catchability/composition fallback.')

broad=[r['taxon'] for r in rows if r['very_low_group']=='fish_broad']
add('S07_broad_fish',broad,['search_batch_1.json','search_batch_3.json','search_batch_5.json','search_batch_10.json','search_final_3.json','search_final_4.json'],['SAU reporting definitions and unidentified marine fish','IMARPE/IFOP broad groundfish/pelagic catches versus residual-label composition'],['https://api.seaaroundus.org/catch-reconstruction-and-allocation-methods/','https://reportes.imarpe.gob.pe/archivos/informes/eval_poi_cuarto_trim2019.pdf','https://www.sernapesca.cl/informacion-utilidad/consumo-de-cuotas/'],'SAU methods page opened in full. Other primary results indexed. Final Humboldt/unidentified query also returned unrelated Humboldt County results, which were excluded.','Reporting taxon, commercial group and functional category have different scopes. Local national/fleet totals and quota resources do not state the constituents of the exact unidentified LME catch label. Current taxonomy cannot reconstruct historical Perciformes or Scorpaeniformes reporting composition.','No directly applicable observed residual-label composition was found. All defensible named and residual pools remain candidates, including zero-landings source groups. Provider habitat/maximum-size tags do not justify treating broad reported composition as observed. This is a Very low broad approximation, with fixed native landings and all assumptions exposed.')

add('S08_analogue_ecology',['Ophichthus','Galaxias maculatus','Hoplostethus atlanticus','Dissostichus eleginoides'],['search_batch_5.json','search_batch_7.json','search_final_3.json'],['Regional anguila versus congrio commercial nomenclature','NIWA Galaxias marine larval/freshwater adult habitat','FishBase orange roughy deep habitat'],['https://repositorio.imarpe.gob.pe/bitstreams/0bc833fc-9c71-4826-8b79-cc8d421c8fff/download','https://niwa.co.nz/lakes/freshwater-update/freshwater-update-75-november-2017/new-science-inanga','https://www.fishbase.se/summary/334'],'Primary/authority indexed text, with no observed allocation adopted.','Taxonomic identity and real life-history/depth mismatches support closest analogue decisions rather than treating broad model names as explicit species membership.','Ecology evidence informs Very low membership only; no within-population empirical catch allocation is implied by a one-group weight of 1.')

add('S09_taxonomic_alias',['Doryteuthis gahi','Merluccius peruanus','Odontesthes regia','Labrisomus philippii','Fissurella cumingi'],['search_batch_2.json','taxonomy_authority_records.json'],['WoRMS/MolluscaBase accepted names','OBIS Loligo gahi accepted taxon'],['https://obis.org/taxon/341880','https://www.marinespecies.org/aphia.php?p=taxlist&pid=125473&rComp=%3E%3D&tRank=220'],'OBIS entry opened in full, WoRMS list indexed and prior primary authority API records retained with original evidence date.','Source Loligo gahi maps to Doryteuthis gahi; source Merluccius gayi peruanus maps to accepted M. peruanus. Odonthestes/philippi are documented source orthographic corrections; catch Fissurella cumingi retains the reported label with accepted cumingii authority record.','Taxonomic equivalence does not remove size-allocation, spatial applicability or source-version uncertainties. No membership of other modern hake species is inferred from the historical subspecies name.')

exact_batches=[]
for i in range(1,5):
    raw=json.loads((OUT/f'search_final_{i}.json').read_text(encoding='utf-8'))
    exact_batches.append({'date':DATE,'raw_result':f'search_final_{i}.json','actual_queries':raw['queries']})
ledger={'searched_utc_date':DATE,'scope':'Independent catch-label membership and allocation searches; source proxy only after no applicable observed proportions established.','search_evidence_policy':'Raw early provider outputs retain primary results and failures. Early query topics are contextual summaries, not fabricated verbatim query strings. Final four exact query batches retain executed arguments with outputs. Secondary mirrors and unrelated results were rejected; indexed passages are labeled as such and never called full text.','actual_query_batches':exact_batches,'records':records,'applicable_observed_composition_adopted':False,'note':'Source-native catch fractions and biomass fractions are modeled proxies, not observed LME composition. Every multi-group allocation retains its raw denominator and eligible zero candidates.'}
(OUT/'search_records.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2),encoding='utf-8')
print('Saved',len(records),'curated records,',sum(len(x['actual_queries']) for x in exact_batches),'exact final queries')
