from pathlib import Path
import sys,json,csv
MODEL=Path(__file__).resolve().parent;REGION=MODEL.parents[1];ROOT=REGION.parents[1]
sys.path.insert(0,str(ROOT/'tools'))
from workbooks import *
E=MODEL/'selection_20260928';MID=MODEL.name

def main():
    b=read_book(REGION/'LME_014.xlsx');o=overview(b)
    audit=json.loads((E/'selected_results_validation.json').read_text())
    coverage=list(csv.DictReader((E/'mapping_coverage.csv').open(encoding='utf-8-sig')))
    mapping=list(csv.DictReader((E/'mapping_review.csv').open(encoding='utf-8-sig')))
    annual=[r for r in records(b,'PPR','Annual') if r['scope']=='all' and r['catch_basis']=='landings' and r['unidentified']=='method' and r['metric']=='ppr']
    ratios={r['method']:r[2019] for r in records(b,'PPR–NPP','Ratios') if r['model_id']==MID and r['scope']=='all' and r['catch_basis']=='landings' and r['unidentified']=='method' and r['npp_method']=='ens_median_tC_yr'}
    methods={'new_GE':'GE','new_TE_EEfix':'TE','new_WithEgestion':'With Egestion'}
    lines=[
      '# LME_014 — selected native model and regional calculation',
      '',
      'Updated 2026-09-28. The user selected **PAT2024_FalklandShelf_2020_native** because it did not fail. The exact ID and rationale are saved in [LME_014.xlsx](../../LME_014.xlsx), Overview. GE, TE and With Egestion all remain **WARN**, not OK. The selected regional calculation is complete and validated. Central registration/consolidation is queued for the parent task; this task did not write Project.xlsx.',
      '',
      'The earlier source reports and extraction comparison are frozen preselection evidence. Their statements that no model was selected describe that earlier stage. This report is the current selection record.',
      '',
      '## What was selected',
      '',
      '| Candidate | Evidence and outcome | Selection |',
      '|---|---|---|',
      '| PAT2024_FalklandShelf_2020_native | Exact author-supplied native 2020 database; coupled completion of unknown living/producer B and EE; GE / TE / With Egestion = WARN / WARN / WARN | Selected by the user |',
      '| PAT2024_FalklandShelf_2020_published_tables | Article Table 4 plus supplements retained separately; no documented alignment of the one-detritus S2 diet with two final detritus pools | Not selected; all three NOT_RUN |',
      '| OcampoReinaldo2016_SanMatiasGulf_1970 | Article and newly supplied complete diet supplement; standalone juvenile-hake production/predation inconsistency and unresolved source fields | Not selected; FAIL / FAIL / FAIL |',
      '',
      'Büring et al. (2024), DOI [10.1017/S0025315423000887](https://doi.org/10.1017/S0025315423000887), supplies a Falkland shelf model for 2020, 36 groups, two fleets and approximately 200,000 km² to 300 m depth. PAT-2023 is the retained paper-folder identifier, not the publication year. The native database and printed tables differ in diet/import values beyond rounding and in detritus EE. Initial Table S3 is not another complete balanced model. No variants were averaged or pooled.',
      '',
      '## Computational input and source fidelity',
      '',
      f'- Canonical native extraction: [model.json](model.json), SHA-256 `{audit["canonical_source_sha256"]}`. Missing native values remain missing.',
      f'- Selected computational input: [derived JSON]({o["model_path"].split(MID+"/")[1]}), SHA-256 `{audit["computational_input_sha256"]}`. It is byte-identical to the input that produced the audited three WARN diagnoses.',
      '- [Completion provenance](selection_20260928/selection_provenance.json) lists every derived cell; the native Access file and all eleven inventoried source files are unchanged.',
      '',
      'The native database stores inputs and leaves 13 living/producer biomasses and some EEs unresolved. The computational input solves the coupled production equations',
      '',
      '`B_i × PB_i × EE_i = catch_i + BA_i + emigration_i − immigration_i + Σ_j(B_j × QB_j × DC_ji)`.',
      '',
      'Known native biomass, diet, catches, rates, EE, habitat area and migration are retained. Unknown biomasses are solved simultaneously, then missing EE is calculated from the same balances. Kingclip immigration is included. The matrix residual is 1.13 × 10⁻¹⁴; all solved biomasses are positive and recomputed EE lies within [0,1]. The solution reproduces the printed Table 4 outputs to their rounding, including benthic crustacean B = 1.371551 and phytoplankton B = 3.255569 t km⁻². These are Ecopath-derived quantities, not arbitrary biomass defaults.',
      '',
      'The region-local adapter uses the supported regional SPPR stage and shared exporter with only the three selected methods, each bounded at 180 seconds. It verifies the input hash, accommodates the legacy filename parser and restores the audited loader settings: underdetermined=False, normalize_DC=False, DC_tol=0.001, zero_catch=True, zero_biomass_accum=True, default_gs=True. Native living inputs explicitly supply the relevant zeros and GS. Both detritus pools remain separate (collapse=never, opening=none). All three calculations completed; none timed out. The shared default loader is unsuitable for rerunning this exact selection because it changes those settings. Use the region-local adapter documented below.',
      '',
      'The selected workbook reproduces all 777 numeric cells of the previously audited completed group table. This verifies that the production coefficients use the same computational state as the WARN diagnostics. The earlier uncompleted default-loader FAIL run is retained under default_loader_diagnostics/ and is not selected.',
      '',
      '## Remaining warnings and limitations',
      '',
      'The full direct diagnostic returns remain in [diagnostic_report.md](diagnostic_report.md) and [diagnostics_raw.json](diagnostics_raw.json). That diagnostic report contains only GE, TE and With Egestion returns.',
      '',
      '- Baleen Whales has EE = 0. TE additionally has near-zero TE in Toothed Whales and Dolphins, Seals and Sea Lion, and Seabirds. TE’s relative PP-budget gap is approximately 0.0001256 (0.01256%); GE and With Egestion are approximately 1.17 × 10⁻¹⁶. The TE warning was retained.',
      '- The native fleet discard fate sends both fleets to Detritus, while five consumers eat the separate Discards pool. The loader does not retain explicit fleet-specific discard supply. It forces detritus identity routing/EE = 1 and derives detritus accumulation, including negative accumulation for Discards. Native BA = 0 is preserved in source and computational JSON; loader completion is separately visible. The unknown native Detritus biomass is also assigned the loader’s nonliving placeholder of 1. This is not a source biomass estimate or a new living-group completion. These facts limit ecological interpretation despite numerical balance.',
      '- The model represents the Falkland shelf, not the entire Patagonian Shelf LME. Adults of toothfish and certain deep-water skates and grenadiers are explicitly excluded. No model-area percentage or catch-area fraction was invented. Historical regional calculations transfer 2020 coefficients to 1950–2019 catches; they do not reconstruct annual historical food webs.',
      '- WARN acceptance follows the existing regional configuration policy and the user’s selection. It does not establish that all source inconsistencies have disappeared. Annual status “ok” means the calculation was admitted; the diagnostic status remains WARN.',
      '',
      '## Catch matching and coverage',
      '',
      'All 250 regional taxa were reviewed. Twenty-nine have supported assignments and 221 remain unresolved. Explicit Table 2 membership takes precedence over broad group labels. Nine bivalve records are contained by the paper’s explicit Bivalves/Scallops definition; their primary WoRMS records are retained in [mapping taxonomy evidence](selection_20260928/mapping_taxonomy_evidence.json). For example, [Zygochlamys patagonica](https://www.marinespecies.org/aphia.php?p=taxdetails&id=236717) is the Patagonian scallop. Membership support is distinct from geographic representativeness.',
      '',
      'D. gahi is split between ASC (0.49237747138886107) and SSC (0.507622528611139) using native 2020 cohort landings. This constant historical mixture is an approximation. The genus-level Merluccius record uses the region’s identified hake catches over 1950–2019: M. hubbsi 0.994820308056964 and M. australis 0.005179691943036082. This is inferred composition, not a published annual split. [Split weights](selection_20260928/split_weights.csv), [all mapping decisions](selection_20260928/mapping_review.csv) and [exact numeric mapping](selection_20260928/mapping_resolved.csv) are retained.',
      '',
      '| Catch basis | Period | Covered tonnes | Total tonnes | Coverage |',
      '|---|---|---:|---:|---:|',
    ]
    for r in coverage:lines.append(f'| {r["catch_basis"]} | {r["years"]} | {float(r["mapped_tonnes"]):,.2f} | {float(r["total_tonnes"]):,.2f} | {float(r["mapped_percent"]):.2f}% |')
    lines += ['', 'The largest unresolved cumulative catches are shown below. Whole-LME aggregates are not assigned using only their modeled members when that would hide unsupported components.', '', '| Unresolved taxon | 1950–2019 catch tonnes |', '|---|---:|']
    for r in [r for r in mapping if r['group']=='Unresolved'][:10]:lines.append(f'| {r["taxon"]} | {float(r["catch_tonnes_1950_2019"]):,.0f} |')
    lines += ['', 'Pleoticus shrimp is not Munida lobster krill; croakers and anchovies are not listed within the source fish groups. Unsplit adult/juvenile toothfish and deep-water skates are not silently assigned to the shelf compartments. Missing SPPR remains blank. The standard zero/simple treatments for unidentified records are separate labeled scenarios; they are not source mappings.', '', '## Regional results and NPP', '', 'Annual PPR is saved for 1950–2019, with all / inner / PP source scopes and landings / catch / discards bases. The three configurations have nonnegative coefficients for every source group, including unfished groups. Unresolved catch contributes no estimate to the covered-catch PPR; these are partial estimates, not a claim that the omitted catches require zero production.', '', 'Illustrative 2019 values below use all-source scope, landings, and the method treatment for unidentified catch. Covered landings are 964,673.12 of 1,497,627.62 tonnes.', '', '| Configuration | PPR, wet-weight-equivalent tonnes | PPR / inherited NPP ensemble | Diagnosis |', '|---|---:|---:|---|']
    for r in annual:lines.append(f'| {methods[r["method"]]} | {r[2019]:,.2f} | {ratios[r["method"]]:.5f}% | WARN |')
    lines += ['', 'PPR/NPP divides wet-weight-equivalent PPR by nine exactly once. Existing NPP values, algorithm identities and missing years were preserved: Antoine–Morel and ensemble support 1998–2019; the other four algorithms support 2003–2019. Earlier ratios remain blank. The inherited NPP series includes documented gap filling and model-ratio methods; this task did not perform a new satellite extraction. Twenty-two historic provenance links were resolved to retained research-archive files using the relocation manifest and verified hashes; [link audit](selection_20260928/npp_provenance_links.json). No frozen NPP evidence was rewritten.', '', '## Verification and reproduction', '', f'[Validation evidence](selection_20260928/selected_results_validation.json) records {audit["taxon_coefficient_checks"]:,} coefficient checks, {audit["annual_cell_checks"]:,} annual-value checks and {audit["ratio_cell_checks"]:,} ratio checks. Original catch, classic-taxon coefficients and numerical NPP inputs are unchanged. The supported region validator passes. Executed scientific code snapshots and hashes are retained under selection_20260928/executed_code/.', '', 'To reproduce from the project root, use:', '', '```powershell', f'python regions/LME_014/models/{MID}/run_selected_sppr.py', f'python regions/LME_014/models/{MID}/prepare_catch_mapping.py', 'python tools/run_region.py --region regions/LME_014/LME_014.xlsx --stage calculate', f'python regions/LME_014/models/{MID}/validate_selected_results.py', 'python tools/run_region.py --region regions/LME_014/LME_014.xlsx --stage validate', '```', '', 'Central metadata proposals are [here](selection_20260928/central_registration_proposal.json). Shared code, Project.xlsx and the map were not modified by this regional task.']
    (MODEL/'selection_report.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    basepath='regions/LME_014/models/'
    proposals=[]
    for suffix,selected,availability in [('native',True,'Extracted native model; audited derived living B/EE completion; GE/TE/With Egestion WARN'),('published_tables',False,'Extracted source tables; loader blocked by undocumented two-pool detritus routing')]:
        mid='PAT2024_FalklandShelf_2020_'+suffix
        proposals.append({'unit_id':'LME_014','model_id':mid,'model_path':('regions/LME_014/'+o['model_path']) if selected else basepath+mid+'/model.json','source_filename':'sup002.eweaccdb' if selected else 'Article Table 4 and supplements S2/S3/S4','selected':selected,'selection_rationale':o['selection_rationale'] if selected else None,'paper_ids':'PAT-2023__LME_014','model_year':2020,'variant':'author-supplied native Ecopath model; declared computational completion' if selected else 'published final parameter table and supplements; unresolved detritus alignment','model_area_km2':200000,'availability':availability,'publication_year':2024,'model_years':'2020','target_coverage_ratio':None,'coverage_class':'subregional','doi':'10.1017/S0025315423000887','coverage_note':'Falkland shelf to 300m; area 200000 km². LME-area percentage not established. Canonical source extraction '+basepath+mid+'/model.json; '+('selected regional coverage 29/250 taxa, 64.41% 2019 landings; diagnostics WARN.' if selected else 'Not selected.'),'atlas_region_rank':19})
    omid='OcampoReinaldo2016_SanMatiasGulf_1970'
    proposals.append({'unit_id':'LME_014','model_id':omid,'model_path':basepath+omid+'/model.json','source_filename':'Assessing-the-effects-of-demersal-fishing--e228101d.pdf and 1-s2.0-S0304380015005104-mmc1.docx','selected':False,'selection_rationale':None,'paper_ids':'LME014-OcampoReinaldo-2016__LME_014','model_year':1970,'variant':'published 1970 Ecopath baseline; diet supplement transcribed','model_area_km2':10000,'availability':'Source extraction complete; diagnostic GE/TE/With Egestion FAIL; not admitted','publication_year':2016,'model_years':'1970 baseline; Ecosim 1970–2009 not additional balanced models','target_coverage_ratio':None,'coverage_class':'subregional','doi':'10.1016/j.ecolmodel.2015.10.025','coverage_note':'San Matias Gulf model; no verified LME coverage percentage','atlas_region_rank':19})
    updates=[{'article_id':'PAT-2023__LME_014','fields':{'title':'Unveiling the wasp-waist structure of the Falkland shelf ecosystem: the role of Doryteuthis gahi as a keystone species and its trophic influences','publication_year':2024,'model_years':'2020','functional_groups':36,'supplement_status':'User-provided CSV, DOCX and native EwE Access database inventoried and hash-verified','model_file_status':'Native EwE sup002.eweaccdb extracted read-only; source preserved','full_model_loadable':'Native inputs loaded after audited coupled living/producer B/EE completion; GE/TE/With Egestion WARN. Stock uncompleted loader FAIL retained separately.','extraction_readiness':'Complete source extraction; exact native variant selected; regional calculation validated with partial catch coverage','loadability_evidence':'regions/LME_014/models/PAT2024_FalklandShelf_2020_native/selection_report.md','documentation_evidence':'Native database plus article Tables 2 and 4, complete S2 diet and S3/S4 supplement; all cells and disagreements retained','coverage_note':'Model covers Falkland shelf to 300m, approximately 200000 km². Prior 0.12 ratio was approximate footprint metadata, not verified LME coverage; do not treat as source-supported catch coverage.'}}, {'article_id':'LME014-OcampoReinaldo-2016__LME_014','fields':{'model_years':'1970 baseline; Ecosim 1970–2009','functional_groups':26,'supplement_status':'New user-provided mmc1.docx complete diet matrix transcribed and hash-verified','full_model_loadable':'Standalone reconstruction loads with declared missing-input conventions; GE/TE/With Egestion FAIL, including juvenile-hake production/predation inconsistency','extraction_readiness':'Complete supported source extraction; not selected; no numerical admission','loadability_evidence':'regions/LME_014/models/OcampoReinaldo2016_SanMatiasGulf_1970/diagnostic_report.md','documentation_evidence':'Article Tables 1/2 and supplied complete supplementary diet matrix; cell evidence and source gaps retained'}}]
    proposal={'status':'PROPOSAL ONLY: parent owns serialized Project.xlsx edits','region_workbook':'regions/LME_014/LME_014.xlsx','region_workbook_sha256':sha(REGION/'LME_014.xlsx'),'selected_model_id':MID,'models_to_upsert':proposals,'paper_field_updates':updates,'preserve_existing_fields':'Preserve fields not explicitly listed, retrieval-attempt history and prior evidence. Do not invent quality-score recalculations. Existing numeric quality ratings are historical, not updated by these facts.','subsequent_action':'After metadata registration, run supported update_project for LME_014 and verify central selection, diagnostics and partial-catch coverage. No rerun through the default loader.'}
    (E/'central_registration_proposal.json').write_text(json.dumps(proposal,indent=2,ensure_ascii=False),encoding='utf-8')
    print('Report and central proposal saved:',MODEL/'selection_report.md')

if __name__=='__main__':main()
