from pathlib import Path
import json,hashlib
ROOT=next(p for p in Path(__file__).resolve().parents if (p/'Project.xlsx').is_file())
QA=Path(__file__).resolve().parents[1]/'qa';records=[]
def edit(relative, pairs):
    p=ROOT/relative;b=p.read_bytes();t=p.read_text(encoding='utf-8')
    for old,new in pairs:
        if old not in t:raise ValueError(f'Missing inspected text: {relative} {old[:60]}')
        t=t.replace(old,new)
    p.write_text(t,encoding='utf-8');records.append(dict(path=relative,before_sha256=hashlib.sha256(b).hexdigest(),after_sha256=hashlib.sha256(p.read_bytes()).hexdigest()))
edit('explainers/PPREstimation/USER_GUIDE.md',[
('# User Guide: `ModelData` and `PPRCalculator`','# User Guide: `ModelData` and `PPRCalculator`\n\nThis is scientific engine/API background. Read the [structure contract](../structure.md), [model loading note](../model_loading.md), [current parameters](../sppr_parameters.md) and [direct-diagnostics contract](../../tools/skills/paper-to-ppr/references/direct-diagnostics.md) before executing project work. The ordinary direct route remains GE/TE/With Egestion; global/Monte Carlo examples below require separately authorized scope. Engine toy/legacy data examples do not define regional discovery or selection. Source behavior and actual model-specific provenance govern every result.'),
('**`ModelData(model_input: int | str)`**','**`ModelData(model_input: int | str, *, model_name=None, model_year=None)`**'),
('| `model_input` | `str` | **New API**: a path to a per-model JSON file, e.g. `"real_models/EwE_jsons/227_227_Iceland_(1950).json"`. The filename stem must follow `{first_number}_{model_number}_{name}_({year})` — **two** leading numeric tokens (the first is a source/grouping id and is discarded; the second is the model id). For single-model files the two numbers are the same (`227_227_...`); for multi-model source files they differ (`13_10013_Humboldt_Current_(1980)`). |','| `model_input` | `str` | Path to a supported Ecopath JSON, including the canonical paper-owned or EcoBase `model.json`. Legacy two-number filenames retain their historical identity; canonical files resolve identity from their model directory and explicit metadata. Unknown number/year remain unknown rather than inferred provenance. |\n| `model_name`, `model_year` | optional keyword | Explicit caller-provided identity labels; record their actual source and do not use them to invent a publication period. |'),
('> **Where the files live:** real EwE models are JSON files under `real_models/EwE_jsons/`; small\n> hand-built toy models (used in the test notebooks) are under `real_models/ToyModels/`.','> **Project ownership:** current regional models live under the grouped region/paper/model or regional EcoBase layout in structure.md. Shared engine source models under real_models/ are reference inputs; toy-model examples are engine tests, not regional candidates.'),
('given model number or the filename can\'t be parsed.','given integer model number, or the JSON lacks the supported nonempty group list. A generic canonical filename is supported; missing identity metadata stays missing.'),
('default_gs=True, weight_flow=1.0, weight_guess=1.0)`**','default_gs=True, weight_flow=1.0, weight_guess=1.0, normalize_DC=False, DC_tol=0.001, balance_BA_after_DC_normalization=True)`**'),
('| `weight_guess` | `float` | `1.0` | LIM penalty weight favoring *staying near biologically sensible guesses*. |','| `weight_guess` | `float` | `1.0` | LIM penalty weight favoring *staying near biologically sensible guesses*. |\n| `normalize_DC` | `bool` | `False` | Normalize an ephemeral runtime diet copy when requested; canonical/source cells remain unchanged. |\n| `DC_tol` | `float` | `0.001` | Runtime diet-row tolerance; source deficits and precision still need evidence. |\n| `balance_BA_after_DC_normalization` | `bool` | `True` | Offset normalization-induced predation in eligible runtime BA only when the raw production identity is already consistent and all counterfactual terms are finite; preserve the transformation ledger and excluded reasons. |'),
('Known living-group production, mortality and\naccumulation are not adjusted to absorb changed predation: remaining balance residuals must be\nchecked with `is_model_balanced()` or diagnostics.', 'Known production and mortality remain unchanged. The separately controlled normalization BA offset applies only to eligible originally consistent groups; it is not a general balancer. Remaining residuals must be checked with is_model_balanced() or diagnostics.'),
('| `TE_option` | `str` | `\'GE\'` | `\'GE\'`, `\'TE\'`, `\'With Egestion\'`, `\'global\'` (see §5.1). |','| `TE_option` | `str` | `\'GE\'` | GE, TE or With Egestion. Although get_TE supports global, SPPR_new\'s executable detritus branch currently rejects global; use a supported global method only within authorized scope. |'),
('**never raises**. The Monte-Carlo samplers rely on this so they can detect and reject unstable draws.', 'the recycling block preserves failure/negative output rather than certifying a healthy result. Other solver errors or unavailable matrices remain possible. The Monte-Carlo samplers screen their actual returns.'),
('When you want robust, always-finite results.', 'Only for an explicitly reviewed pooling approximation; finite or valid results are not guaranteed.'),
('Quick, very robust approximation.', 'Explicit pooling approximation; preserve its distinct scientific assumptions and diagnostics.'),
('`SPPR_Methods.md`', '[sppr_methods.md](../sppr_methods.md)'),
('`ModelData.validate_DC` already raises at load time at `1e-3`, so the default `dc_row_tol=1e-6` is what makes this informative.', 'Diet admission depends on actual normalize_DC/DC_tol. Without normalization, excessive deviation raises; normalization records changed runtime rows. The stricter diagnostic dc_row_tol remains a separate check.'),
])
edit('explainers/sppr_methods.md',[
('# SPPR Calculation Methods in `PPRCalculator`','# SPPR Calculation Methods in `PPRCalculator`\n\nThis reference explains the retained scientific engine, not permission to execute every method. The [structure](structure.md), [loading](model_loading.md), [parameter reference](sppr_parameters.md) and [direct-diagnostics contract](../tools/skills/paper-to-ppr/references/direct-diagnostics.md) govern current project ownership, actual settings and ordinary GE/TE/With Egestion scope. Global and Monte Carlo examples require their own authorization. Historical or unsupported API descriptions below do not establish readiness, validation or provenance.'),
("- **`TE_option`** — `'GE'` (default), `'TE'`, `'With Egestion'`, `'global'` (see §2). Beyond", "- **`TE_option`** — GE (default), TE or With Egestion. get_TE supports global, but SPPR_new's executable detritus branch currently rejects it; use supported global methods only within authorized scope. Beyond"),
("    ill-conditioned), in which case fall back to pooling. The safe, self-correcting choice.","    ill-conditioned), in which case fall back to pooling. This changes the detritus approximation and needs explicit configuration evidence; it guarantees neither scientific validity nor finite results."),
('  `ModelData.validate_DC` already **raises at load time** at `tol=1e-3`, so anything that loaded\n  passes at that tolerance; the default `dc_row_tol=1e-6` is what makes this field informative.', '  Admission follows the actual normalize_DC/DC_tol settings: unnormalized excessive deviation raises; requested normalization records changed runtime rows. Diagnostic dc_row_tol is a separate stricter check, not proof that source fractions were faithful.'),
])
(QA/'engine_guide_changes.json').write_text(json.dumps({'records':records,'evidence':['tools/scientific_code/PPREstimation/ModelData.py:_resolve_json_identity','tools/scientific_code/PPREstimation/PPRCalculator.py:from_modeldata,_reconcile_normalized_diet_biomass_accum,SPPR_new','tools/scientific_code/PPREstimation/create_PPRS_excel.py:load_model'],'scientific_engine_edited':False},indent=2),encoding='utf-8')
print('Corrected 2 engine guides against actual current signatures and branches.')
