from pathlib import Path
from decimal import Decimal
import json,csv
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'extracted_tables'
chapter=json.loads((OUT/'literal_source_extraction.json').read_text(encoding='utf-8'))
thesis=json.loads((OUT/'thesis/literal_source_extraction.json').read_text(encoding='utf-8'))
def write(path,obj):path.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
checks=list(csv.DictReader((OUT/'table_I_internal_arithmetic.csv').open(encoding='utf-8-sig')))
write(OUT/'source_conflicts.json',{'chapter':{'variant':'38-group preliminary chapter','biomass_basis_conflicts':[r for r in checks if r['check']=='B_B minus habitat*B_A' and r['material_discrepancy']=='True'],'GE_conflicts':[r for r in checks if r['check']=='GE minus PB/QB' and r['material_discrepancy']=='True'],'year_conflict':'Volumecover says October2004; colophon2005. Retained chapter2004 identity; explicit modelyear unknown.','no_diet':'ChapterPDF4 printed408 says quantitative diet unavailable; database available onrequest.'},'preferred_thesis':{'group20':{'basic':'Epinephelus aeneus*','annex':'Hemichromis fasciatus','membership_evidence':'Table3.3 PDF83 printed59 places these in separately named compartments; Epinephelus*+Lutjanusgoreensis+ within Prédateurs de fond, Hemichromis separate row. No correction established.','resolution':'UNRESOLVED; canonical diet prey20 and consumer20 unknown; no loading'},'group27':{'basic':'Liza grandisquamis*','annex':'Liza falcipinnis','membership_evidence':'Table3.3 PDF83 printed59 lists both in Mugilidés pool with Saloum grandisquamis* and falcipinnis+','resolution':'Pooledguild reconciliation supported; representative name conflict preserved; no numerical cell changed'},'source_spelling_conflicts':['Sphyraena guanchancho* (Table6.5) vs guachancho (Annex)','Scomberomorus tritor (Table6.5) vs Scromberomorus tritor (Annex)','Pseudotolithus (Table6.5) vs Pseudotholithus (Annex)','Cynoglossus senegalensis (Table6.5) vs sengalensis (Annex)'],'source_version_conflicts':['Table3.3 Pseudotolithus senegalensis is starred Saloum representative; Table6.5 uses P.brachygnathus*; same explicit OtherScianidae pool retains both species','Table3.3 places Chloroscombrus chrysurus and Psettodes belcheri in a Psettodidae-labelled block, inconsistent with sole-species caption inTable6.5; source block retained, no silent taxonomic correction','Chapter38groups is distinct parameter variant:24fish/10invertebrate/3producer/detritus vs thesis29fish/5invertebrate/2producer/detritus']}})
mask=json.loads((OUT/'thesis/canonical_diet_missingness.json').read_text(encoding='utf-8'))
known_y=[g for g in thesis['groups'] if g['Y'] is not None]
write(OUT/'thesis/source_admission_summary.json',{'status':'BLOCKED','preferred_source':'Villanueva2004 thesis','groups':37,'consumers':34,'fish_groups':29,'invertebrate_groups':5,'producer_groups':2,'detritus_groups':1,'model_period':'1991-1992','source_cells':{'basic':259,'diet':1258,'diet_nonblank':sum(c['value'] is not None for c in thesis['diet_cells']),'diet_blank':sum(c['value'] is None for c in thesis['diet_cells'])},'literal_diet_sum_range':['0.999','1.000'],'literal_diet_sums_below_one':[2,5,10],'diet_orientation':'prey rows by numbered consumer columns, explicit Proie/Prédateur header','caption_percent_note':'Cells are fractions; source totals 0.999–1.000 supportfractioninterpretation. No divisionby100/no normalization performed.','canonical_identity_withheld_cells':len(mask),'canonical_identity_withheld_nonblank_source_cells':sum(c['source_value'] is not None for c in mask),'known_published_catch_groups':len(known_y),'published_catch_known_subtotal_t_km2_year':str(sum(Decimal(g['Y']) for g in known_y)),'known_published_catch_zero_groups':[g['group_id'] for g in known_y if Decimal(g['Y'])==0],'unknown_catch_groups':[g['group_id'] for g in thesis['groups'] if g['Y'] is None],'missing_fields':['GS all37','BA all37','routing/export all37','discards all37','migration all37','habitatfractions all37','diet import all34','canonical diet group20identity unresolved'],'loaded_state':None,'source_health_diagnostics':'NOT_RUN','scientific_reason':'Cannot map source diets of separately identified Hemichromis group20 onto Epinephelus parameters without author-supported correction. Unknown fields kept unknown.','roundtrip_fidelity':'PASS;8standard4companions23172cells maxdifference0; fidelity doesnotadmit scientificcalculation','converter_indicative_massbalance':'1error109indeterminate0warnings2notes; incomplete canonical20diet intentionally withheld. Not an authored-model health verdict.','structural_validator':'4errors40warnings; reducedknown diets due withheld20row; no repair','native_model_comparison':'EcoBase612 metadata identifies thesis-related37group model but official input unavailable; no nativehash/equivalence assertion','no_adoption':True})
write(OUT/'thesis/converter_transformation_ledger.json',{'source_to_partial_import':['Source decimal comma converted to dot with precision retained','Parentheses stripped from numeric cells but model_estimated role retained','Source footnotes retained in companions','Canonical group names strip the source asterisk; pooling flag retained','Published Y labelled Reported total catch fleet in Landings.csv without asserting discard completeness','Group 20 prey row and entire consumer 20 column set unknown, exact raw source retained','Group 27 numbered mapping reconciled to documented Mugilides pool, no numeric change','Printed blank diet cells remain blank under structural no-prey convention; raw missing mask retained','Import unknown explicitly null; no forced zero','No GS/BA/routing/migration/discards default written into source/import model'],'converter_to_database':['Intermediate conversion uses habitat area one, but final source-fidelity restoration preserves unknown habitat_area=-9999 for all37; known whole-area B retained unchanged','Source blank diet cells classified unknown by converter; distinguish structural blanks from explicitly unmapped group20 through literal companions','Unknown numeric fields represented -9999 in generated database','Converter indicative mass balance may use GS0.2 only within advisory checks; not admitted/source evidence','Detritus PB1.700 retained as unsupported source field; no synthetic biological production asserted'],'runtime_loading':None,'runtime_normalization':False,'author_corrections_applied':[]})
text= (ROOT/'evidence/identity/Villanueva2004_thesis_29305.txt').read_text(encoding='utf-8')
pages=[]
for p in [66,67,68,69,70,71,72,73,76,77,78,79,80,81,82,83,87,132,136,137,138,142,143,235,236]:
 start=text.find(f'=== PDF PAGE {p} ===');end=text.find(f'=== PDF PAGE {p+1} ===',start)
 pages.append(text[start:end])
(ROOT/'evidence/source/thesis/method_membership_evidence.txt').write_text('\n'.join(pages),encoding='utf-8')
