from pathlib import Path
import json,hashlib,csv,subprocess,sys,struct
R=Path(__file__).resolve().parent;E=R/'evidence';N=R/'resolved_native';C=R/'computational'
def jw(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2,allow_nan=False),encoding='utf-8')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
orig=json.loads((E/'original_sources.json').read_text(encoding='utf-8'))
for a in orig:a['relative_path']='../../../../papers/HUM-2018/'+a['filename']
jw(E/'original_sources.json',orig)
snap=json.loads((E/'supplement_cells.json').read_text(encoding='utf-8'));snap['source']='../../../../papers/HUM-2018/Supplementary material revised and final.xls';jw(E/'supplement_cells.json',snap)
ledger=json.loads((N/'SOURCE_CELLS.json').read_text(encoding='utf-8'))
for a in ledger:
    if 'source_file' in a:a['source_file']='../../../../papers/HUM-2018/Supplementary material revised and final.xls'
jw(N/'SOURCE_CELLS.json',ledger)
identity=json.loads((R/'SOURCE_IDENTITY.json').read_text(encoding='utf-8'))
for a in identity['source_bundle_hashes']:a['relative_path']='../../../papers/HUM-2018/'+a['filename']
jw(R/'SOURCE_IDENTITY.json',identity)
data=json.loads((N/'extraction.json').read_text(encoding='utf-8'))
budget=json.loads((N/'SOURCE_BUDGET_ARITHMETIC.json').read_text(encoding='utf-8'))['groups']
sums=json.loads((N/'DIET_SOURCE_SUMS.json').read_text(encoding='utf-8'))['consumers']
conflicts=[
{'id':'sardine_landings_version','group_id':9,'field':'landings_commercial','supplement_value':5.6513425,'paper_prose_value':1.4,'source_locations':['XLS Table A J14','PDFp3/printedp30 Methods','PDFp4/printedp31 Table1 Foragefish landings28.13'],'adopted_native_value':5.6513425,'status':'unresolved source-version conflict; native supplement preserved','interpretation':'Paper says sardine landings were reduced from5.65 to1.4 to balance. Native5.6513425+Anchovy22.475495=28.1268375, consistent with printed aggregate28.13. Choosing prose1.4 would be a distinct source-conflict variant; no such variant was run.'},
{'id':'large_jellyfish_diet_excess','group_id':7,'field':'diet_total','source_value':sums[6]['sum'],'source_locations':['XLS Table B H4,H7,H8,H9,H39,H43'],'status':'source total1.045 preserved','interpretation':'4.5% excess is material. Exact five nonzero stored cells plus zero import; final source and import artifacts never normalized. Runtime normalized copy handled separately by diagnostics.'},
{'id':'small_gelatinous_production','group_id':6,'field':'production_vs_predation','source_production':budget[5]['source_production_t_km2_y'],'source_raw_predation':budget[5]['raw_source_predation_t_km2_y'],'source_EE':budget[5]['source_EE'],'source_implied_EE':budget[5]['EE_implied_without_BA_or_migration'],'source_locations':['XLS Table A C11,D11,E11,H11','XLS Table B H9,G9','PDFp4/printedp31 Table1 Smalljellyfish B.01 PB.58 QB2.92','PDFp8/printedp35 caveats'],'status':'severe source arithmetic disagreement; no supported repair','interpretation':'Large jellyfish alone demands23.3497540704 of gelatinous6 versus source gelatinous production.00529590617 t/km²/year. Article caveat says small-jelly biomass surveys need improvement; it supplies no corrected numerical biomass.'},
{'id':'egg_pool_classification','group_id':36,'field':'source_type','source_locations':['PDFp3/printedp30 36living groups including eggs','XLS Table A row41 blankPB/QB','XLS Table C C13=.25 and row39 fate','PDFp3/printedp30 egg production assumed25%'],'status':'explicit operational pool representation','interpretation':'Source describes eggs as living, but parameter/routing tables encode a nonfeeding pool.25 is a source fraction and is not justified as an annual PB. Operational pp2 is a labeled translation, not a new PB or a true primary-source classification.'},
{'id':'aggregate_detritus_codes','fields':['group_code'],'source_locations':['XLS Table E C43:C45','XLS Table H-agg. production matrix codes24–26','PDFp4/printedp31 Table1 codes24–26'],'status':'name-based crosswalk retained, numeric-code conflict unresolved','interpretation':'TableE/ECOTRAN order:24Pelagicdetritus,25Eggs,26Offal. PrintedTable1:24Eggs,25Offal,26Pelagicdetritus. Names must govern source joins; no silent positional exchange.'},
{'id':'aggregate_vs_resolved_egg_EE','group_id':36,'field':'ee','resolved_native_value':data['groups'][35]['ee'],'aggregate_printed_value':0.87,'source_locations':['XLS Table A H41','PDFp4/printedp31 Table1 Fish eggs EE.87'],'status':'variant difference retained','interpretation':'Resolved EE.8843322396 would display.88, not.87. Printed aggregate is not an exact rounded copy of the detailed source.'},
{'id':'different_aggregate_fates','field':'detritus_fate','source_locations':['XLS Table C E4=1/F4=0 (Diatoms)','XLS Table G-aggregate detritus fate E5=0/F5=1 (Largephytoplankton senescence)'],'status':'different model semantics','interpretation':'Resolved Ecopath TableC pools generic detritus fate. Aggregated ECOTRAN TableG separates feces, senescence and NH4 excretion; Diatom senescence destination differs. It cannot be substituted as an equivalent source Ecopath fate matrix without a distinct translation.'},
{'id':'rounded_display_zeros','fields':['biomass','ee','pq'],'source_locations':['XLS Table A C39:C40','XLS Table A H12','XLS Table A F36:F38','PDFp4/printedp31 Table1'],'status':'native stored nonzero preserved','interpretation':'Green/leatherbackB.000343/.000162 and largejellyEE.0000611780 display0.00; seabird/mammalPQ also may display0.00. These are not numeric zero.'},
{'id':'biomass_unit_header','field':'biomass_units','source_locations':['XLS Table A C5','PDFp3 Eq1 and definition','PDFp4/printedp31 Table1'],'status':'printed header retained; dimensional interpretation explicit','interpretation':'Table header labels B with t km−2 y−1, although Eq1 defines B as stock biomass. Canonical B is t wetweight/km², with source header recorded; no numerical time conversion applied.'},
{'id':'archive_metadata_stale','fields':['title','model_period','source_availability'],'source_locations':['../../../papers/HUM-2018/README.md','../../../papers/HUM-2018/metadata.json','PDFp1 title','PDFp3 baseline1995–1998'],'status':'historical files untouched; corrected candidate identity companion','interpretation':'Old README claims no verified source; actual PDF/XLS/DOCX exist and hashes are retained. Cached1995–2004 is not the focal static averaging period. Full published title and short historical alias retained separately.'}
]
jw(R/'SOURCE_CONFLICTS.json',conflicts)
tax=[]
for g in json.loads((N/'GROUP_IDENTITY.json').read_text(encoding='utf-8')):
    tax.append({'seq':g['seq'],'group_name':g['group_name'],'source_description':g['taxon_descr'],'source_evidence':g['taxonomy_evidence'],'scope':g['membership_scope'],'source_or_inherited':'inherited_model' if 'Tam2008' in g['taxonomy_evidence'] else 'focal_source','accepted_synonyms':'not verified in this source extraction; source historical spellings retained','authority_id':None,'model_period':'1995–1998','area_basis':'NHCS 4–16°S,111km offshore','allocation_shares':'not inferred from example membership','caveat':'Egg pool25% refers to TableC fate fraction, not a measured total-production allocation' if g['seq']==36 else None})
jw(N/'TAXONOMY_EVIDENCE.json',tax)
with (N/'TAXONOMY_EVIDENCE.csv').open('w',encoding='utf-8',newline='') as f:
    w=csv.DictWriter(f,fieldnames=list(tax[0]),lineterminator='\r\n');w.writeheader();w.writerows(tax)
# Read vector EMF text from original DOCX image, without rendering/editing its bytes.
b=(E/'image5.emf').read_bytes();o=0;emf=[]
while o+8<=len(b):
    t,size=struct.unpack_from('<II',b,o)
    if size<8:break
    if t==84:
        n,off=struct.unpack_from('<II',b,o+44)
        emf.append({'record_offset':o,'text':b[o+off:o+off+n*2].decode('utf-16-le',errors='replace')})
    o+=size
jw(E/'docx_emf_text.json',emf)
search={'date':'2026-10-03','queries':['Tam 2008 Trophic modeling northern Humboldt Current ecosystem PartI Comparing trophic structure ENSO model Table functional groups pdf','Chiaverano2018 corrigendum jellyfish','10.1016/j.pocean.2018.04.009 supplement correction'],'primary_material_read':[{'url':'https://epic.awi.de/id/eprint/22464/1/Tam2008a.pdf','artifact':'evidence/Tam2008a.pdf','sha256':sha(E/'Tam2008a.pdf'),'read':'all text; Methodspp353–354 membership and Table1 source purpose; p353 source render','outcome':'verified explicit predecessor; inherited taxonomy retained, no borrowed numerical source values'},{'url':'https://www.sciencedirect.com/science/article/abs/pii/S0079661117303312','read':'publisher indexed title/DOI metadata','outcome':'full title match; no focal numeric corrigendum found'},{'url':'https://repositorio.imarpe.gob.pe/items/1059a1f2-ffe3-4abf-bea8-d0fe11f6d4a8/full','read':'institutional indexed bibliographic record','outcome':'focal article DOI/title match'}],'rejected_search_result':{'title':'Corrigendum: Spatial patterns of large jellyfish Chrysaora plocamia blooms in the Northern Humboldt Upwelling System','doi':'10.1093/icesjms/fsy019','reason':'Different Quiñones study; not a correction of focal Ecopath model.'},'missing_after_bounded_search':['author-native EwE database/export with consistent balanced input not recovered','numeric source corrections to jellyfish diet/production not found','exact composition and size thresholds for residual pools not documented','Ecopath BA,habitat fractions,migration,external detritus imports and focal source TL values not tabulated'],'stop_reason':'All three supplied original sources numerically read; verified explicitly cited predecessor read; correction queries yielded no focal corrigendum. No repeated access attempts or source substitutions.'}
jw(R/'RECOVERY_SEARCH.json',search)
script=Path.cwd()/'tools/skills/original_skill_resources/claude/ecopath-extraction/scripts/validate.py'
v=subprocess.run([sys.executable,'-X','utf8',str(script),str(N)],capture_output=True,text=True,encoding='utf-8')
(N/'VALIDATION.txt').write_text(v.stdout+v.stderr+f'\nexit_code={v.returncode}\n',encoding='utf-8')
profile='''# Northern Humboldt Current, 1995–1998 static baseline

Source axis: taxonomy, plankton size classes, fish feeding guilds, and hake size stages. No spatial prefixes.

Domain:4–16°S, to111km offshore, source area165,000km² wet-weight densities. Regionwide catch extrapolation is a separate applicability assumption.

Exact source nodes:1–41. Operational stock representation:1–39, with33feeding consumers3–35 and producers1–2. Source prose lists36living groups including Anchovyeggs36 and3detrituspools37–39; tables encode eggs36 as a nonfeeding routing pool. Fleetnodes40/41 retained separately as Artisanal/Commercial fisheries. Operational detritus convention includes36–39 and is explicitly recorded.

Hake species inherited from Tam2008:Merlucciusgayi peruanus, small<29cm,medium30–49cm,large>50cm. Printed gaps and unspecified length convention remain unresolved. These are separately tabulated static groups; no native multistanza links, transition ages, growth curve, or stanza equations were recovered. Plankton size classes inherited:20–200µm,200–2000µm,2–20mm.

Single taxa:Chrysaoraplocamia,Sardinopssagax,Engraulisringens,Dosidicusgigas,Trachurusmurphyi,Scomberjaponicus,Prionotusstephanophrys,Galeichtysperuvianus,Cheloniamydas,Dermochelyscoriacea. Historical source spellings are retained. Lists marked'e.g.' are representative examples; donor parameter analogues are not promoted to local group members.

Source biological data complete:all stocks1–35 have B/PB/EE and all33consumers have QB/AE/PQ. Source TL,BA,habitatfraction,migration,externaldetritusimport are unavailable. BA0 and other conventions exist only in explicit computational input; raw imports remain blank. Positive catch groups and real zero rows are retained in GROUP_CATCH_BIOMASS.csv. Large hake has zero landings but positive discards.

Fleet discards go100%tooffal37 in TableC; simplified calculator input retains donor removals but cannot preserve internal discard-return ancestry. Discard-flow loss is explicitly retained and makes production adoption ineligible.
'''
(R/'MODEL_PROFILE.md').write_text((R/'MODEL_PROFILE.template.md').read_text(encoding='utf-8'),encoding='utf-8')
report='''# Fresh source audit of Chiaverano et al. (2018)

The source extraction is complete and preserves the supplied original values. The detailed source does not reproduce a balanced steady-state budget. No numerical repair, biological pooling, canonical diet normalization, model adoption, regional workbook edit, Project.xlsx update, or map change was made.

The published title is *Evaluating the role of large jellyfish and forage fishes as energy pathways, and their interplay with fisheries, in the Northern Humboldt Current System*, Progress in Oceanography164:28–36, DOI10.1016/j.pocean.2018.04.009. The old short-title alias is retained in[SOURCE_IDENTITY.json](SOURCE_IDENTITY.json). The focal baseline averages1995–1998; 1995–2004 belongs to the cited dynamic predecessor history. The area is165,000km² from4°S to16°S and111km offshore (PDFp2/Figure1; PDFp3/printedp30 Methods). [Fresh Figure1 view](evidence/pdf-page-02.png) and coordinate text evidence are retained.

The original[article PDF](../../../papers/HUM-2018/1-s2.0-S0079661117303312-main.pdf),[XLS supplement](../../../papers/HUM-2018/Supplementary%20material%20revised%20and%20final.xls), and[Word figures/tables](../../../papers/HUM-2018/Peru%20paper%20figures%20and%20tables%20II.docx) were read afresh. All original hashes remain unchanged. Earlier archive README/metadata are stale history and were preserved. Authoritative actual source hashes are in[evidence/original_sources.json](evidence/original_sources.json).

## Detailed baseline and exact extraction

TableA has41source nodes with native IDs and names:36living groups as described in prose,3detrituspools,2fisheries nodes. The calculator representation has39stock groups; producers1–2,consumers3–35, and operational nonfeeding pools36–39. Source eggs36 are called living in prose, have B/EE but blankPB/QB/PQ/AE in TableA, and receive a25%Anchovy detritus-fate fraction in TableC. The source's'production rates assumed25%' sentence does not justify inventing annualPB. The pool classification is a disclosed translation. Fleetnodes40/41 carry no B/PB/QB and were kept as separate fleet evidence, not real groups with imputedB=1.

The exact group spine and taxonomy evidence are in[GROUP_IDENTITY.json](resolved_native/GROUP_IDENTITY.json),[Taxonomy.xlsx](resolved_native/Taxonomy.xlsx), and[TAXONOMY_EVIDENCE.csv](resolved_native/TAXONOMY_EVIDENCE.csv). Native trailing spaces in Anchovy,Smallhake,Largehake were preserved. Hake stages and residual-pool membership were verified against the explicitly cited[Tam2008 institutional PDF](evidence/Tam2008a.pdf), Methodspp353–354. Named lists retain source spellings, representative scope, and unverified synonym status. The precursor's saury,flyingfish,pelagicgoby entries are parameter donors and were not asserted as focal local members. No stage-share or catch allocation was inferred here.

TableA layout: A=source code; B=group name; C=B;D=PB;E=QB;F=PQ;G=AE;H=EE;I/J=Artisanal/Commercial landings;K/L=Artisanal/Commercial discards. Stock rows6–44;fleetnodesrows45–46. Bold cells are source-model estimates under the caption. The complementGS=1−AE was taken with exact decimal arithmetic for33feeding consumers. No zooplankton convention replaced sourceAE.

TableB has preyrows4–42 and39source predatorcolumnsB:AN; importsrow43. Matrix orientation was read from the caption and verified by exact name identity. All1,521stockdietcells and39imports, including explicit zeros, remain in the full extraction/canonical JSON and original-cell ledger. The ordinary EwE diet CSV contains the33feeding consumer columns and39preyrows, as required by its contract; omitted nonfeeding zero columns are retained in canonical/full evidence. Nonzeroimports:Macrobenthos8=.13,Othercephalopods13=.1,Other smallpelagicfish14=.05. No canonical/import diet cell was normalized.

TableC rows4–44 gives source/fate fractions to Eggs36,Offal37,Pelagic38,Benthic39,andExport. All rows sum1, including fleetnodes40/41→Offal37=1. Fleet-specific catches/discards and their fate are complete in[GROUP_CATCH_BIOMASS.csv](resolved_native/GROUP_CATCH_BIOMASS.csv) and[FLEET_DETRITUS_FATE.json](resolved_native/FLEET_DETRITUS_FATE.json). Source landings total34.119279175500000146 and discards total1.42026974257249992606t/km²/year. This simplified calculator can preserve donor removals but not the source internal discard-return ancestry; [the flow-loss ledger](computational/DISCARD_FLOW_TRANSLATION_LIMIT.json) quantifies that limitation without inventing external import.

## Precision, missingness, and conversion

Native stored XLS values are retained through their decimal representations. Display formats and bold/italic styles are separate evidence in[evidence/supplement_cells.json](evidence/supplement_cells.json). Stored single-precision tails do not add scientific measurement precision. Source tables display mostB/rates/EE/PQ/AE to two decimals; jellyfish dietH4,H7,H8,H9 to three decimals. Rounded display0.00 does not mean stored zero: turtle biomasses and ChrysaoraEE are positive, and some smallPQ values displayzero.

Source table headers labelB witht/km²/year. Eq1 definesB as stock biomass; canonical dimensional meaning ist wetweight/km². The original header is retained and no time conversion was applied. Catch units aret/km²/year;PB/QB areannual rates;AE/EE/PQ/diet/fate arefractions. Every cell and GS complement is linked to its exact sheet/address/sourcehash in[SOURCE_CELLS.json](resolved_native/SOURCE_CELLS.json). XLS formulas versus constant-cell provenance could not be distinguished through the reader; stored values were not recalculated.

The six CSVs plusTL.xlsx/Metadata.xlsx are the eight EwE import artifacts. The blankBAfile is faithful source missingness. TL has39source-unknownvalues; it was not computed and relabeled as publishedTL. Habitatfractions,migration,externaldetritusimports,totalmortality,andothermortality remain unknown in source evidence. The source canonicalJSON uses−9999for unknowns. [Computational model.json](computational/model.json) is separately constructed with explicit area1/BA0/migration0/externalimport0 conventions, knownAEcomplements, and operationaleggpoolpp2; [the ledger](computational/TRANSFORMATION_LEDGER.json) lists every change. All biologicalB/PB/QB/EEvalues remain native. The source declares steady-state; its equations did not support using a computedresidual as a recoveredBA.

[Round-trip checks](resolved_native/ROUND_TRIP_CHECKS.json) passed6,823exact/numeric checks: originalcell→imports→sourcecanonical→[reconstructed.xlsx](resolved_native/reconstructed.xlsx), including exact names,fullnative diet/proportions,routing,missingness, and taxonomy. All originals were rehashed. Workbook typed cells,sourceformats,and representative views of every exported sheet were visually checked; Metadata header clipping was corrected. The stockJSON reconstruction retainsGE/PQ/sourceAEcomplement separately. The stockJSON cannot natively encode fleetnodes,explicit fleetbreakdown,source Export fate outside its predecessor format,or native multistanza settings; companions retain these fields. There are no recoverednative stanza links/transitionages/growthcurves; separatestatic hake stages must not be relabelednative multistanza.

## Source conflicts and historical claims

The[conflict ledger](SOURCE_CONFLICTS.json) has exact locators and adopted/unresolved states. The paper's'balanced'caption is a source claim, not a result of this reconstruction.

* Sardine:PDFp3/printedp30 sayslandingswere reduced5.65→1.4toachievebalance. NativeTableA J14remains5.6513425. PrintedTable1 Foragefishlandings28.13matchesnative Sardine+Anchovy28.1268375, retainingthelargervalue. No sole consistent finaltableversion is established. The native supplement branch is retained; applying1.4wouldbeaseparatevariant. SourceEE remains.9700034857; changingcatchalonewould notrepairthegelatinousproductionproblem.
* Large jellyfish:TableB H4/H7/H8/H9/H39 are.00985221674876847,.73118226600985,.10470443349753696,.0492610837438424,.15,withzeroimport. Total1.04499999999999783. This material4.5% excess isnotrounding. Other totals outside.001areChubmackerel16=.995233899550000002,Largehake20=1.00905,Greenturtle34=1.002. Runtime normalization is a distinct diagnosticcopy and never changes canonical/importvalues.
* Small gelatinous production:TableA C11/D11/E11/H11 isB=.009068332612514496,PB=.5839999914169312,QB=2.919999837875366,EE=.949999988079071. Sourceproduction=.00529590617t/km²/year. Chrysaora alone consumes23.3497540704ofthispreyfromH9. Independent rawdietarithmetic gives gelatinousEEimplied4409.9702117vs.95. PrintedSmalljellyfishB.01/PB.58/QB2.92corroboratesthesourcenumericmagnitude. Sourcep35caveats call for improvedsmall-jellyfishbiomasssurveysbutgive no correctedparameter. No magnitude correction or unsupportedbiology was adopted.

[SOURCE_BUDGET_ARITHMETIC.json](resolved_native/SOURCE_BUDGET_ARITHMETIC.json) independently records nativepredation,catches,production,andEEdisagreements;BA/netmigration0are labeled arithmeticconventions. This is sourceaudit arithmetic, notadopted balance or a substitute for the actualdirectdiagnosticrun. RetainedparameterPQ for seabirds/mammals is lowbutpositive; no'plausibility correction' was made.

## Aggregated alternative and structural scenarios

PrintedTable1 hascodes4–28:24stockrowsplusonefleet. ECOTRANTableH adds3nutrientnodesfor28productionnodes. Exact printed twodecimal values/blanks and PDFcoordinates are retained in[aggregated_Table1_printed.json](aggregated_Table1_printed.json). SupplementTableF diets,TableG separatedfeces/senescence/NH4fates,TableH productionmatrix,TableI uncertaintyCV,andTableE crosswalk remain [raw alternative evidence](aggregated_alternative_source.json). Sheet captions are one letter later forF–I than sheetnames; both are recorded.

Names govern the crosswalk:TableE/ECOTRANcode24=Pelagicdetritus,25=Eggs,26=Offal,whileprintedTable1code24=Eggs,25=Offal,26=Pelagicdetritus. SourceEEeggs.8843322396versusprintedaggregate.87 is notsimple displayrounding. SourceDiatomsTableC routesdetritustoPelagic,whereasaggregateTableG routesLargephytoplankton senescence toSubsurface. TableG isECOTRANfatepartitioning anddoesnotprovideanequivalentunique Ecopathcombinedmatrix. PrintedTurtleB0.00wouldlosepositivebiomass. The aggregatedalternativetherefore haslessprecision,additionalrepresentationdifferences,andbothjellyfishissues;itisnotasoundrepairbyaggregation. Detailedresolvedsource ispreferable for membership/catchdiagnostic auditing,withalllimitationsretained.

SupplementScenarioI/II and WordTable2 containfractionalproductionchangesandMonteCarlouncertainty summaries,notindependentEcopathinputsets. Focalstructuralscenariosarelinearasymptoticsolutions,+50%jellyfish/forageconsumption,+40%forageharvest,andfisheryclosure. Theydonotjustifyreusingchangedendpointstatesascompletebaseline models. The source's 25%eggstatement isnottranscribedasanannualproductionrate. No scenario endpoint was constructed orrun here.

## Validation and handoff

Officialimportvalidator:[VALIDATION.txt](resolved_native/VALIDATION.txt):1error(sourceChrysaoradiet1.045),3warnings(basal/poolGSblank,BAunknown,TLmissing). These are evidence/findings; cells remain faithful. Source-round-trip passes, modelmass-balanceadmission does not. The requestedactualdirectdiagnosticoutputs are produced separatelybythe diagnosticsagent from thepersistedcomputationalinput;methodgrades andruntimechangesbelongtothatrun. No validatedannual regionalPPRcoefficientorproductionadoption followsfromthisextraction.

Boundedprimaryrecovery:[RECOVERY_SEARCH.json](RECOVERY_SEARCH.json). TheverifiedTam2008sourcewasread;focalcorrectionqueriesdidnotfindanumericalcorrigendum. A2018Quiñonescorrigendumisadifferentpaperandwasnotusedtocorrectthismodel. No author-nativeconsistentEwEdatabasewasrecovered. Fullnativeformula lineage,genericgroupmembers,missingTL/BA/migration/imports,andnativefleetdiscardancestryremainexplicitlimitations. Allnewartifactsonlyresideinthiscandidate/sourcefolder;existingacceptedparameters/models,activeworkbooks,Project.xlsx,andmap/graphareuntouched.
'''
# Human-readable spacing after numeric tokens and compound source references.
replacements={'164:28':'164: 28','DOI10':'DOI 10','averages1995':'averages 1995','area is165':'area is 165','from4':'from 4','and111':'and 111','source nodes':'source nodes','41source':'41 source','36living':'36 living','3detritus':'3 detritus','2fisheries':'2 fisheries','39stock':'39 stock','33feeding':'33 feeding','all33':'all 33','All1,521':'All 1,521','39imports':'39 imports','total34':'total 34','total1.420':'total 1.420','passed6,823':'passed 6,823','has39':'has 39','codes4':'codes 4'}
for a,b in replacements.items():report=report.replace(a,b)
(R/'REPORT.md').write_text((R/'REPORT.template.md').read_text(encoding='utf-8'),encoding='utf-8')
(R/'README.md').write_text((R/'README.template.md').read_text(encoding='utf-8'),encoding='utf-8')
art=[]
sources=Path.cwd()/'regions/LME_013/papers/HUM-2018'
for a in orig:art.append({'role':'source_'+a['filename'].split('.')[-1],'path':'../../../papers/HUM-2018/'+a['filename'],'sha256':a['sha256'],'availability':'present'})
roles={'canonical_source':'resolved_native/model.json','extraction':'resolved_native/extraction.json','basic_import':'resolved_native/Basic_input.csv','diet_import':'resolved_native/Diet_composition.csv','landings_import':'resolved_native/Landings.csv','discards_import':'resolved_native/Discards.csv','fate_import':'resolved_native/Detritus_fate.csv','BA_import':'resolved_native/Biomass_accumulation.csv','TL_import':'resolved_native/TL.xlsx','metadata_import':'resolved_native/Metadata.xlsx','taxonomy':'resolved_native/Taxonomy.xlsx','taxonomy_evidence':'resolved_native/TAXONOMY_EVIDENCE.csv','source_cell_ledger':'resolved_native/SOURCE_CELLS.json','source_snapshot':'evidence/supplement_cells.json','round_trip':'resolved_native/ROUND_TRIP_CHECKS.json','reconstruction':'resolved_native/reconstructed.xlsx','source_conflicts':'SOURCE_CONFLICTS.json','profile':'MODEL_PROFILE.md','budget_context':'resolved_native/SOURCE_BUDGET_ARITHMETIC.json','report':'REPORT.md','computational_input':'computational/model.json','transformation_ledger':'computational/TRANSFORMATION_LEDGER.json','discard_translation':'computational/DISCARD_FLOW_TRANSLATION_LIMIT.json','source_fleet_fate':'resolved_native/FLEET_DETRITUS_FATE.json','aggregated_alternative':'aggregated_alternative_source.json','printed_aggregate':'aggregated_Table1_printed.json','predecessor':'evidence/Tam2008a.pdf','recovery_record':'RECOVERY_SEARCH.json','field_availability':'resolved_native/FIELD_AVAILABILITY.json','source_identity_metadata':'SOURCE_IDENTITY.json','readme':'README.md','group_identity':'resolved_native/GROUP_IDENTITY.json','catch_biomass_vector':'resolved_native/GROUP_CATCH_BIOMASS.csv'}
for role,p in roles.items():art.append({'role':role,'path':p,'sha256':sha(R/p),'availability':'present'})
art.append({'role':'author_native_EwE_database','availability':'missing','reason':'No author-native consistent database/export recovered; source XLS tables preserved separately','acquisition_status':'bounded sources/recovery examined; not recovered'})
jw(R/'evidence_index.json',{'schema_version':1,'run_id':'HUM2018_20261003_fresh_source','region_id':'LME_013','model_id':'HUM2018_resolved_native','variant_id':'native_supplement_uncorrected','source_identity':{'sha256':snap['source_sha256'],'doi':identity['doi']},'computational_input_identity':{'path':'computational/model.json','sha256':sha(C/'model.json')},'methods':[],'methods_options':{'source_only':True,'source_normalization':False,'adoption':False,'operational_egg_pool':True},'required_roles':['source_pdf','source_xls','source_docx']+list(roles),'artifacts':art,'reconciliation':{'source_originals_unchanged':True,'round_trip_exact':json.loads((N/'ROUND_TRIP_CHECKS.json').read_text())['passed'],'39stock_ids_preserved':len(data['groups'])==39,'taxonomy_three_columns':True},'ecological_admission':'fails; ecological failure does not erase complete source evidence','missing_optional':['author_native_EwE_database']})
print('Source report, conflict ledger and evidence index authored; input hashes preserved.')
