from pathlib import Path
import sys,json,math,copy,pickle,collections
Q=Path(__file__).parent;ROOT=Q.parents[4];sys.path.insert(0,str(ROOT/'tools'));import workbooks as W;import regional as RC
R=ROOT/'regions/LME_038';MID='38_38003_Java_Sea_normalized_BA_completed_(mid1970s)';E=R/'validation_reports'/MID;MP=R/'models'/MID
def dump(n,v):(E/n).write_text(json.dumps(v,ensure_ascii=False,indent=2,allow_nan=False),encoding='utf-8')
b=pickle.load((Q/'book.pkl').open('rb'));old=copy.deepcopy(b);native={int(g['group_seq']):g for g in json.loads((MP/'model.json').read_text(encoding='utf-8'))['group']};g={int(g['seq']):g for g in W.records(b,'Selected model groups','Groups')};gn={s:r['group_name']for s,r in g.items()};gi={v:k for k,v in gn.items()}
ds=json.loads((MP/'evidence/MAPPING_DECISIONS.json').read_text(encoding='utf-8'))['taxa'];prior=collections.defaultdict(list)
for m in W.records(b,'PPR','Matching'):prior[m['taxon']].append(m)
classic={r['taxon']:r for r in W.records(b,'Classic PPR','Taxa')};rank=['Unresolved','Very low','Low','Medium','High'];audit=[];newmaps=[];ledger=[];changes=[];decisions=[]
def choose(t,r):
 d=ds[t];ids=[gi[x['group']]for x in prior[t]if x.get('group')];base=d['explanation']
 broad={
 'Marine fishes not identified':([5,8,12,14,15,18,19,20,21,22,23,25,26],'SAU key 100039 / ISSCAAP 39 is bony fishes. All actual represented bony members are candidates, including ichthyoplankton (5, genuine zero), named pelagics and mixed Misc. pelagics / large demersals. Dedicated rays (24) excluded. Source14 includes Mobulidae and source23/26 also sharks/rays; pooled composition is not bony-only.'),
 'Marine pelagic fishes not identified':([5,8,12,14,18,19,20,21,22,25],'SAU key100339 / ISSCAAP39 is bony pelagic fishes. Includes actual source ichthyoplankton, Sphyraenidae in SAF, Caesionidae/Stromateidae water-column members in Small demersals, Rachycentron in Medium demersals and named pelagic guilds. Dedicated rays and large-demersal bony members are excluded; source14 Mobulidae remains pooled contamination.'),
 'Perciformes':([8,12,14,15,18,19,21,22,23,25,26],'Historical fisheries perch-like category spans named scombrid/carangid, reef and demersal bony source members. Functional Medium demersals tag is not an exhaustive scope. Modern order reclassification and unknown constituent/size composition make this an explicit broad approximation; clupeoids, cartilage and fish larvae lack a specific perch-like connection.'),
 'Scombroidei':([8,12,14,19,25],'Historical SAU tunas/bonitos/billfishes concept includes source large scombrids, Auxis and Rastrelliger, with historical barracuda connection to SAF. Billfishes are absent from exact source membership and use large-pelagic analogues. It is not a modern-order identity claim.'),
 'Mollusca':([3,7,9,17],'Broad reported clams/seasnails/squids/octopuses can span source mollusc larvae (3), small burrowing molluscs (7), commercial-size macrozoobenthos (9) and cephalopods (17). Commercial catch suggests larger members but does not measure stage composition or establish exclusion. Mixed larvae/benthos pools remain approximate.'),
 'Decapoda':([4,7,11,13,16],'Broad decapod identity includes sergestids/decapod larvae (4), plausible benthic crustacean larvae (7), juvenile/adult shrimps (11/13), and crabs/lobsters (16). SAU Lobsters, crabs tag supports ecology but is not an exhaustive taxonomic exclusion of shrimp/larvae. Mixed source composition remains unobserved.'),
 'Miscellaneous marine crustaceans':([3,4,7,11,13,16],'SAU marine crabs/shrimps/lobsters nei is broad Crustacea. Candidate crustaceans include source copepods/ostracods/cirripedia larvae (3), sergestids and other large zooplankton (4), burrowing crustaceans (7), shrimp stages (11/13), crabs/lobsters (16). Shrimp functional tag alone cannot establish all caught membership; pooled mixed-stage composition is approximate.'),
 'Miscellaneous aquatic invertebrates':([3,4,5,6,7,9,10,11,13,16,17],'Generic aquatic invertebrates can include every actual invertebrate-bearing source pool: plankton/larvae, medusae, benthos, living bottom structure, shrimp stages, crabs/lobsters and cephalopods. Commercial caught members/stages are unknown. Carnivorous zooplankton also contains fish larvae, and LBS catch is an author-assumed bycatch proxy.')}
 if t in broad:return broad[t][0],'M10','Very low',broad[t][1]
 if t=='Dendrobranchiata':return[4,11,13],'M9','Medium','Dendrobranchiate shrimps include source sergestids in Large herbivorous zooplankton (4) and penaeid/general shrimp juvenile/adult stages (11/13). Source-specific sergestid placement takes priority over broad all-shrimp stage wording. Unknown residual family/stage composition is assumed across the complete source-containing set.'
 if t=='Nemipteridae':return[8,21],'M9','Medium','FAO1990 modern Nemipteridae includes Nemipterus/Scolopsis and Pentapodus. Source Small demersals explicitly names Nemipteridae while SAF names historical Pentapodidae; FAO1974 Pentapodidae includes Pentapodus and related genera. This coarse family label needs both source homes, with reef/structure and size composition assumed; Scolopsis alone does not establish a whole-family synonym bridge.'
 if t=='Pleuronectiformes':return[21,22,23,26],'M10','Very low','Broad flatfish order includes explicit source Cynoglossidae Small demersals and Psettodidae Medium demersals plus unlisted families such as Paralichthyidae that can cross larger size pools. Complete demersal-size analogue set retains the same large candidates reviewed for the constituent family; provider<90cm tag does not establish exclusion. Source family/size composition remains unknown.'
 if t in ['Bivalvia','Echinodermata','Crassostrea','Modiolus','Perna viridis','Tegillarca granosa','Veneridae']:
  return[3,7,9],('M2'if t=='Tegillarca granosa'else'M9'),('High'if t=='Tegillarca granosa'else'Medium'),'Source Table3.1 includes bivalve/echinoderm larvae in Small herbivorous zooplankton(3), <=1.0mm burrowing molluscs/echinoderms and benthic larvae in Benthic infauna(7), and >1.0mm molluscs/echinoderms in Macrozoobenthos(9). Complete source stage/size union is retained instead of treating commercial catch as observed adult composition. Genuine Harvest zeros in3/7 give100%group9 only under the model-catch proxy. '+('Tegillarca/Anadara granosa name bridge is retained.'if t=='Tegillarca granosa'else'')
 if t=='Batoidea':return[14,23,24,26],'M9','Medium','Batoid scope includes explicit Mobulidae in Misc. pelagics as well as Dasyatidae/Myliobatidae rays and sawfish/guitarfish in large demersal stages. Original set omitted the Mobulidae home. Actual bony/shark co-members and unknown caught composition limit the assumed source-containing set.'
 if t=='Elasmobranchii':return ids,'M9','Medium','Sharks/rays/skates reporting excludes chimaeras. Actual source Mobulidae, Carcharhinidae/Sphyrnidae and batoids establish the candidate guilds, but the family-level shelf summary does not exhaust every local shark/skate family. Mixed bony source members and species composition remain uncertain.'
 if t=='Chondrichthyes':return ids,'M10','Very low','Cartilaginous reporting includes sharks/rays and chimaeras. Represented shark/ray members support these candidate guilds; chimaeras have no documented source compartment. This broader approximation preserves the absent-component limitation and mixed bony pooling.'
 if t in ['Serranidae']:return ids,'M10','Very low','Historical source Serranidae covers small/medium groupers and named Epinephelus lanceolatus large stages; modern Epinephelidae and Serranidae differ. SAU basses/groupers/hinds label supports a historical catch concept, not modern family synonymy. Unknown bass/grouper/size composition remains approximate.'
 if t in ['Lutjanidae','Pristipomoides','Ariidae','Epinephelus','Sciaenidae','Carangidae','Scombridae','Clupeiformes']:return ids,'M9','Medium',base+' Family/genus habitat/size contents and source exceptions were checked; representative source families support this set, while full regional composition remains assumed.'
 if t=='Pomadasys argenteus':return ids,'M6','Low','Source Haemulidae occurs in both Small and Medium demersals. FAO Western Central Pacific Silver grunt account (printed2983) gives maximum about60cm/common40cm, positively supporting Medium under the source average-or-maximum40–60cm rule. Small remains an uncertain size interpretation because source uses average or maximum, not an observed individual-size split; complete retained pair and source catches remain assumed.'
 if t=='Scolopsis':return ids,'M6','Low','FAO1990 places Scolopsis in Nemipteridae, explicitly in source Small demersals. Historical Pentapodidae source SAF name does not synonymize the entire modern family (FAO1974 lists Pentapodus/Gnathodentex/Monotaxis/Gymnocranius, not Scolopsis). Reef association gives a competing SAF ecology and the source average-or-maximum size criterion is not resolved; retained Small demersals is a partial fit.'
 if t=='Cephalopholis boenak':return ids,'M3','High','FAO1993 grouper account (printed38) establishes historical Serranidae, maximum26cmTL and4–30m silty dead reef habitat. This fits source Small demersals<40cm criterion; source named large Epinephelus lanceolatus exception is different. Dead-reef occurrence alone does not establish SAF dependence on living bottom structure through the life cycle.'
 if t in ['Carcharhinus falciformis','Carcharhinus longimanus','Prionace glauca']:return ids,'M6','Low','Verified carcharhinid fits the source large-demersal juvenile/adult union taxonomically, but oceanic/pelagic occurrence conflicts with the guild habitat-first demersal construction. Source broad family list and absent species composition support a partial placement; stage shares are graded separately.'
 if d['basis']=='model_catch':return ids,'M3','High',base+' Membership in the full documented source pair is supported independently of its assumed internal stage allocation. Source juvenile Harvest construction and unknown caught-stage composition do not raise allocation confidence.'
 if not ids:
  if t in ['Lates calcarifer','Latidae']:return[23,26],'M11','Very low','Unlisted large coastal/estuarine fish predator uses source large-demersal Arius/Muraenesox/Epinephelus union as the closest represented analogue. Brackish/freshwater habitat, lineage and guild composition differ. Small/Medium demersals do not represent the large size; SAF requires a more specific structure dependence not established here.'
  if t in ['Cypselurus poecilopterus','Exocoetidae']:return[14],'M11','Very low','Unlisted surface-schooling flyingfish has the closest family-order/ecological connection to source Misc. pelagics Belonidae/Hemiramphidae. Flyingfishes are absent from that list and offshore/surface feeding differs. Clupeoids and large-predator stages are less specific alternatives.'
  if t in ['Xiphias gladius','Istiompax indica','Kajikia audax','Tetrapturus angustirostris','Istiophorus platypterus','Istiophoridae','Makaira','Coryphaena hippurus']:return[12,25],'M11','Very low','Unlisted large pelagic predator uses the source Chirocentridae/large Scombridae/Trichiuridae juvenile/adult union as an ecological analogue. Oceanic/deeper distribution and family differences remain; Misc. pelagics is a less specific small/medium assemblage and no exact billfish/dolphinfish group exists.'
  if t in ['Alopias','Isurus oxyrinchus','Isurus']:return[23,26],'M11','Very low','Unlisted thresher/mako shark uses the represented large shark stages through actual Carcharhinidae/Sphyrnidae source members. Pelagic/oceanic habitat and different family are material mismatches; Misc. pelagics Mobulidae and dedicated demersal rays are less suitable shark analogues.'
  if t in ['Platycephalidae','Paralichthyidae']:return[21,22,23,26],'M11','Very low','Unlisted benthic flathead/flounder predator has a positive coastal bottom-fish connection to source Small demersals (Synodontidae/Cynoglossidae), Medium demersals (Psettodidae), and large demersal predators. Family size variation can cross source <40/40–60/>60cm average-or-maximum pools; complete source size/growth set is an explicit approximation, not observed catch-size composition.'
  if t in ['Plotosus','Plotosidae']:return[21,22,23,26],'M11','Very low','Unlisted coastal benthic eel catfish uses source Ariidae catfish in Small demersals and named Arius thalassinus large juvenile/adult stages, with Medium demersals as the intervening bottom-fish size analogue. FAO Western Central Pacific Plotosus lineatus maximum about30cm supports a small constituent, while P. canius common lengths up to80cm support larger analogues; the guide historical maximum150cm is not measured Java Sea composition and has been questioned. A small species cannot bound the whole genus/family. Complete source-size analogue set avoids assuming observed size composition; family/reef ecology differs and SAF remains a competing less taxonomically specific ecology.'
  if t=='Labridae':return[8],'M5','Medium','Unlisted wrasses have a supported reef/structure-associated connection to source SAF (LBS-dependent biota and named reef-fish families). Extension to the whole wrasse label is assumed; some members use sand/seagrass and do not establish exclusive structural dependence. Residual demersal pools are less specific alternatives.'
  if t=='Congridae':return[22,23,26],'M11','Very low','Unlisted conger/garden-eel family uses the source Muraenesocidae pike-conger homes in Medium demersals (Congresox) and large-demersal juvenile/adult stages as the closest related benthic eel analogue. Complete represented conger-size homes are retained. Family, maximum size, deep-water and garden-eel habitats differ, with no reported constituent proportions; Small demersals is a less specific residual bottom-fish ecology.'
  if t=='Megalops cyprinoides':return[14],'M11','Very low','Unlisted coastal/estuarine tarpon uses Misc. pelagics coastal schooling fish as a functional analogue. Tarpon is absent and estuarine migration/lineage differs; large-predator pair and reef SAF are less specific represented assemblages.'
  if t in ['Bramidae','Berycidae','Lampris guttatus','Lepidocybium flavobrunneum']:return([14]if t in ['Bramidae','Berycidae']else[12,25]),'M11','Very low','Unlisted oceanic/deep-water fish has the closest represented '+('Misc. pelagics bony schooling-fish'if t in ['Bramidae','Berycidae']else'large-pelagic predator')+' connection. The shallow Java Sea lacks a dedicated bathypelagic/deep-slope guild; depth, lineage and source size composition are material mismatches. Demersal shelf guilds offer no exact deep-water alternative.'
  raise ValueError('unreviewed unresolved '+t)
 if t in ['Decapterus','Rastrelliger','Leiognathidae','Balistidae','Lethrinidae','Polynemidae','Sphyraenidae','Sparidae','Tetraodontidae','Caesionidae','Mullidae','Mugilidae','Synodontidae','Stromateidae','Dasyatidae']:return ids,'M9','Medium','Source names the related family/genus assemblage, with habitat/size rules and a limited regional species summary. Reported modern genus/family can contain unlisted or ecologically variable members; the retained source home is an explicit supported extension, not exhaustive modern-family containment. Named source exceptions and competing stage/guild homes were checked.'
 if d['confidence']=='medium':return ids,'M5','Medium',base+' Functional catch metadata supports ecology but does not prove exclusive source membership; the source-specific taxonomic connection is retained as an extension.'
 return ids,('M2'if t in ['Dussumieria acuta','Netuma thalassina','Tegillarca granosa']else'M3'),'High',base+' Source member or documented family/generic criterion supports this particular taxon; competing named exceptions were checked. Habitat-first and average-or-maximum length convention are retained as source limitations, not provider-bin thresholds.'
for r in sorted([x for x in W.records(b,'Catch','Catch')if x['catch_basis']=='landings'],key=lambda x:x['taxon']):
 t=r['taxon'];ids,mr,mc,why=choose(t,r);assert len(ids)==len(set(ids))and all(s in native for s in ids)
 raw=[float(native[s]['export'])for s in ids];bio=[float(native[s]['biomass'])for s in ids];oldids=[gi[x['group']]for x in prior[t]if x.get('group')];same=set(ids)==set(oldids)
 if len(ids)==1:ws=[1.];wr='W1';wc='High';ww='One reviewed source group receives100%; no numerical split.'
 elif same and ds[t]['basis']=='catch_composition':
  pw={gi[x['group']]:x['weight']for x in prior[t]if x.get('group')};ws=[pw[s]for s in ids];wr='W5';wc='Low';ww='Exact historical1950–2019 identified-total-catch guild fractions retained. Actual donors include all eligible direct/stage taxa in candidate guilds, without a lineage restriction. Raw country/sector/gear/reporting/year/basis mismatch and unobserved residual species composition limit this proxy.'
 elif all(math.isfinite(x)and x>=0 for x in raw)and math.fsum(raw)>0:
  ws=[x/math.fsum(raw)for x in raw];wr='W4';wc='Medium';ww='Complete printed1974–1976 Harvest proportions, including genuine source zeros, are an assumed composition/catchability proxy. Juvenile shrimp .008 and large-demersal juvenile .066 are author-assumed catches; no observed stage composition is claimed.'
  if same:
   pw={gi[x['group']]:x['weight']for x in prior[t]if x.get('group')};assert all(math.isclose(pw[s],w,abs_tol=1e-8)for s,w in zip(ids,ws)),t;ws=[pw[s]for s in ids]
 else:
  assert all(math.isfinite(x)and x>=0 for x in bio)and math.fsum(bio)>0;ws=[x/math.fsum(bio)for x in bio];wr='W9';wc='Medium';ww='Complete model biomass fallback follows unusable/zero-total source catch; assumed composition/catchability, not caught-mass evidence.'
 overall=min([mc,wc],key=rank.index);reason=(why+' '+ww+' Fixed mid1970s source coefficients and weights transfer across1950–2019 whole-LME landings/catch/discards.').replace('key100','key 100').replace('ISSCAAP39','ISSCAAP 39').replace('source14','source 14').replace('source23','source 23').replace('1974–1976','1974–1976').replace('printed1974','printed 1974').replace('historical1950','historical 1950').replace('receives100','receives 100').replace('across1950','across 1950').replace('FAO1990','FAO 1990').replace('FAO1974','FAO 1974')
 co=classic.get(t,{});c=r[2019];sp=co.get('sppr');pp=0. if c==0 else c*sp/9 if W.finite(c)and W.finite(sp)else None
 a=dict(taxon=t,tl=co.get('tl'),classic_sppr=sp,catch_tonnes=c,simple_chain_ppr_tC=pp,common_name=r['common_name'],functional_group=r['functional_group'],membership_rule=mr,membership_confidence=mc,allocation_rule=wr,allocation_confidence=wc,overall_confidence=overall,assumed=mc!='High'or len(ids)>1,group_ids=ids,group_names=[gn[s]for s in ids],weights=ws,mapping_display='; '.join(gn[s]+f' ({100*w:.6f}%)'for s,w in zip(ids,ws)),reason=reason,sources=['Buchary1999Table3.1','Buchary1999Table3.9','SAUv50.1','ClassicSaved']+(['ProxyReview']if wr=='W5'else[]),prior_mapping=prior[t])
 audit.append(a);new=[]
 for i,(s,w)in enumerate(zip(ids,ws)):
  row=dict(model_id=MID,taxon=t,group=gn[s],weight=w,confidence=overall.lower().replace(' ','_'),evidence=f'validation_reports/{MID}/taxon_audit.json',explanation=reason)
  if w>0:newmaps.append(row);new.append(row)
  ledger.append(dict(unit_id='LME_038',model_id=MID,taxon=t,group=gn[s],seq=s,weight=w,rule=wr,membership_rule=mr,membership_confidence=mc,allocation_confidence=wc,confidence=overall.lower().replace(' ','_'),assumed=a['assumed'],source_catch_field='export / Table3.9 Harvest',source_catch_raw=native[s]['export'],source_catch=raw[i],loaded_catch=g[s]['catch'],source_biomass=bio[i],catch_provenance='Printed source value, including genuine zero; shrimp juvenile11 and demersal juvenile23 explicitly author-assumed. LBS10 is10×SAF source bycatch assumption. Not loader-default catch.',source_period='1974–1976',years_applied='1950–2019',catch_bases_applied='landings;catch;discards',evidence=row['evidence'],limitations=reason))
 decisions.append(dict(taxon=t,included=[dict(seq=s,group=gn[s],source_catch=raw[i],source_catch_raw=native[s]['export'],source_biomass=bio[i],weight=ws[i],genuine_printed_zero=raw[i]==0)for i,s in enumerate(ids)],excluded=[dict(seq=s,group=gn[s],reason='Outside reviewed target set. '+why)for s in native if s not in ids],membership_rule=mr,allocation_rule=wr,catch_total=math.fsum(raw),biomass_total=math.fsum(bio),source_decision=why,source_field='Table3.9 Harvest t/km²/year; canonical export unchanged.'))
 changes.append(dict(taxon=t,old=prior[t],new=new,kind='mapping_or_weight'if [(x.get('group'),x.get('weight'))for x in prior[t]]!=[(x['group'],x['weight'])for x in new]else'confidence_or_rationale',membership_rule=mr,allocation_rule=wr))
assert len(audit)==181 and all(math.isclose(math.fsum(a['weights']),1,abs_tol=1e-10)for a in audit)
ct=math.fsum(a['catch_tonnes']for a in audit);pt=math.fsum(a['simple_chain_ppr_tC']for a in audit if W.finite(a['simple_chain_ppr_tC']))
def parts(rule,conf):
 out=[]
 for rr,cc in sorted(set((a[rule],a[conf])for a in audit)):
  p=math.fsum(a['simple_chain_ppr_tC']for a in audit if a[rule]==rr and a[conf]==cc and W.finite(a['simple_chain_ppr_tC']));out.append(dict(rule=rr,confidence=cc,ppr_tC=p,ppr_percentage=p/pt*100))
 return sorted(out,key=lambda x:-x['ppr_percentage'])
cats=[]
for label in ['High','Medium','Low','Very low','Unresolved']:
 aa=[a for a in audit if a['overall_confidence']==label];c=math.fsum(a['catch_tonnes']for a in aa);p=math.fsum(a['simple_chain_ppr_tC']for a in aa if W.finite(a['simple_chain_ppr_tC']));cats.append(dict(label=label,taxa=len(aa),catch_tonnes=c,ppr_tC=p,catch_percentage=c/ct*100,ppr_percentage=p/pt*100))
summary=dict(unit_id='LME_038',model_id=MID,year=2019,basis='landings',source_scope='all',taxon_filter='all',group_filter='none',unidentified='method',source_groups=28,synthetic_groups=['diet_import29'],taxa=181,total_catch_tonnes=ct,total_simple_chain_ppr_tC=pt,missing_coefficient_taxa=[a['taxon']for a in audit if not W.finite(a['classic_sppr'])],unknown_ppr_taxa=[a['taxon']for a in audit if a['simple_chain_ppr_tC']is None],confidence_summary=cats,membership_summary=parts('membership_rule','membership_confidence'),allocation_summary=parts('allocation_rule','allocation_confidence'))
for n,v in [('taxon_audit.json',audit),('candidate_and_allocation_evidence.json',decisions),('adopted_mapping_changes.json',changes),('coverage_summary.json',summary)]:dump(n,v)
if '--adopt'in sys.argv:
 assert W.sha(R/'LME_038.xlsx')=='90782e72dd029e1f86e6daa1306c631ea55db505b34c01dc3f26bce89fdde6cb'
 b['PPR']['Matching']=W.table_dict(newmaps);b['PPR']['Mapping review']=W.table_dict([{k:a[k]for k in ['taxon','membership_rule','membership_confidence','allocation_rule','allocation_confidence','overall_confidence','assumed','reason']}for a in audit]);b['PPR']['Allocation assumptions']=W.table_dict(ledger)
 RC.recalculate(b,R/'LME_038.xlsx');b['Classic PPR']=copy.deepcopy(old['Classic PPR']);rh,rv=b['PPR–NPP']['Ratios'];b['PPR–NPP']['Ratios']=(rh,[r for r in W.rows(old,'PPR–NPP','Ratios')if not r[0]]+[r for r in rv if r[0]])
 RC.set_setting(b,'source_note','All181 catch labels reviewed and provisionally mapped, including zero catch. Broad bony-fish and invertebrate sets use actual source members; absent taxa use explicit analogues. Source-model catch and identified-catch donor allocations are assumptions. GE/Egestion OK thresholds and TE WARN remain; accepted normalized diet/completed BA retained. Evidence: validation_reports/'+MID+'/taxon_audit.json.')
 RC.set_setting(b,'calculation_status','provisional: reviewed mappings and assumptions; accepted derived variant; TE WARN; full-LME/time transfer limits retained');RC.set_setting(b,'mapping_limitation','28 formerly unresolved labels receive documented analogues; residual source sets corrected; W5 donor mismatch remains Low; W4 model catch Medium includes author assumptions. Mid1970s Java Sea to full LME1950–2019 extrapolation; no biological repair.');RC.set_setting(b,'production_eligible',False);RC.set_result_hash(b);W.write_book(R/'LME_038.xlsx',b)
 for sh in ['Catch','Classic PPR','NPP','Selected model groups','Diagnostics']:assert W.digest_tables(list(b[sh].items()))==W.digest_tables(list(old[sh].items())),sh
 pickle.dump(b,(Q/'adopted_book.pkl').open('wb'));dump('adoption_record.json',dict(workbook_sha256=W.sha(R/'LME_038.xlsx'),input_hash=W.input_hash(b),result_hash=RC.result_hash(b),taxa=181,canonical_model_sha256=W.sha(MP/'model.json'),protected_cached_blocks_exact=True,fresh_canonical_validation_pending=True))
print(json.dumps(summary,indent=2))
