from pathlib import Path
import json,hashlib,shutil
Q=Path(__file__).parent;ROOT=Q.parents[4];MID='38_38003_Java_Sea_normalized_BA_completed_(mid1970s)';R=ROOT/'regions/LME_038';E=R/'validation_reports'/MID
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(n,v):(E/n).write_text(json.dumps(v,ensure_ascii=False,indent=2,allow_nan=False),encoding='utf-8')
c=ROOT/'original_research_archive/research/selected_regions_validation_20260930/central_source_metadata_current.json';s=json.loads(c.read_text(encoding='utf-8'));assert s['project_sha256']==sha(ROOT/'Project.xlsx'),(s['project_sha256'],sha(ROOT/'Project.xlsx'))
s['tables']={k:[r for r in v if r.get('unit_id')=='LME_038']for k,v in s['tables'].items()};dump('central_metadata_snapshot.json',s)
coverage='Source PDF29/printed20 approximate Java Sea prose bounds, with Natural Earth1:50 million land removal and two source eastern-bound scenarios116.5/117.5E: target fraction A≈19–22%, study fraction B≈99–100%. Source Figure2.1 is bathymetry/context, not an explicit study polygon. Northern/southern prose limits may truncate coast-following water. Reported471000km² remains separate from reconstructed441114/488277km². Low geographic confidence; whole-LME extrapolation and no geographic PPR multiplier.'
fields={'Models & coverage':{'availability':'Selected accepted derived model available and reloaded exactly. Fresh direct GE/With Egestion OK, TE WARN; full source matrices finite/nonnegative. Mapping review covers181 labels provisionally; parameter validity and whole-LME/time application limits retained.','target_coverage_ratio':0.21441532733779304,'coverage_note':coverage},'Papers':{'full_model_loadable':'Accepted user-authorized normalized/computational-BA derived model reloads exactly; printed source remains inadmissible as printed.','extraction_readiness':'Source-faithful extraction and selected accepted derived variant retained; current source/model/mapping review complete with explicit source differences and TE WARN.','geometry_method':'Approximate prose-bounds reconstruction, coast-clipped with Natural Earth1:50 million; source eastern-bound scenarios116.5/117.5E; WGS84 intersection.','geometry_confidence':'Low: approximate regional prose extent; no explicit source study polygon; A≈19–22%,B≈99–100%.','target_coverage_ratio':0.21441532733779304,'geometry_note':coverage,'coverage_note':coverage}}
patches=[]
for table,changes in fields.items():
 key='model_id'if table=='Models & coverage'else'article_id';value=MID if key=='model_id'else'INDO-1999__LME_038';r=next(x for x in s['tables'][table]if x[key]==value)
 for field,new in changes.items():patches.append(dict(table=table,key={key:value,'unit_id':'LME_038'},field=field,expected_old=r.get(field),proposed_new='Low'if field=='geometry_confidence'else new,evidence=f'regions/LME_038/validation_reports/{MID}/source_review.md'))
oldfoot=R/'papers/INDO-1999/footprint.geojson';newfoot=E/'geography/reconstructed_study_bounds.geojson'
foot=dict(geometry_key='article:INDO-1999__LME_038',article_id='INDO-1999__LME_038',unit_id='LME_038',expected_old_region_footprint_path=str(oldfoot.relative_to(ROOT)).replace('\\','/'),expected_old_region_footprint_sha256=sha(oldfoot),proposed_geometry_path=str(newfoot.relative_to(ROOT)).replace('\\','/'),proposed_geometry_sha256=sha(newfoot),method='Approximate prose-bounds water reconstruction with larger east117.5 scenario; source original figure has no explicit study polygon.',confidence='Low',limitations='Larger source scenario only; east116.5 sensitivity retained. Approximate latitude clipping can truncate coast-following water. Reported471000km² is distinct. Root must authenticate current shared article geometry and reconcile exact old state.')
dump('shared_metadata_proposals.json',dict(project_snapshot_sha256=s['project_sha256'],changes=patches,source_footprint_proposals=[foot],limitations='Ratio uses larger eastern scenario, clearly approximate; interval is controlling geographic evidence. Historical retrieval attempts, legacy ratings and source-faithful values are preserved. Coordinator reauthenticates and applies keyed fields.'))
P=E/'supporting_sources';P.mkdir(exist_ok=True)
manifest=[]
for name in ['external_source_manifest.json']:
 data=json.loads((Q/'independent_source_review'/name).read_text(encoding='utf-8'))
 for r in data:
  for key in ['path','extracted_text_path']:
   if r.get(key)and(ROOT/r[key]).is_file():
    src=ROOT/r[key];dst=P/src.name;shutil.copy2(src,dst);r[key]=str(dst.relative_to(ROOT)).replace('\\','/');r[key+'_sha256']=sha(dst)
  manifest.append(r)
dump('supporting_sources_manifest.json',manifest)
sources=[dict(id='Buchary1999Table3.1',title='Buchary1999 thesis, Table3.1 PDF58–59/printed49–50 and habitat/size prose PDF55/46',supports='Actual representative taxonomy; habitat first, then average or maximum length<40/40–60/>60cm. Family-level summary, not exhaustive modern membership. Infauna cutoff visually<=1.0mm, accepted stored description retained.',target='papers/BUCHARY-1991/ubc_1999-0254.pdf.pdf#page=58'),dict(id='Buchary1999Table3.9',title='Buchary1999 Table3.9 PDF80/printed71 and catch-assumption prose PDF69–76',supports='Complete printed Harvest, including genuine zeros. Juvenile shrimp and large-demersal juvenile catches are author assumptions; LBS is10×SAF assumed bycatch. Numerical model-catch fractions are Medium composition proxies, not observed stage-mass fractions.',target='papers/BUCHARY-1991/ubc_1999-0254.pdf.pdf#page=80'),dict(id='SAUv50.1',title='Sea Around Us LME38 v50.1 original catch ZIP',supports='181 exact reported labels and original country/sector/catch type/reporting/gear/end-use/year fields. Generic key100039/100139/100239/100339 bony residual scope excludes dedicated cartilage. Provider30/90cm tags differ from source40/60cm rules.',target='raw/LME_038-catch.zip'),dict(id='ClassicSaved',title='LME_038 workbook, protected Classic PPR coefficients and annual outputs',supports='Reference2019 landings, classic taxon TL/coefficient and valid bounds preserved. Simple-chain PPR equals wet coefficient×catch/9 once.39 coefficient-missing taxa have genuine zero2019 catch and zero annual contribution.',target='LME_038.xlsx'),dict(id='ProxyReview',title='Actual historical identified-catch donor and raw-strata review',supports='All eligible non-unidentified direct/stage donors in candidate guilds,1950–2019 total catch, no same-family restriction.16 prior fractions independently reproduced; proxy composition/basis mismatch remains Low.',target='validation_reports/'+MID+'/identified_catch_proxy_review.json'),dict(id='CandidateEvidence',title='Complete candidate and allocation ledger',supports='Every181 label, eligible/excluded groups, source Harvest/biomass, genuine-zero candidates, membership/allocation confidence and exact weights. Zero numerical weights remain in ledger.',target='validation_reports/'+MID+'/candidate_and_allocation_evidence.json'),dict(id='DirectDiagnostics',title='Fresh GE/TE/With Egestion full source matrices',supports='29 loaded groups including synthetic import;29×4source entries each;348 total finite/nonnegative. Saved scoped coefficients match. TE Marine mammals near-zero warning retained.',target='validation_reports/'+MID+'/matrix_inspection.json'),dict(id='Geography',title='Java Sea source bounds and LME overlay',supports='Approximate source prose bounds, two eastern scenarios, 1:50 million coast clipping. A≈19–22%,B≈99–100%; no explicit source polygon; no catch/PPR multiplier.',target='validation_reports/'+MID+'/geography/geographic_assessment.json')]
for m in manifest:
 if m.get('id')and m.get('path'):
  sources.append(dict(id=m['id'],title=m['id'].replace('_',' ').capitalize(),supports=m.get('supports')or m.get('support')or'Primary taxonomy, habitat and size evidence linked to actual selected-source guilds; supports membership interpretation, not observed Java Sea catch-stage proportions.',target=str(Path(m['path']).relative_to(Path('regions/LME_038'))).replace('\\','/')))
dedup={r['id']:r for r in sources};dump('appendix_sources.json',list(dedup.values()))
specific={'Scolopsis':['fao1974_pentapodidae','fao1990_nemipteridae_intro'],'Nemipteridae':['fao1974_pentapodidae','fao1990_nemipteridae_intro'],'Cephalopholis boenak':['fao1993_cephalopholis_species'],'Pomadasys argenteus':['fao1999_haemulidae'],'Megalops cyprinoides':['fao_wcp_megalops'],'Platycephalidae':['fao_pakistan_flatheads'],'Plotosus':['fao_wcp_plotosidae'],'Plotosidae':['fao_wcp_plotosidae'],'Scombroidei':['fao1993_scombroidei_intro']}
dump('taxon_source_links.json',specific)
allowed={Path(r[k]).name for r in manifest for k in ['path','extracted_text_path']if r.get(k)}
for f in P.iterdir():
 if f.is_file()and f.name not in allowed:f.unlink()
print('Authenticated metadata',s['project_sha256'],'sources',len(dedup))
