from pathlib import Path
import json,hashlib,shutil,os
Q=Path(__file__).parent;ROOT=Q.parents[4];MID='38_38003_Java_Sea_normalized_BA_completed_(mid1970s)';R=ROOT/'regions/LME_038';E=R/'validation_reports'/MID
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(n,v):(E/n).write_text(json.dumps(v,ensure_ascii=False,indent=2,allow_nan=False),encoding='utf-8')
review=E/'independent_review';review.mkdir(exist_ok=True)
for f in ['findings.json','primary_source_ledger.json','candidate_ledger.json','verification.json','supporting_sources_manifest.json','delivery_hashes.json']:
 shutil.copy2(Q/'independent_source_review'/f,review/f)
src=R/'models/38_38001_Java_Sea_(mid1970s)/model.json';sel=R/'models'/MID/'model.json';s=json.loads(src.read_text(encoding='utf-8'));d=json.loads(sel.read_text(encoding='utf-8'));dif=[]
for sg,dg in zip(s['group'],d['group']):
 for k in set(sg)|set(dg):
  if sg.get(k)!=dg.get(k):dif.append(dict(seq=sg['group_seq'],field=k,printed_source=sg.get(k),accepted_selected=dg.get(k)))
dump('source_fidelity_review.json',dict(source_pdf_sha256=sha(R/'papers/BUCHARY-1991/ubc_1999-0254.pdf.pdf'),printed_model_sha256=sha(src),selected_model_sha256=sha(sel),groups=28,source_to_selected_group_differences=dif,accepted_interpretation='Macrozoobenthos diet0.660 divided proportionally by0.660; all28 signed computational BA completions persisted. No accepted parameter correction, rebalance or restoration in this review.',locators=['Table3.1 PDF58–59/printed49–50','Table3.9 PDF80/printed71','Table3.10 PDF81/printed72','habitat/size rule PDF55/printed46','GS/BA/detritus and group methods PDF60–79'],source_roundtrip_evidence='../../models/38_38003_Java_Sea_normalized_BA_completed_(mid1970s)/evidence/DERIVED_RELOAD_VALIDATION.json'))
md='''# LME_038 selected Java Sea validation evidence

The regional mapping review is complete and adopted in LME_038.xlsx. All181 exact catch labels are represented, including zero catch; the28 former unresolved labels use explicit functional analogues. This is provisional numerical coverage, not scientific model approval. Shared consolidation and browser alignment belong to the coordinator and remain pending at this regional handoff.

## Source identity and alternatives

The focal source is Eny Anggraini Buchary’s1999 UBC MSc thesis, *Evaluating the effect of the1980 trawl ban in the Java Sea, Indonesia: An ecosystem-based approach*. The user-supplied143-page main PDF is retained at [the original thesis](../../papers/BUCHARY-1991/ubc_1999-0254.pdf.pdf). Its SHA256 is eb2c504f176b230153cfd4caa0fc6671e02c5d1cdc0fd2bc0561d3590759f53d. The1991 folder name is an inherited alias referring to a previous degree year, not publication identity. The EcoBase410 landing link is historical metadata and has not been authenticated as this exact numerical variant. Original native EwE database and an author allocation supplement were not identified in the selected inventory; local source-faithful JSON/imports are reconstructed artifacts, not an author model file. Current possession/reload availability is separate from historical download-attempt counts, which this review leaves unchanged.

The thesis supplies one documented static mid1970s baseline with1974–1976catch context and later Ecosim simulations. A second complete verified static B/PB/QB/EE/diet set was not identified. [Zainuri & Endrawati1999](../../papers/LME038-Zainuri-1999/4895-c62b530d.pdf) covers115ha Awur Bay and12components. [Nurhakim2003](../../papers/LME038-Nurhakim-2003/content-ce43630c.pdf) covers north Central Java,27groups and a1979survey baseline; literal217 diet entry, incomplete/censored diets prevent strict admission. These are geographically and structurally distinct alternatives, not substitute inputs.

## Accepted model and printed-source differences

Exact selected identity:38_38003_Java_Sea_normalized_BA_completed_(mid1970s). Canonical SHA256 db0bc803ea5a068e346b82df8d8b4e4b13f8351bf61103c6507997cb6996ae35 remains unchanged. Printed source model38001 is preserved separately. User-accepted Macrozoobenthos diet0.660→1 proportional normalization and28 signed computational BA completions are retained. BA is a closure calculation, not measured biomass change. Source-specific differences are enumerated in [source fidelity](source_fidelity_review.json); historical cell/source and round-trip evidence remain under the model directories. Current source Table3.1 visibly uses infauna<=1.0mm while stored accepted text says<1.0mm: the discrepancy is disclosed without changing protected accepted wording.

Fresh exact-setting direct diagnostic matrices and biological state are retained under [direct diagnostics](direct_diagnostics/execution_evidence.json). Constructor: underdetermined=True,zero_biomass_accum=False,DC_tol=.001,normalize_DC=True; options GE,TE,With Egestion; det_open_mode=none,det_theta=1,det_external_sppr=0,det_collapse_mode=never. All29recipients×4basal sources per option (348entries) are finite and nonnegative. All source and unfished rows are inspected. Scope sums match saved coefficients within1e-10relative/1e-8absolute tolerance; accepted coefficients were reused. GE rho=.4017728257,b=.2454609189,detritusSPPR=1.3149477189; TE rho=.6212993433,b=0convention,detritusSPPR=.7738986707; Egestion rho=.3214182606,b=.2545349592,detritusSPPR=1.3418324460. TE retains the near-zero Marine mammals transfer-efficiency warning (inverse≈1180.6997) and mortality/recycling interpretation. b=0under TE convention does not prove physical recycling absent. GE/Egestion OK are threshold grades, not scientific applicability approval. Historical diagnostic warnings and failures remain intact; no Monte Carlo expansion occurred.

## Membership and allocation

[All181taxon decisions](taxon_audit.json), [complete candidate/zero-weight ledger](candidate_and_allocation_evidence.json) and [exact changes](adopted_mapping_changes.json) bind the review. Source Table3.1 is a representative Indonesian family/guild summary. PDF55/printed46 prioritizes habitat, then average or maximum length<40/40–60/>60cm. Provider30/90cm bins cannot replace that convention. Froese,Luna&Capuli1996 Indonesian checklist and FishBase1998 are cited by the thesis; their complete historical checklist/CD was not recovered, so exhaustive modern-family membership is not claimed.

Generic bony residual keys100039/100339 retain actual bony members in mixed guilds, with ichthyoplankton5(genuine zero) and source-specific Sphyraenidae8,Caesionidae/Stromateidae21,Rachycentron22 where meaningful. Dedicated rays24 are excluded from bony reporting. Misc. pelagics14contains Mobulidae and large demersals23/26contain sharks/rays alongside actual bony members; their pooled catches/coefficients cannot be separated into bony-only composition. Broad invertebrate labels retain actual larvae, benthos, shrimp and cephalopod homes. Bivalvia/Echinodermata source3/7zeros remain explicit rather than inferring captured adults. Nemipteridae includes historical Pentapodus source8and modern source21; historical Pentapodidae alone does not bridge Scolopsis to SAF. Native FAO evidence supports C.boenak small demersal, Pomadasysargenteus medium-size boundary, tarpon’s55/30cm pelagic alternative and catfish/flathead family size variation. Specific sources are associated in [taxon source links](taxon_source_links.json) and [native source inventory](supporting_sources_manifest.json). Congridae22/23/26is an explicit pike-conger analogy; additional small garden-eel membership is not conclusively resolved. Very low confidence retains that gap without an exhaustive family claim.

Every taxon records membership and allocation separately, with overall confidence the weaker component. Complete source Harvest proportions are Medium allocation assumptions. All28printed values, including genuine zeros, were checked. Juvenile shrimp0.008(PDF71/62)has no actual landing data and is assumed equal to group4. Juvenile large demersals0.066(PDF75/66)are assumed equal to Small demersals, while landed large demersals and pelagics are treated as adults. These reconstruct author-assumed model catch; they are not observed target-age mass fractions. LBS0.100(PDF69/60)equals10×SAF assumed trawl bycatch and supplies71.428571% of the0.140generic-invertebrate allocation. Transfer to modern recorded landings/catch/discards therefore has a material composition and catch-basis mismatch. No compatible measured stage-mass partitions were located in the bounded source/search review; absence is not a claim that no such data exists.

The [actual W5 donor reconstruction](identified_catch_proxy_review.json) reproduces16historical routes. The original builder first assigns direct and source-stage taxa, then pools every identified donor in the candidate guilds over1950–2019total catch; no same-family/genus selector and no recursive coarse-pool donor use.136donor taxa include82stage-weighted rows. Independent reviewer reproduced147158native rows and112stratum dimensions (country/entity,sector,catch type,reporting,gear,end use,year). Retained unchanged-candidate W5 routes remain Low because observed donor catch does not observe residual target composition and strata/bases differ. Candidate corrections use complete printed Harvest rather than an invented donor restriction. Two prior stage-assumption routes changed because of source-containing candidate correction: Dendrobranchiata and residual marine crustaceans; remaining prior stage weights are exact.

## Reference arithmetic and exposure

Reference2019landings across all181labels is2741447.824026478t. Protected simple-chain PPR is177164712.36289582tC: saved wet coefficient×catch/9once.39labels lack classic coefficients, all with genuine zero2019catch and zero annual contribution; TL/coefficient unknowns remain unknown. Historical positive catch without a classic coefficient remains a known subtotal under preserved statuses/bounds. No classic coefficient or researcher setting was repaired. [Coverage summary](coverage_summary.json) uses the entire reference universe; each separate membership/allocation table partitions the same full simple-chain denominator.

Very low36labels contribute30.9942866589%of catch and19.6880097669%of classic PPR. Their model-method dependence is larger:33.3458867564%GE,49.5819263080%TE and32.2014002416%Egestion all-source PPR. Broad marine bony residual alone contributes25.8704210068%GE,30.0682306009%TE,24.8838730580%Egestion; Latescalcarifer analogy contributes18.5807747917%TE. These exposures justify clear scientific limits, not mapping changes chosen to suppress results. [Full method exposure](method_specific_mapping_exposure.json) retains exact year/basis/scope/treatment and contributors.

## Geography and time

PDF29/printed20 gives approximately3°S–6°50′S,105°50′E–116°30′/117°30′E and471000km². Figure2.1/PDF30is bathymetry/context without an explicit study polygon. [Geographic assessment](geography/geographic_assessment.json) reconstructs two prose-bound scenarios with Natural Earth1:50million land removal and WGS84 geodesic areas. R=2267635.6378km². Eastern116.5scenario S=441114.3616,intersection439052.4811,A19.3616855%,B99.5325746%; eastern117.5S=488277.3908,intersection486215.8376,A21.4415327%,B99.5777906%. Report A≈19–22%,B≈99–100%, Low confidence. Reported471000km² remains a separate published quantity; generalized land masks and approximate latitude clipping may truncate coast-following water. Seven included/excluded controls pass but do not establish an exact coast-following study boundary. No spatial multiplier applies to PPR. Fixed mid1970s guild/state and composition proxies across1950–2019full-LME records do not reconstruct annual ecosystem dynamics.

## Review and adoption evidence

Independent source/candidate reviewer /root/qa_source_metadata_display finished on exact audit/candidate/proxy hashes recorded in [findings](independent_review/findings.json) and [proof](independent_review/verification.json), with no demonstrated blocking correction. Root independently reproduced geography; coordinator owns its retained proof and subsequent shared geometry decisions. [Canonical reader verification](canonical_reader_verification.json), [protected input check](coordinator_protected_input_check.json), package/render/link proofs and final hashes are indexed in reports_index.md and coordination_handoff.json. Source/biological validity, scientific approval and shared/browser alignment remain distinct from completed regional review.
'''
# Expand compact inherited numeric prose in new evidence only.
import re
protected={}
def hold(m):
 token=chr(0xE000+len(protected));protected[token]=m.group(0);return token
md=re.sub(r'\]\([^)]*\)|\b[0-9a-f]{64}\b|'+re.escape(MID)+r'|LME_038',hold,md)
md=re.sub(r'(?<=[A-Za-z])(?=\d)',' ',md);md=re.sub(r'(?<=\d)(?=[A-Za-z])',' ',md)
for token,value in protected.items():md=md.replace(token,value)
(E/'source_review.md').write_text(md,encoding='utf-8')
dump('source_search_review.json',dict(date='2026-10-01',queries=['Java Sea1974–1976 barramundi/flathead catch length','WCPFC Indonesia billfish size catch2019','IOTC Indonesia mako/thresher length2019','Java Sea shrimp juvenile catch composition1974–1976','site:open.library.ubc.ca Buchary1999 Evaluating effect1980trawl ban Java Sea'],primary_material_read='Native focal thesis and FAO PDFs listed in supporting_sources_manifest.json; representative IOTC/WCPFC stage-statistical search returns do not establish source-compatible caught-mass partitions.',search_return_urls=['https://iotc.org/sites/default/files/documents/2019/09/IOTC-2019-WPEB15-14_Rev1.pdf','https://iotc.org/sites/default/files/documents/2023/09/IOTC-2023-WPEB19-07_Rev2_-_Data_0.pdf','https://www.wcpfc.int/system/files/YB_2019.pdf'],search_return_access='Search-return evidence only for these three; no claim of fully recovered compatible stage-mass table.',adoption='No observed-stage fractions adopted. Source printed Harvest proxies retained at Medium; exact donor applicability assessed separately.',limits='Bounded search; does not establish exhaustive absence of regional fisheries size data. Historical retrieval metadata was not incremented for searches.'))
print('Source review and independent evidence retained')
