from pathlib import Path
here=Path(__file__).resolve().parent;stage=here/'skill_update'
texts={
'SKILL.md':'\nPreserve all published model fields, including unsupported native fields, using\n[separate published-field companions](references/published-companions.md). Keep\nthe eight EwE import schemas unchanged. Extra source tables belong under\n`companions/`; they are evidence files, not additional EwE imports. The converter\nretains them in JSON and verifies the reconstructed workbook.\n',
'references/output-formats.md':'\n## Additional published fields\n\nThe eight standard formats above are fixed. Preserve every additional published\nmodel field in separate purpose-specific CSV files under `companions/`, following\n[published-companions.md](published-companions.md). Do not append columns to an\nEwE import. The optional extraction JSON `companions` mapping supplies each\nfilename, description and rows. Standard CSV values and all companion rows are\nretained in database JSON and reconstructed with a sheet manifest and exact\nvalue/missing-mask verification. Companion CSVs permit ordinary CSV quoting;\nthey are source evidence, not files with verified EwE import schemas.\n',
'references/workflow.md':'\n## Preserve fields outside the eight import templates\n\nRead [published-companions.md](published-companions.md) whenever source tables\ncontain additional model fields. Inventory every published field, put unsupported\nfields in purpose-specific companion CSVs, and map any computational use\nexplicitly. The standard eight EwE imports keep their exact headers and order.\n`write_outputs.py` retains the extraction JSON and writes companions separately;\n`database_json.py` preserves standard/companion cells and emits\n`SOURCE_FIDELITY_CHECK.json` after reopening the reconstructed workbook. Retain\nthis alongside independent source-cell and standard-JSON-field checks.\n',
'references/diet-source-runtime.md':'\nStore cell statuses, source literals, corrections and variant constraints in\nseparate evidence companion CSVs under the\n[published-companions contract](published-companions.md), keeping the standard\nDiet_composition.csv schema unchanged. A known-cell sum is not a complete sum\nwhen a source/variant component is missing; retain both the subtotal and missing\ncell identities. Reconstruction preserves the missing mask.\n'}
for rel,txt in texts.items():
 p=stage/rel;s=p.read_text(encoding='utf-8');p.write_text(s.rstrip()+'\n'+txt,encoding='utf-8')
project=here.parents[4]/'tools/skills/original_skill_resources/combined-src/references/reconstruction-audit.md'
s=project.read_text(encoding='utf-8');addition='\n## Published fields and EwE compatibility\n\nPreserve every published model field. Keep the eight EwE import CSV/XLSX schemas\nunchanged; place additional stanza, migration, fleet, scenario and provenance\nfields in separate purpose-specific evidence CSVs under `companions/`. Those\ncompanions are not asserted to be directly importable by EwE. The extraction\nskill documents their manifest/schema in `references/published-companions.md`.\nRetain all companion cells in canonical JSON and reconstructed sheets; verify\nsource/import/JSON/workbook values and missing masks. Unsupported calculator\nfields remain retained evidence until an explicit mapping is reviewed.\n'
if '## Published fields and EwE compatibility' not in s:project.write_text(s.rstrip()+'\n'+addition,encoding='utf-8')
print('Skill references staged; active reconstruction-audit contract updated')
