from pathlib import Path
import hashlib,json
h=Path(__file__).resolve().parent;t=Path('C:/Users/idoca/.agents/skills/ecopath-extraction');dest=t/'scripts/source_fidelity.py'
before=hashlib.sha256(dest.read_bytes()).hexdigest();dest.write_bytes((h/'source_fidelity.py').read_bytes());(h/'skill_update/scripts/source_fidelity.py').write_bytes(dest.read_bytes())
r=t/'references/published-companions.md';s=r.read_text(encoding='utf-8')
s=s.replace('Standard import fidelity\nand biological validity','Standard import fidelity\nand biological validity')
s+='\nTable companions require rectangular rows and unique nonempty headers. Use\n`layout: "source_grid"` only for verbatim source tables with merged/multiline\nheaders; ragged source rows are padded with blanks. Safe CSV basenames are\nrequired. Regeneration removes only omitted prior generated companions whose\nhashes still match; manually changed omitted files raise an error.\n\nStandard reconstructed sheets use numeric cells with source-compatible decimal\nformats; source JSON and companions retain literal text. Verification compares\nmissing masks and numerical values (absolute 1e-12 or relative 1e-14 tolerance),\nand reports the largest difference. Input flags describe values supplied to the\nimporter; provide each group\'s `parameter_roles` mapping to mark published\n`model_estimated` or `derived` values as non-input while retaining their numbers.\nPreserve author provenance separately from these importer flags.\n\nThe default database `export` requires known landings plus known discards. An\nexplicit source convention `metadata.export_basis: "reported_landings"` can retain\npublished catch there, with `export_scope` identifying that limited basis and\nunknown total removals kept unknown. Absolute BA in habitat units is scaled by\nknown habitat fraction for the database\'s whole-model-area basis; source literal\nand imports stay unchanged. `metadata.ba_basis: "whole_model_area"` prevents\nscaling already area-standardized absolute BA. Missing area fraction prevents\nan unsupported absolute-area conversion.\n'
r.write_text(s,encoding='utf-8');(h/'skill_update/references/published-companions.md').write_bytes(r.read_bytes())
print('Installed fidelity revision',before,'->',hashlib.sha256(dest.read_bytes()).hexdigest())
