from pathlib import Path
import json,sys,subprocess,os
HERE=Path(__file__).resolve().parent
skill=Path(sys.argv[1]);tag=sys.argv[2]
case=HERE/('skill_regression_'+tag);case.mkdir(exist_ok=True)
m={'metadata':{'LME':'27','model_number':'regression','model_name':'Fidelity','model_year':1991,'biomass_basis':'whole_model_area'},'groups':[{'n':1,'name':'Consumer','biomass':'0.120','z':'0.21','pb':'0','qb':'2.10','ee':'0.657','pq':'0.100','ba_rate':'-0.050','tl':'3.94'},{'n':2,'name':'Producer','biomass':'6.0','pb':'100','ee':'0.40','tl':'1'},{'n':3,'name':'Detritus','biomass':'1','ee':'0.46','tl':'1'}],'consumers':[1],'diet_rows':3,'diet':{'1':{'1':'0','2':'0.980331','3':None,'import':'0'}},'fleets':['Fleet A','Fleet B'],'landings':{'1':{'Fleet A':'0.000','Fleet B':None}},'discards':{},'detritus_groups':['Detritus'],'detritus_fate':{},'companions':{'Source_stanzas.csv':{'description':'Published native stanza fields; evidence only','rows':[['stock','transition_age_months','K','source'],['Consumer','12','','S1']]},'Source_extra.csv':{'description':'Extra published source fields; not EwE import','rows':[['entity','field','value','status'],['1','vulnerability','2.00','published'],['1','unknown_growth','','unknown']]}}}
(case/'input.json').write_text(json.dumps(m),encoding='utf-8')
env=dict(os.environ,PYTHONIOENCODING='utf-8')
for name,args in [('write_outputs.py',[str(case/'input.json'),'--outdir',str(case),'--dir-name','out']),('database_json.py',['-d',str(case/'out')])]:
 r=subprocess.run([sys.executable,str(skill/name)]+args,capture_output=True,text=True,encoding='utf-8',env=env);(case/(name+'.log')).write_text(r.stdout+r.stderr,encoding='utf-8')
out=case/'out';f=next((x for x in out.glob('*.json') if x.name not in ['DIET_SOURCE_SUMS.json','model.json','extraction.json','SOURCE_FIDELITY_CHECK.json']),None)
data=json.loads(f.read_text(encoding='utf-8')) if f else {};g=data.get('group',[{}])[0]
if isinstance((g.get('diet_descr') or {}).get('diet'),dict):g['diet_descr']['diet']=[g['diet_descr']['diet']]
checks={'z_preserved':g.get('z')=='0.21','pq_preserved':g.get('ge')=='0.100','pb_zero_preserved':g.get('pb')=='0','habitat_unknown':g.get('habitat_area')=='-9999','BA_rate_literal':g.get('biomass_accum_rate')=='-0.050','absolute_BA_unknown':g.get('biomass_accum')=='-9999','fleets_zero_vs_unknown':g.get('landings_by_fleet')=={'Fleet A':'0.000','Fleet B':'-9999'},'unknown_discard_total':g.get('discards_total')=='-9999','diet_blank_preserved':any(x.get('prey_seq')=='3' and x.get('proportion')=='-9999' for x in (g.get('diet_descr') or {}).get('diet',[])),'diet_unscaled':any(x.get('prey_seq')=='2' and x.get('proportion')=='0.980331' for x in (g.get('diet_descr') or {}).get('diet',[])),'extra_csv_written':(out/'companions/Source_extra.csv').is_file(),'companions_in_json':bool(data.get('published_companions')),'standard_schema_unchanged':(out/'Basic_input.csv').read_text(encoding='utf-8').splitlines()[0]==',Group name,Hab area (proportion),Biomass in habitat area (t/km^2),Total mortality (/year),Production / biomass (/year),Consumption / biomass (/year),Ecotrophic Efficiency,Other mortality,Production / consumption,Unassim. consumption,Detritus import (t/km^2/year)'}
(case/'result.json').write_text(json.dumps(checks,indent=2),encoding='utf-8');print(json.dumps(checks,indent=2));print('PASS',all(checks.values()))
if tag!='baseline':assert all(checks.values())
