"""Compile bounded independent QA evidence; all writes confined to this folder."""
from pathlib import Path
import hashlib, json, math
from collections import defaultdict

OUT=Path(__file__).resolve().parent;ROOT=OUT.parents[5]
MID='50_502013_Coastal_Kyoto_Inoue_(2013)'
REG=ROOT/'regions/LME_050';REPORT=REG/'validation_reports'/MID
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(n,d):(OUT/n).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
audit=read(REPORT/'taxon_audit.json');byname={r['taxon']:r for r in audit}
numeric=read(OUT/'allocation_vector_verification.json');geo=read(OUT/'geography_verification.json')
native=read(OUT/'native_source_numeric_ledger.json');bridges=read(OUT/'primary_bridge_verification.json')
assert sha(REPORT/'taxon_audit.json')=='b036025a1d457c42235f0819cace172cf8d9dbec46e2f427a59efb784c180598'
assert sha(REPORT/'mapping_changes.json')=='37b59505e058b8697aa94cd76fe0531c9659834f8662de93af7d671dc9a47d1d'
assert numeric['inputs']['regions/LME_050/validation_reports/'+MID+'/taxon_audit.json']==sha(REPORT/'taxon_audit.json')
for q in bridges['queries']:
    assert sha(OUT/q['raw_file'])==q['raw_sha256']
expected_bridges={'Dasyatis akajei':'Hemitrygon akajei','Crassostrea gigas':'Magallana gigas','Sardinops melanostictus':'Sardinops sagax'}
assert all(any(r['scientificname']==q['name'] and r['valid_name']==expected_bridges[q['name']] for r in q['records']) for q in bridges['queries'])

source_identity={
 'main':{'path':'regions/LME_050/papers/SOJ-2023/Inoue_et_al_2023_Sea_of_Japan-eaca3b45.pdf','sha256':native['source_pdf_sha256'],'doi':'https://doi.org/10.1007/s12562-023-01691-9','identity':'Inoue et al.; Fisheries Science89:573–593 (2023), corrected publication2024; local native21-page article. Cold1985 and warm2013 models distinguished.'},
 'supplement':{'path':'regions/LME_050/papers/SOJ-2023/12562_2023_1691_MOESM1_ESM-8d668bb0.docx','sha256':native['source_supplement_sha256'],'identity':'Original local native MOESM1 DOCX; title/authors match main article; S1–S9 body/tables read directly from original XML. Not a reconstructed verification DOCX.'},
 'selected_canonical':{'path':'regions/LME_050/models/'+MID+'/model.json','sha256':'a3b008c0add95db106f9e10cf90907cc7f1f9d2ab1425cbf615745142e27330e','identity':'Accepted40-group2013 model; synthetic diet_import41 belongs to saved runtime and candidate exclusion audit, not a native41st source group.'}}
ledger=[
 {'id':'P01','source':'main','locator':'PDF1/printed573; Table1 PDF5/577 second block, continued PDF6/578','finding':'Article identity, selected warm2013 and all40 final2013 biomass values independently verified from native pages. Prior1985 values are not allocation authority.','retained_evidence':['main_pdf_page5.png','main_pdf_page6.png','native_source_numeric_ledger.json']},
 {'id':'P02','source':'main','locator':'Methods PDF4/printed576, functional-group classification','finding':'Source explicitly assigns pelagic fish/cephalopod groups1–10,14,16,17,19,20,21; Redseabream14 and Seabass16 therefore belong in generic pelagic-bony residual. All21 bony fish pools include bottom29–31; dedicated cartilage11 excluded.','retained_evidence':['native_main_text.txt','candidate_ledger.json','allocation_vector_verification.json']},
 {'id':'P03','source':'supplement','locator':'TableS3 (nativeXML table3); caption Functional group and representative species','finding':'Representative names establish actual members, not exhaustive modern-family inventories. Ray/skate/guitarfish are all cartilage within11; source bony/ceph/benthic/plankton types checked separately. Source Zooplankton38 representative cell is blank.','retained_evidence':['native_supplement_tables.json','native_source_numeric_ledger.json']},
 {'id':'P04','source':'supplement/main','locator':'S3 rows29–30; S7 rows29–30; Table1 PDF6/578; S5 rows29–30','finding':'S3/S7 list Sole29 and Dragonet30, whereas accepted/mainTable1/S5 have Dragonet29 and Tonguesole30. Crosswalk is by actual functional-group name/representatives; no positional transfer of weights or biological inputs. S3Amberjack6 is mainYellowtail6 through Seriola quinqueradiata.','retained_evidence':['native_source_numeric_ledger.json','main_pdf_page6.png']},
 {'id':'P05','source':'supplement','locator':'S4 nativeXML table5, 2013 (following1985 table4), six fleet columns','finding':'All28 supplied2013 group rows have positive sums. Detailed sum3.999627t/km²/year differs from displayed grand total3.999. Stingray11 displays total0.000 but fleets sum0.000005; Ivoryshell23 displays0.000 but dredge0.00001. Detailed values are composition proxies, not edits to accepted catches.','retained_evidence':['native_source_numeric_ledger.json','verify_source_allocations.py']},
 {'id':'P06','source':'supplement/main','locator':'S4 table5 absent groups29–38; S1 selection/sampling prose; mainPDF6/578 recreational-catch paragraph','finding':'Missing group catches are unknown, including non-targeted benthos, not measured zeros. S1 sampling covers2013–2014TangoBay and excludes specimens<5mm; group-dependent beamtrawl catch efficiency30%/100% is assumed. Recreationalcatch omitted. These features limit transfer to complete regional recorded catches.','retained_evidence':['native_supplement_paragraphs.txt','native_source_numeric_ledger.json']},
 {'id':'P07','source':'supplement/main','locator':'S1 Biomass estimation prose, seven depth bins0–240m; TableS1-2 final area size(km2) row; mainMethodsPDF4/576','finding':'Native area cells60,60,100,300,300,250,153 sum1223km². MainMethods separately reports2230km². S1formula identifies Ax depth-bin area and CAK wholemodel area, so denominator/extrapolation consistency is unresolved. No replacement footprint, normalization or parameter correction demonstrated.','retained_evidence':['native_source_numeric_ledger.json','native_supplement_tables.json','native_supplement_paragraphs.txt']},
 {'id':'P08','source':'supplement','locator':'S1 Benthos species selection; S3row38; S5nativeXMLtable6','finding':'Aureliacoerulea/Nemopilemanomurai were collected but expressly excluded because unusable damaged specimens/literaturedata. Jellyfish→Zooplankton38 is a disclosed Verylow analogue, not literal membership. S5asymptoticmass/temperature/caudalaspect/feedingtype values informQB estimates, not observed regional caught-species or stage composition.','retained_evidence':['native_supplement_paragraphs.txt','native_supplement_tables.json','candidate_ledger.json']},
 {'id':'P09','source':'main/supplement','locator':'ResultsPDF13/printed585 Tuna paragraph; S3row8','finding':'MainResults directly identifies Tuna8 as Thunnus orientalis in the1985/2013comparison, supportingM1/High. S3distinctThunnusthynnus remains an unresolved representative-name conflict, not a synonym. Lead implemented confidence-only correction; congeneric taxa and accepted parameters unchanged.','retained_evidence':['main_pdf_page13.png','candidate_ledger.json']},
 {'id':'P10','source':'primaryWoRMS','locator':'Fresh exact-name REST queries, retrieval2026-10-01','finding':'Independent native API bytes verify Dasyatisakajei→Hemitrygonakajei, Crassostreagigas→Magallanagigas and Sardinopsmelanostictus→Sardinopssagax. Source Scomberaustlasicus/Crossostreanippona spelling issues remain editorial/source caveats, not unsupported synonym declarations.','retained_evidence':['primary_bridge_verification.json']},
 {'id':'P11','source':'main/supplement/localreporting','locator':'S3cephalopod22/squids20–21; localCatch exact common names; source S1 jellyfish exclusion','finding':'Exact provider Sepiida is Cuttlefishes,bobtailsquids; adult pelagic bobtails cannot be excluded by a narrowSepia account or confused with unseen paralarvae. Current Sepiida21 analogue discloses broad scope and differs from narrowSepiidae21 rationale. Octopoda22 separately discloses unrepresented pelagic argonauts; benthicOctopus source is not evidence of caught argonaut composition.','retained_evidence':['candidate_ledger.json','allocation_vector_verification.json']},
 {'id':'P12','source':'mainFigure1/coordinatortrace','locator':'Figure1PDF2/574, nativeembedded1500×923JPEG; mainMethodsPDF4/576','finding':'Source dashed240m boundary has an ordered northern bend/loop and coastal/peninsula/island exclusions. Fresh native-byte extraction, independent land-mask reconstruction, savedtrace equality, canonicalLME50↔Project equality, all12controls and WGS84 areas reproduced. Centraltrace1680.955638km² is24.620823% below2230; supplemental1223 remains separate. Inherited134.1–135.5rectangle is unsupported.','retained_evidence':['geography_verification.json','native_trace_controls_independent.png','verify_geography.py']},
 {'id':'P13','source':'main/acceptedruntime','locator':'Table2 caption/methods diet adjustments; regional source_identity/matrix_inspection/loader_version_parity','finding':'One printed diet matrix accompanies both year models despite year-specific diet prose; saved transformations/defaults/completions and WARN/FAIL remain accepted limitations. This bounded review does not rebalance, restorepaper inputs, callSPPR/MC methods or validate full scientific model adequacy.','retained_evidence':['native_main_text.txt']}
]
write('primary_source_ledger.json',{'model_id':MID,'source_identities':source_identity,'ledger':ledger,'availability':'MainPDF and original nativeDOCX bytes available locally and fully read for requestedsource sections. FreshWoRMS RESTbytes available; browserreader could not open the3RESTURLs. No later/unread material represented as read.'})

priority_labels=['Marine fishes not identified','Marine finfishes not identified','Actinopterygii','Marine pelagic fishes not identified','Miscellaneous aquatic invertebrates','Miscellaneous marine crustaceans','Malacostraca','Decapoda','Dendrobranchiata','Penaeidae','Mollusca','Gastropoda','Bivalvia','Cephalopoda','Octopoda','Octopus','Octopodidae','Sepiida','Sepiidae','Gadus chalcogrammus','Gadus macrocephalus','Gadidae','Gadiformes','Lycodes','Oncorhynchus','Oncorhynchus gorbuscha','Salmonidae','Chondrichthyes','Elasmobranchii','Batoidea','Paralithodes','Chionoecetes','Haliotis','Scyphozoa','Cephea','Rhopilema','Clupeidae','Caranx','Thunnus orientalis']
priority=[]
for name in priority_labels:
    if name not in byname:continue
    r=byname[name]
    priority.append({k:r[k] for k in ['taxon','common_name','catch_tonnes','candidate_ids','membership_rule','membership_confidence','allocation_rule','allocation_confidence','overall_confidence','reason']})
write('candidate_ledger.json',{'reviewed_audit_sha256':sha(REPORT/'taxon_audit.json'),'all_253_source_group_partitions_reviewed':True,'complete_independent_numeric_reproduction':'allocation_vector_verification.json','source_partition_basis':'Actual nativeS3 representative taxa reconciled by names, main-method pelagic/demersal/benthic types, retainedprimarytaxonomy and exactprovider reporting scope. Nativeproducer39,detritus40,syntheticimport41 excluded fromcaughtorganism candidates.','priority_cases':priority,'conclusion':'No additional demonstrated blocking source-member omission or allocation contradiction remains after the Thunnus orientalis correction. Weak habitat/taxonomic analogues remain Very low and underdetermined; quantitative reproduction does not make them observed composition.','retained_gaps':['No native gadid, salmon, deep/cold shark or king-crab compartments are documented; Seabass/Rockfish, Yellowtail, Stingray and Pagurus analogues retain major thermal, body-form, family and geography mismatches.','Blank Zooplankton #38 identity cannot establish an exhaustive crustacean, jellyfish or larval inventory. No unsupported literal membership assertion is imposed.','Representative taxonomy/body form may establish a usable analogue; no unique caught-species or age mixture is established for coarse or residual labels.','No focal observed species/stage absolute caught-mass composition was recovered for the 35 split labels; W4/W9 are source-composition assumptions, not fisheries observations for the whole LME.']})

catch_total=sum(x['catch_tonnes'] for x in audit)
catch_by_conf=defaultdict(float)
for x in audit:catch_by_conf[x['overall_confidence']]+=x['catch_tonnes']
catch_exposure=[{'confidence':k,'catch_tonnes':v,'catch_percentage':100*v/catch_total} for k,v in catch_by_conf.items()]
reported=read(REPORT/'method_contribution_exposure.json')
context=[]
for method in reported['methods']:
    assert math.isclose(sum(x['ppr_tC'] for x in method['confidence_contribution']),method['total_tC'],rel_tol=1e-12)
    for x in method['confidence_contribution']:
        assert math.isclose(x['ppr_percentage'],100*x['ppr_tC']/method['total_tC'],abs_tol=1e-10)
    for x in method['top_contributors']:
        assert x['confidence']==byname[x['taxon']]['overall_confidence']
        assert math.isclose(x['catch_t'],byname[x['taxon']]['catch_tonnes'],rel_tol=1e-12)
        assert math.isclose(x['ppr_tC'],x['catch_t']*x['sppr']/9,rel_tol=1e-12)
    context.append({'method':method['method'],'scope':method['scope'],'total_reported_tC':method['total_tC'],'very_low_ppr_percentage':next(x['ppr_percentage'] for x in method['confidence_contribution'] if x['label']=='Very low'),'pollock_top_contribution_percentage':100*next(x['ppr_tC'] for x in method['top_contributors'] if x['taxon']=='Gadus chalcogrammus')/method['total_tC']})
write('verification.json',{'checks':{'native_S4_fleet_and_Table1_allocation_inputs':True,'all_253_exact_labels_and_404_mapping_rows':True,'all_40_native_and_import_candidate_decisions':True,'all_vectors_and_weakest_confidence':True,'all_zero_catch_labels_have_complete_candidate_review':True,'source_S3_order_trap_checked_by_actual_names':True,'fresh_primary_high_confidence_bridges':True,'native_raster_saved_trace_and_12controls':True,'fresh_Project_canonical_target_equality':True,'canonical_model_hash_unchanged':True,'reported_exposure_toprow_and_confidence_arithmetic':True},'max_weight_absolute_error':numeric['maximum_weight_absolute_error'],'confidence_counts':numeric['confidence_counts'],'zero_catch_labels':numeric['zero_catch_labels'],'catch_exposure_2019_landings':catch_exposure,'reported_method_exposure_context':context,'exposure_limit':'Only reported arithmetic and top-row catch/confidence are verified here; scientific coefficients and full matrix diagnostics remain retained lead/root work and were not independently recalculated in this review.','reproduction_commands':["C:/Users/idoca/miniconda3/python.exe -u -Xutf8 -B original_research_archive/research/selected_regions_validation_20260930/work/LME_050/independent_source_review/verify_source_allocations.py","C:/Users/idoca/miniconda3/python.exe -u -Xutf8 -B original_research_archive/research/selected_regions_validation_20260930/work/LME_050/independent_source_review/verify_geography.py","C:/Users/idoca/miniconda3/python.exe -u -Xutf8 -B original_research_archive/research/selected_regions_validation_20260930/work/LME_050/independent_source_review/finish_review.py"],'ownership':'All review writes are confined to independent_source_review. Production, regional accepted inputs, Project, shared code, generated outputs and Git are read-only in this reviewer assignment. No descendants.'})
bound_files=[REPORT/'taxon_audit.json',REPORT/'mapping_changes.json',REPORT/'allocation_provenance.json',REPORT/'source_identity.json',REPORT/'loader_version_parity.json',REPORT/'matrix_inspection.json',REPORT/'method_contribution_exposure.json',REG/'models'/MID/'model.json',REG/'LME_050.xlsx']
identities={str(p.relative_to(ROOT)).replace('\\','/'):sha(p) for p in bound_files}
write('findings.json',{'model_id':MID,'status':'BOUNDED_INDEPENDENT_QA_COMPLETE','reviewer':'/root/region_lme_038; gpt-6.1-sol/xhigh; no descendants','exact_reviewed_production_identities':identities,'resolved_actionable_finding':{'taxon':'Thunnus orientalis','before':'M6/Low with unresolved main/S3 identity conflict','after':'M1/High from exact main Results membership in Tuna #8, 100%; the distinct S3 Thunnus thynnus caveat remains','parameter_changes':False},'material_unresolved_source_findings':[{'id':'S1_AREA','finding':'The seven S1-2 depth-bin areas spanning 0–240 m sum 1223 km²; the main paper reports 2230 km²; the graphical trace measures 1680.955638 km². Keep these distinct; no fitted polygon or accepted parameter correction.'},{'id':'MISSING_CATCH','finding':'Native S4 supplies no catch rows for groups 29–38; loaded zeros are not measured zeros. Complete biomass under W9 is retained whenever candidate catch is absent.'},{'id':'REPRESENTATIVE_COMPOSITION','finding':'Source S3 representatives and local 2013 source catch/biomass do not establish whole-LME caught species, stage or commercial composition. The 143 Very low taxa dominate modeled output.'},{'id':'GEOGRAPHY_SCALE','finding':'The trace is 24.620823% smaller than the main reported area. Low confidence in graphical calibration/land segmentation and source area ambiguity remain. Two anchors per axis and 12 controls support the approximate displayed polygon; no author digital boundary or extrapolation multiplier is established.'}], 'numeric_result':{'labels':253,'mapping_rows':404,'confidence_counts':numeric['confidence_counts'],'allocation_rule_counts':numeric['allocation_rule_counts'],'max_weight_error':numeric['maximum_weight_absolute_error']},'geography_result':{'native_raster_hash':geo['inputs']['original_research_archive/research/selected_regions_validation_20260930/work/LME_050/coordinator_geography/Figure1_native.jpg'],'fresh_Project_sha256':geo['fresh_Project_snapshot_sha256'],'central_area_km2':geo['central_trace_area_km2'],'A_percent':geo['scenarios'][1]['A_percent'],'B_percent':geo['scenarios'][1]['B_percent'],'all12controls':True,'canonical_target_equals_Project':True,'demonstrated_defect':None},'remaining_demonstrated_blocking_corrections':[],'limits':['No full SPPR method rerun or Monte Carlo expansion; saved warnings, FAIL, defaults, diet ambiguity and finite provisional status remain.','Independent arithmetic verification does not approve weak analogues as observed composition or whole-LME representativeness.','No production edits, Git actions, shared writer or scientific approval claim. The regional lead/root retain adoption and integration ownership.'],'handoff':['primary_source_ledger.json','candidate_ledger.json','native_source_numeric_ledger.json','allocation_vector_verification.json','primary_bridge_verification.json','geography_verification.json','verification.json']})
(OUT/'README.md').write_text('Independent LME 050 review is complete on the exact final audit and mapping hashes in findings.json. The accepted canonical model remains a3b008c0add95db106f9e10cf90907cc7f1f9d2ab1425cbf615745142e27330e.\n\nAll 253 labels, 404 mapping rows, complete source-group partitions, native fleet/biomass vectors and weakest confidence reproduce. The native Figure 1 bytes, independent mask reconstruction, WGS84 areas, canonical target / fresh Project equality and all 12 water/land controls reproduce.\n\nThe source depth-bin sum 1223 km², reported main area 2230 km² and graphical trace 1680.955638 km² remain distinct unresolved quantities. Native missing catch rows remain unknown; source-model catch and biomass splits remain assumptions. Thunnus orientalis now has direct main-text membership at High while the conflicting supplement T. thynnus stays disclosed.\n\nRead findings.json and primary_source_ledger.json for locators, candidate_ledger.json for priority interpretations, verification.json for commands, and delivery_hashes.json for retained bytes. Scripts only write within this directory; production and Git were read-only. This is bounded evidence review, not scientific approval or a whole-LME validation claim.\n',encoding='utf-8')
manifest={p.name:sha(p) for p in sorted(OUT.iterdir()) if p.is_file() and p.name!='delivery_hashes.json'}
write('delivery_hashes.json',{'production_reviewed_identities':identities,'files':manifest})
print(json.dumps({'findings_sha256':sha(OUT/'findings.json'),'verification_sha256':sha(OUT/'verification.json'),'primary_ledger_sha256':sha(OUT/'primary_source_ledger.json'),'manifest_sha256':sha(OUT/'delivery_hashes.json'),'very_low_catch_percent':next(x['catch_percentage'] for x in catch_exposure if x['confidence']=='Very low'),'exposure_context':context}))
