import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const out=path.dirname(fileURLToPath(import.meta.url));
const region=path.resolve(out,'../..');
const audit=JSON.parse(await fs.readFile(path.join(out,'adopted_taxon_audit.json'),'utf8'));
const summary=JSON.parse(await fs.readFile(path.join(out,'coverage_summary.json'),'utf8'));
const sources=JSON.parse(await fs.readFile(path.join(out,'appendix_sources.json'),'utf8'));
const rows=[...audit].sort((a,b)=>((b.simple_chain_ppr_tC??-Infinity)-(a.simple_chain_ppr_tC??-Infinity))||a.taxon.localeCompare(b.taxon,'en'));
const wb=Workbook.create();
const sheet=wb.worksheets.add('Taxon mappings');sheet.showGridLines=false;
sheet.getRange('A1:G4').format.font={name:'Arial',size:10};
sheet.getRange('A1').values=[['Mediterranean Sea taxon mapping appendix']];sheet.getRange('A1').format.font={name:'Arial',size:14,bold:true};
sheet.getRange('A2:G2').merge();sheet.getRange('A2').values=[['2019 landings. Independent simple trophic chain. Catch tonnes and PPR tonnes C. All 522 exact catch labels.']];
sheet.getRange('A3:G3').merge();sheet.getRange('A3').values=[['Descending unrounded simple-chain PPR, taxon name for ties. ? means unavailable. Zero recorded catch contributes zero PPR.']];
sheet.getRange('A4:G4').merge();sheet.getRange('A4').values=[[`Total catch ${summary.total_catch_tonnes.toLocaleString('en-US',{maximumFractionDigits:3})} t. Total PPR ${summary.total_simple_chain_ppr_tC.toLocaleString('en-US',{maximumFractionDigits:3})} t C. Model GE/TE coefficients remain unavailable.`]];
sheet.getRange('A2:G4').format.wrapText=true;sheet.getRange('A2:G4').format.rowHeight=28;
const headers=['Taxon name','TL','Catch (t)','Simple-chain PPR (t C)','Mapped group names and weights','Confidence level','Reason'];
sheet.getRange('A6:G6').values=[headers];
const values=rows.map(r=>[r.taxon,r.tl??'?',r.catch_tonnes??'?',r.simple_chain_ppr_tC??'?',r.groups.length?r.groups.map(g=>`${g.group_name} (${(100*g.weight).toFixed(6)}%)`).join('; '):'Unresolved',r.overall_confidence,r.appendix_reason]);
sheet.getRange(`A7:G${6+rows.length}`).values=values;
sheet.getRange(`A6:G${6+rows.length}`).format.font={name:'Arial',size:10};
sheet.getRange(`A6:G${6+rows.length}`).format.verticalAlignment='top';
sheet.getRange(`A7:G${6+rows.length}`).format.wrapText=true;
sheet.getRange('A6:G6').format={fill:'#174C58',font:{name:'Arial',size:10,bold:true,color:'#FFFFFF'},wrapText:true,rowHeight:34};
sheet.getRange(`B7:D${6+rows.length}`).setNumberFormat('#,##0.000000');
const widths=[28,8,17,23,70,16,88];widths.forEach((v,i)=>sheet.getRange(`${String.fromCharCode(65+i)}6:${String.fromCharCode(65+i)}${6+rows.length}`).format.columnWidth=v);
for(let i=0;i<values.length;i++){
 const lines=Math.max(...values[i].map((v,j)=>String(v).split('\n').reduce((n,t)=>n+Math.max(1,Math.ceil(t.length/(widths[j]-3))),0)));
 sheet.getRange(`A${i+7}:G${i+7}`).format.rowHeight=Math.max(45,lines*14+12);
}
const table=sheet.tables.add(`A6:G${6+rows.length}`,true,'MediterraneanTaxonMappings');table.showFilterButton=true;
sheet.freezePanes.freezeRows(6);sheet.freezePanes.freezeColumns(1);
const ss=wb.worksheets.add('Sources');ss.showGridLines=false;
ss.getRange('A1').values=[['Sources for the Mediterranean mapping review']];ss.getRange('A1').format.font={name:'Arial',size:14,bold:true};
ss.getRange('A2:E2').merge();ss.getRange('A2').values=[['Source locators support membership, allocation proxies and the independent classic-PPR calculation. Retrieval date 30 September 2026.']];
ss.getRange('A2:E2').format.wrapText=true;ss.getRange('A2:E2').format.rowHeight=34;
ss.getRange('A4:E4').values=[['Source ID','Descriptive reference','Supports and limitations','Locator','Open source']];
ss.getRange(`A5:E${4+sources.length}`).values=sources.map(s=>[s.id,s.title,s.supports,s.locator,'Open source']);
ss.getRange(`A4:E${4+sources.length}`).format.font={name:'Arial',size:10};ss.getRange(`A4:E${4+sources.length}`).format.wrapText=true;ss.getRange(`A4:E${4+sources.length}`).format.verticalAlignment='top';
ss.getRange(`E5:E${4+sources.length}`).format.font={name:'Arial',size:10,color:'#0563C1'};
ss.getRange('A4:E4').format={fill:'#174C58',font:{name:'Arial',size:10,bold:true,color:'#FFFFFF'},wrapText:true,rowHeight:32};
const sw=[18,62,96,55,19];sw.forEach((v,i)=>ss.getRange(`${String.fromCharCode(65+i)}4:${String.fromCharCode(65+i)}${4+sources.length}`).format.columnWidth=v);
sources.forEach((s,i)=>{const text=[s.id,s.title,s.supports,s.locator,'Open source'];const lines=Math.max(...text.map((v,j)=>Math.ceil(v.length/(sw[j]-3))));ss.getRange(`A${i+5}:E${i+5}`).format.rowHeight=Math.max(58,lines*14+10);});
ss.tables.add(`A4:E${4+sources.length}`,true,'MediterraneanMappingSources').showFilterButton=true;ss.freezePanes.freezeRows(4);
wb.recalculate();
const output=await SpreadsheetFile.exportXlsx(wb);await output.save(path.join(region,'LME026_taxon_mapping_appendix.xlsx'));
const check=await wb.inspect({kind:'table',range:'Taxon mappings!A6:G10',include:'values,formulas',tableMaxRows:5,tableMaxCols:7,maxChars:1800});
await fs.writeFile(path.join(out,'qa/appendix_inspection.ndjson'),check.ndjson);
const previews=[['Taxon mappings','A1:G11','appendix_top'],['Taxon mappings','A250:G256','appendix_middle'],['Taxon mappings',`A${rows.length}:G${rows.length+6}`,'appendix_bottom'],['Sources','A1:E11','sources_top'],['Sources',`A12:E${4+sources.length}`,'sources_bottom']];
for(const [sn,range,n] of previews){const blob=await wb.render({sheetName:sn,range,scale:1.2,format:'png'});await fs.writeFile(path.join(out,`qa/${n}.png`),new Uint8Array(await blob.arrayBuffer()));}
const longest=values.map((v,i)=>({i,len:v[4].length+v[6].length})).sort((a,b)=>b.len-a.len)[0];
const lb=await wb.render({sheetName:'Taxon mappings',range:`A${longest.i+7}:G${longest.i+9}`,scale:1.2,format:'png'});await fs.writeFile(path.join(out,'qa/appendix_longest.png'),new Uint8Array(await lb.arrayBuffer()));
console.log(JSON.stringify({rows:rows.length,sources:sources.length,output:'LME026_taxon_mapping_appendix.xlsx'}));
