"""Reconcile preserved classic arithmetic, retain access evidence and regional QA."""
import sys,json,copy,math,shutil,os,re,zipfile
from pathlib import Path
Q=Path(__file__).resolve().parent;OUT=Q.parent;REG=OUT.parents[1];ROOT=REG.parents[1];MID=OUT.name
sys.path.insert(0,str(ROOT/'tools'));from workbooks import *
from regional import recalculate
BASE=ROOT/'original_research_archive/research/selected_regions_validation_20260930/baseline/EEZ_598'
a=json.loads((OUT/'taxon_audit.json').read_text(encoding='utf-8'));b=read_book(REG/'EEZ_598.xlsx');old=read_book(BASE/'EEZ_598.xlsx')
tmp=copy.deepcopy(b);recalculate(tmp,REG/'EEZ_598.xlsx')
keys=['model_id','scope','method','catch_basis','unidentified','metric'];key=lambda r:tuple(r.get(k) or None for k in keys)
new={key(r):r for r in records(tmp,'Classic PPR','Annual')};diff=[];removed=[]
for r in records(old,'Classic PPR','Annual'):
 if key(r) not in new:removed.append(r);continue
 for y in YEARS:
  x,z=r[y],new[key(r)][y]
  if x!=z:diff.append({'key':dict(zip(keys,key(r))),'year':y,'accepted':x,'fresh_arithmetic':z,'absolute_difference':abs(x-z) if finite(x) and finite(z) else None})
mx=max((x['absolute_difference'] or 0 for x in diff),default=0)
assert mx<1e-5
proof={'classic_annual_preserved_exactly':b['Classic PPR']['Annual']==old['Classic PPR']['Annual'],'protected_checks':a['protected_checks'],'fresh_dependent_recalculation_differences':diff,'max_arithmetic_absolute_difference_wet_tonnes':mx,'retained_historical_rows':removed,'reference_simple_chain_tC':a['simple_chain_ppr_tC'],'why_preserved':'Catch, Classic Taxa and NPP are unchanged. Classic benchmark is independent of Ecopath mappings. Recalculation discards historical fixed-TL min/max placeholders and changes only floating summation tails of valid classic values. Baseline Classic Annual and empty-model-id classic ratios remain exact; all selected-model dependent rows use adopted mappings. Historical size-impact table is explicitly renamed historical 20260929; it is not a new uncertainty estimate.'}
assert proof['classic_annual_preserved_exactly']
(OUT/'classic_preservation_verification.json').write_text(json.dumps(proof,indent=2,ensure_ascii=False),encoding='utf-8')
archive=ROOT/'original_research_archive/research/size_allocation_20260929/pacific'
for src,dst in [('online_search_audit.json','20260929_search_audit.json'),('online_source_hashes.json','20260929_source_hashes.json')]:shutil.copy2(archive/src,OUT/'online'/dst)
search={'date':'2026-09-30','unit_id':'EEZ_598','purpose':'Regional stage composition and independent primary taxonomy/ecology review','queries':['site.wcpfc.int Papua New Guinea 2020 annual report 2019 tuna length frequency size catch','site.spc.int Papua New Guinea 2019 catch length 43 120 124 tuna'],'sources':[{'url':'https://meetings.wcpfc.int/file/7705/download','material':'Papua New Guinea2020 WCPFC annual report; locally retained PDF and extracted text independently reviewed','retrieval':'Full retained PDF/text; primary web PDF reopened','applicability':'2019 fisheries reporting but vessel-size categories, observer/port coverage and flag-fleet totals do not provide all-fleet PNG-EEZ caught-mass shares at43/120/124cm','decision':'Reject as measured allocation weights; retain bounded search evidence'},{'url':'https://www.wcpfc.int/sustainability/scientific-data','material':'Current scientific-data public page; full page retrieved','applicability':'Public fish-length data are described, without recovered taxon/year/EEZ/fleet/caught-mass denominators at source thresholds','decision':'Useful acquisition lead, no adopted numeric shares'},{'url':'https://meetings.wcpfc.int/meetings/sc08?order=field_doc_issue_date&sort=desc','material':'Search snippet names2012ST-IP-06 Decomposition of Tuna Length Frequency Data from Port Sampling in Papua New Guinea; direct listing returned internal error','retrieval':'Snippet only; listing inaccessible','applicability':'Historical port sample lead; not recovered2019 all-fleet EEZ caught-mass shares','decision':'No numeric allocation adopted; no absence-of-data inference'},{'url':'https://www.spc.int/updates/blog/2019/09/help-us-to-find-out-how-tuna-age-and-how-fast-they-grow-and-win-usd-100','material':'Search snippet about2019 tagging','retrieval':'Search snippet only','applicability':'Tagging/fish-growth study; no total caught-mass stage denominator','decision':'Not used for weights'},{'url':'https://www.wcpfc.int/sites/default/files/2025-11/Yearbook_2025.pdf','material':'Search excerpt of PNG longline totals by species/year','retrieval':'Search excerpt only; no claim of full PDF read','applicability':'Flag-fleet/species totals do not supply residual-family composition or exact stage shares','decision':'Not used for regional proportions'}], 'independent_taxonomy_ecology_sources':a['sources'],'allocation_decision':'No applicable observed regional caught-mass weights recovered. Complete source model catches, then complete biological biomass, supply explicit Medium composition assumptions; separate membership confidence can be weaker. Accepted infantSKJ uncaught exception remains explicit. This bounded search does not establish that data do not exist.'}
(OUT/'online/20260930_search_audit.json').write_text(json.dumps(search,indent=2,ensure_ascii=False),encoding='utf-8')
visual={'date':'2026-09-30','docx_pages':6,'all_pages_inspected':True,'docx_images':['report_page_'+str(i)+'.png' for i in range(1,7)],'docx_findings':'All six pages readable; table headers repeat, manual rows/placeholders unchanged, no clipped table cells or overlapping objects. Source and geographic images readable; relative link styling visible.','xlsx_sheets':['Taxon mapping','Sources'],'xlsx_rendered_ranges':['Taxon mapping A1:G9','A10:G18','A19:G27','A46:G54','A73:G81','A100:G108','A109:G109','Sources A1:D7','A8:D14','A15:D21','A22:D24'],'xlsx_findings':'Representative high-PPR, long reasons, broad family, weak/unresolved and zero-catch rows plus all Sources ranges readable; typed numbers, group weights, wraps and confidence fills readable without overflow. Filters/frozen headers verified separately.','preferred_renderer':'Failed: LibreOffice soffice.exe missing from PATH','fallback':'New owned hidden Word COM instance opened generated DOCX read-only, exported PDF, closed document and its own instance; scientific Python PyMuPDF rasterized pages. User instances not accessed.'}
(Q/'visual_qa.json').write_text(json.dumps(visual,indent=2),encoding='utf-8')
(Q/'packaged_renderer.log').write_text('2026-09-30 render_docx.py attempted with bundled Python. FileNotFoundError: LibreOffice soffice.exe was not found on PATH. Generated document was then exported read-only through the separately owned hidden Word instance in word_export.ps1.\n',encoding='utf-8')
# Read-only review of current source metadata, with exact Project freshness.
snapshot=ROOT/'original_research_archive/research/selected_regions_validation_20260930/central_source_metadata_current.json';sm=json.loads(snapshot.read_text(encoding='utf-8'));current_sha=sha(ROOT/'Project.xlsx')
if sm['project_sha256']==current_sha:tables=sm['tables'];origin='hash-authenticated coordinator metadata snapshot'
else:
 pb=read_book(ROOT/'Project.xlsx');tables={'Models & coverage':records(pb,'Models & coverage','Models'),'Papers':records(pb,'Papers','Papers')};origin='fresh read_book of current Project.xlsx; cached snapshot rejected on SHA mismatch'
models=[r for r in tables['Models & coverage'] if r.get('unit_id')=='EEZ_598'];papers=[r for r in tables['Papers'] if r.get('unit_id')=='EEZ_598']
assert any(r.get('model_id')==MID and r.get('selected') for r in models)
(OUT/'central_metadata_review.json').write_text(json.dumps({'project_sha256':current_sha,'origin':origin,'models':models,'papers':papers},indent=2,ensure_ascii=False),encoding='utf-8')
print('CLASSIC PRESERVED',proof['classic_annual_preserved_exactly'],'max tail wet tonnes',mx,'historical rows',len(removed),'metadata',origin)
