"""Prepare central changes for the parent; does not write Project.xlsx."""
from extract_candidates import *
review='regions/LME_022/models/extraction_review_20260928'
models=[]
for folder,mid,period,variant,area,coverage,paper,year,doi in [
 ('22_20251890_East_Coast_of_Scotland_(1890-1895)','22_20251890_East_Coast_of_Scotland_(1890-1895)','1890–1895','Published historical ECS model',None,'subregional','NS-2025__LME_022',2025,'10.3389/fmars.2025.1646031'),
 ('22_20251990_East_Coast_of_Scotland_(1991-1995)','22_20251990_East_Coast_of_Scotland_(1991-1995)','1991–1995','Published modern ECS model',None,'subregional','NS-2025__LME_022',2025,'10.3389/fmars.2025.1646031'),
 ('22_20071991_North_Sea_report_Table_3.3_(1991)','22_20071991_North_Sea_report_Table_3.3_(1991)','1991','Printed balanced Table 3.3 with printed Table 3.4 diets; source defects retained',570000,'intended_full','LME022-Mackinson-2007__LME_022',2007,None),
 ('457_457_North_Sea_(1991)','457_457_North_Sea_(1991)','1991–1992 (registry); 1991 (local filename)','EcoBase accession 457 numerical repository variant; not identical to report tables',570000,'intended_full','LME022-Mackinson-2007__LME_022',2007,None)]:
  note=('East-coast Scotland shelf fishing grounds, including Orkney/Shetland; subset of North Sea. No verified author polygon/area ratio. Inherited paper 0.1 coverage ratio is not newly validated.' if area is None else 'Report domain ICES IV, approximately 570000 km2. Whole North Sea spatial intent; exact LME overlap ratio not established from a digital author boundary.')
  models.append(dict(unit_id='LME_022',model_id=mid,model_path=f'regions/LME_022/models/{folder}/model.json',source_filename=mid+'.json',selected=False,selection_rationale=None,paper_ids=paper,model_year=1890 if '1890' in period else 1991,variant=variant,model_area_km2=area,availability='Extracted candidate; bounded SPPR evidence retained; not selected. See candidate report for strict source admission versus transformed computation.',publication_year=year,model_years=period,target_coverage_ratio=None,coverage_class=coverage,doi=doi,coverage_note=note,atlas_region_rank=11))
papers=[
 {'article_id':'NS-2025__LME_022','changes':{'functional_groups':25,'model_years':'1890–1895 and 1991–1995','extraction_readiness':'Two source-faithful parameter/diet/fleet/taxonomy extractions completed; unknown BA and GS remain source unknowns.','model_file_status':'Two local extracted JSON candidates and complete import tables; source diet rounding preserved.','full_model_loadable':'Engine load tested with normalization/defaults/unknown-flow completion; native EwE application import not tested.','loadability_evidence':f'{review}/EXTRACTION_AND_SPPR_REPORT.md; both candidate diagnostics isolated from production. Strict diet admission passes; TE diagnostics fail in both candidates.','notes':'Extraction 2026-09-28: two 25-group models preserved separately. No model selection. Table S2 describes main species rather than exhaustive group membership. Supplement workbook contains four tables plus one methods DOCX; not four separately archived files.','coverage_note':'East-coast Scotland subregional shelf model. Inherited 0.1 target coverage is not validated by this extraction; no area fraction inferred from bounding box.'}},
 {'article_id':'LME022-Mackinson-2007__LME_022','changes':{'functional_groups':68,'model_years':'1991 (printed model); 1991–1992 (EcoBase457 registry); 1973 version mentioned, complete inputs unavailable','extraction_readiness':'Printed model extracted without correcting severe diet/PQ conflicts; EcoBase457 separately archived and diagnosed as a numerical variant.','model_file_status':'Source-faithful printed JSON plus separate EcoBase457 candidate; no complete 1973 static model located.','full_model_loadable':'Printed source fails strict diet admission; wrapper computes only after normalization/completion. EcoBase457 passes strict diet admission; native EwE import not tested.','loadability_evidence':f'{review}/EXTRACTION_AND_SPPR_REPORT.md; paper versus repository comparison and per-candidate diagnostic workbooks retained.','notes':'USER-PREFERRED SOURCE (2026-09-28): user considers spatial fit better and documentation very detailed. Exact model choice remains pending. This preference is distinct from numerical validity. Printed model has 19 consumer diet sums outside ±0.01 and gelatinous zooplankton PB/QB conflict. EcoBase457 is a distinct numerical repository variant, not equivalent printed extraction. EcoBase628 advertises a 1973 model but currently exposes zero groups/fleets; no parameters invented.','coverage_note':'ICES IV North Sea model, approximately 570000 km2 in report. Basin-scale intent independently supported; exact polygon overlap with LME022 not established.','correction_notes':'Extraction uses final balanced Table3.3 (printed27–28), not initial Table3.1. Report requested citation2007, copyright2008. Severe printed diet and gelatinous QB inconsistencies retained, not repaired.'}}
]
preferred='22_20251990_East_Coast_of_Scotland_(1991-1995)'
preference_note=f'USER-PREFERRED MODEL (explicit user instruction, 2026-09-28): {preferred}; user rationale: "least SPPR failures". GE and WithEgestion diagnostics are OK; TE remains FAIL. Candidate preference only: production Overview and computed results are not adopted. Earlier Mackinson/Daskalov paper preference is retained as history and superseded by this exact-model preference.'
debug_note='LATER DEBUGGING REQUESTED (explicit user instruction, 2026-09-28): 457_457_North_Sea_(1991), why did the flow-balancing test fail? Independent source mass balance passes, but standard engine input/flow checks fail. Discards group68 stored P=0.2981897135 versus recomputed P=-99.7018102865; original JSON supplies detritus_import=100 and immigration=100. Relative overall balance gaps: GE2.9109828, TE0.12447885, WithEgestion2.8741747. Cause remains unresolved; source representation, loader handling and computation have not been disentangled. No debugging experiment or source/engine repair performed in this update.'
for row in models:
 if row['model_id']==preferred:row['availability']+=' '+preference_note
 if row['model_id']=='457_457_North_Sea_(1991)':row['availability']+=' '+debug_note
papers[0]['changes']['notes']+=' '+preference_note
papers[0]['changes']['recommendation']=preference_note
papers[1]['changes']['notes']='HISTORICAL SOURCE PREFERENCE (earlier on 2026-09-28): '+papers[1]['changes']['notes']+' LATEST USER INSTRUCTION: '+preference_note+' '+debug_note
papers[1]['changes']['recommendation']='Earlier paper preference retained as history; current exact-model preference is '+preferred+'. EcoBase457 is flagged for later debugging, not adopted.'
dump(OUT/'central_metadata_proposal.json',{'unit_id':'LME_022','status':'PROPOSED; parent coordination required before any shared workbook write','preserve':['All other rows/cells, including ranks, scores and user edits','Existing paper selected flags and regional Overview unchanged','No catch matching, annual PPR/PPR-NPP or HTML refresh'],'paper_updates':papers,'model_rows_to_register':models,'unavailable_model':{'accession':628,'nominal_period':1973,'reason':'Report mentions fitted 1973 version; no complete static tables/native file located; live EcoBase record has zero groups and fleets. Not an extracted model and not assigned invented JSON.'}})
print(OUT/'central_metadata_proposal.json')
