"""Render extraction and exact-run findings; no model/selection mutations."""
from extract_candidates import *
MIDS=['22_20251890_East_Coast_of_Scotland_(1890-1895)','22_20251990_East_Coast_of_Scotland_(1991-1995)','22_20071991_North_Sea_report_Table_3.3_(1991)','457_457_North_Sea_(1991)']
def readable(s):
    s=re.sub(r'\b(Table|PDF|group|accession|QB|PB|P/Q|EE|GS|BA|Both|both|with|than|of|to|version|model|Published|at|within|from|using|approximately|requests|request|uses|biomass|remains|as|and|value|unavailable|Unavailable|doi)(?=\d)',r'\1 ',s)
    s=re.sub(r'(?<=[A-Za-z]),(?=\d)',', ',s)
    s=re.sub(r':(?=\d)',': ',s)
    for a,b in [('TableS','Table S'),('groups/fleets','groups/fleets'),('570000km','570000 km'),('before0','before 0'),('from1','from 1'),('by more than0','by more than 0'),('mean0','mean 0'),('input100','input 100'),('import100','import 100'),('immigration100','immigration 100'),('all100','all 100'),('of the1890','of the 1890'),('its20','its 20'),('with107','with 107'),('records205','records 205'),('version and','version and')]:s=s.replace(a,b)
    return s
intro='''# LME022 extraction and SPPR assessment — 28 September 2026

Four candidate JSONs are now available from the two requested sources: two published East-coast Scotland period models, the printed 1991 North Sea model, and a separately attributed EcoBase457 numerical variant of the latter. **User preference recorded on 28 September 2026:** `22_20251990_East_Coast_of_Scotland_(1991-1995)`, with the user's rationale, "least SPPR failures". GE and WithEgestion are OK; TE remains FAIL. This records candidate preference, not production adoption or scientific validity across all configurations. The earlier preference for the Mackinson/Daskalov paper, based on perceived spatial fit and documentation detail, is retained as history and superseded by this exact-model preference. Production Overview remains unselected.

**Later debugging requested by the user on 28 September 2026:** `457_457_North_Sea_(1991)` failed standard engine input/flow checks despite passing independent source mass balance. Discards group 68 has stored P=0.2981897135 versus recomputed P=-99.7018102865; the original source has detritus_import=100 and immigration=100. GE, TE and WithEgestion overall relative balance gaps are 2.9109828, 0.12447885 and 2.8741747. Cause remains unresolved: source representation, loader handling and computation have not been disentangled. The model is flagged for later review. No debugging experiments, source repairs or engine changes were performed for this preference update.

The North Sea report independently supports a basin-scale ICES IV domain of approximately 570,000 km². The Saygu models describe East-coast Scotland shelf fishing grounds, including Orkney/Shetland, within the North Sea. No defensible overlap percentage was calculated from a bounding box; the inherited central paper value0.1 has not been validated. Source presence, spatial suitability, numerical validity and model adoption are distinct.

## Source preservation and interpretation

Source PDFs, XLSX/DOCX supplements, the original repository JSON and retrieved EcoBase records remain under `regions/LME_022/papers/`. The source manifest hashes their bytes. Each paper extraction includes all eight required import artifacts, source JSON, taxonomy, coordinate/page evidence, mass-balance findings and a database round-trip workbook. Source B, PB, QB, EE, GS and explicit diet entries were compared to canonical JSON; source catches were compared to JSON export totals. Group taxonomy preserves source spelling and the scope of principal-species lists; it is not an exhaustive modern nomenclature reconciliation.

The legacy converter silently normalizes diets. Its compatibility output is retained separately, and the canonical JSON was restored to exact published diet proportions, with every changed cell recorded. Both Saygu matrices have small rounding deviations; the report has large inconsistencies. The canonical import tables and JSON are not repaired models. Converter conventions (blank habitat=1, blank diet/import/catch represented as0) are explicitly distinguished from original blanks. Published final B/PB/QB/EE values include Ecopath estimates rather than four independent inputs; no new source-supported values were inferred. Numeric biomass accumulation is unreported for all groups in each paper extraction and remains unknown. Any loader-derived value appears only in diagnostic outputs and `LOADER_TRANSFORMATIONS.csv`.

The calculation engine loads with `normalize_DC=True`, `DC_tol=0.001`, `underdetermined=True`, `zero_biomass_accum=False`. Consequently, wrapper results are **conditional computational diagnostics after loader normalization/defaults/flow completion**, not validation of a fully source-specified model. In particular, the printed North Sea input fails strict source diet admission and cannot be accepted merely because the loader computes numbers. Missing fate fractions can become external export in this representation; this is not source evidence of export.

## Exact diagnostic configuration

Each candidate was run through the existing regional SPPR wrapper using a fresh isolated candidate workbook in its own model directory. The live LME022 workbook was not selected or cleared. Runs request22 methods (20 deterministic,2 Monte Carlo), with180 seconds per method/health row and100 samples for MC. Health uses `det_collapse_mode=never`, `det_external_sppr=0`, `det_open_mode=none`, `det_theta=1`; theta is inert for this closed configuration. MC uses10% uncertainty,20% cut, and excludes divergent draws. Monte Carlo realizations are not seeded here and are retained exactly; earlier converter-normalized Saygu realizations are separately archived and are not the current results. A timeout is computational unavailability, never zero, and does not itself prove scientific failure. Health status applies to its exact configuration; an algorithm returning finite values does not establish scientific admissibility. Negative-group screening includes unfished groups.

No production catch matching, annual regional PPR, PPR–NPP comparison or map rebuild was performed. Model-internal footprint numbers in the diagnostic exports are not regional annual results. Continue the integration pipeline only after the user chooses an exact model and any material source/engine issues are resolved or explicitly scoped.
'''
details={
MIDS[0]:'''Published1890–1895 East-coast Scotland model:25 groups,23 consumers,1 phytoplankton and1 detritus group. Parameters: paper Table1/PDF6; diets: supplementary TableS3; three-fleet landings: TableS1; taxonomy: TableS2. Methods DOCX was inspected. GS, BA, detritus routing/import and habitat shares are not numerically documented. Discards are explicitly excluded by the paper. Printed seal biomass0.00 remains0.00; it was not replaced with an inferred small positive biomass. Source validation:0 errors,27 warnings; source mass-balance check BALANCED with0 errors,0 indeterminate and3 endotherm P/Q warnings, conditional on its treatment of unknowns. This does not certify exact source completeness. GE/WithEgestion WARN involve the zero-biomass/EE historical seal case. TE diverges and has negative Seabirds SPPR despite zero catch.''',
MIDS[1]:'''Published1991–1995 East-coast Scotland model:25 groups, same topology and source locations as the1890–1895 version. Period-specific parameters and landings are retained separately. Source validation:0 errors,27 warnings; source mass balance INDETERMINATE,0 errors,2 indeterminate groups (Turbot and Ling),3 endotherm P/Q warnings. Unknown BA could reconcile the discrepancy, but no checker-suggested BA was inserted. GE/WithEgestion are OK for the completed engine model; TE still diverges with negative unfished Seabirds. These results do not remove the source BA uncertainty.''',
MIDS[2]:'''Printed1991 model:68 groups (64 consumers,1 phytoplankton,3 detritus pools), final balanced Table3.3 printed27–28/PDF29–30, diets Table3.4 printed29–40/PDF31–42. Bracketed initial estimates are preserved as evidence and not substituted for the final table. Table3.5 eight-fleet landings and unallocated total discards were converted from tonnes using570000km². Dashes remain unknown. Summary catches differ from detailed12-fleet Tables14.7/14.8; both are retained separately, not silently mixed. Prose documents only limited fate routing (PP30% DOM/70% POM; DOM→POM; POM→export); the remaining source fate fractions stay unknown. Taxonomy combines the report's group descriptions with107 principal benthic contributors from Table11.8, not an exhaustive census.

**Severe printed-source defects:**19 consumer diet sums differ from1 by more than0.01;33 exceed the engine0.001 admission tolerance. Examples: juvenile Cod0.562, juvenile Saithe0.403, adult Saithe1.530, Hake1.539, Blue whiting0.387 and Large crabs1.468. Continuation-page values appear repeated in some columns; source coordinates and page images preserve the evidence. The Import row is included (adult Whiting includes0.324). Gelatinous zooplankton PB2.858 and QB0.18 imply P/Q15.8778, as actually printed; the prose separately claims P/Q0.45. None was repaired. Strict raw diet admission FAILS. Import validation records19 errors/67 warnings. Source mass balance is NOT BALANCED:1 error,19 indeterminate,4 warnings, including nonpositive gelatinous respiration. Loader normalization/completion yields low identity residuals but does not cure this source failure. All three main health configurations FAIL; GE and TE diverge, and WithEgestion fails overall flow balance. Many negative SPPR values remain, including unfished groups.''',
MIDS[3]:'''EcoBase accession457:68 groups, registry period1991–1992 and local archive filename1991. The live record explicitly cites the Mackinson/Daskalov technical report. The original JSON bytes are archived; every original numerical field was preserved, with source-based taxonomy attached by group_seq only. It is a separate repository numerical variant, not an interchangeable paper extraction: the parameter comparison records205 unequal fields including precision, BA unknown→0, catches and substantial changes (e.g. gelatinous QB6.35111141 instead of printed0.18). The database export aggregates catch and does not preserve the12-fleet ledger. Its JSON-only route is retained with a reconstructed workbook; original repository bytes remain the authority.

Strict source diet admission PASS; independent source mass-balance checker BALANCED with0 errors/0 indeterminate and4 endotherm warnings. Nevertheless, all standard engine configurations FAIL. A fresh independent engine load reproduces the worst identity residual at Discards group68: stored production0.2981897135 versus recomputed−99.7018102865. The source supplies both detritus_import100 and immigration100, unchanged; the engine's handling of this detritus/migration representation requires investigation. Do not describe this alone as proof that the repository living food web is grossly unbalanced. Separate overall balance gaps remain substantial. No negative aggregate group SPPR occurs in completed methods, but convergence/nonnegativity does not make the diagnostic model valid. Both MC methods and both EwE path methods timed out; six symbolic methods failed. No source or engine repair was attempted.'''
}
sections=[];compact=[]
for mid in MIDS:
    dest=REG/'models'/mid;d=json.loads((dest/'SPPR_DIAGNOSTICS.json').read_text(encoding='utf8'));a=json.loads((dest/'EXTRACTION_AUDIT.json').read_text(encoding='utf8'))
    h=['| Configuration | Status | Living spectral radius | Relative flow-balance gap |','|---|---|---:|---:|']
    for r in d['health']:h.append(f"| {r['TE_option']} | {r['status']} | {r.get('divergence_rho_living',float('nan')):.8g} | {r.get('balance_rel_gap',float('nan')):.8g} |")
    mc=[]
    for r in d['mc']:mc.append(f"{r['method']}: {r['n_accepted']}/{r['n_samples']} accepted; {r['n_rejected_diverged']} divergent rejections and {r['n_rejected_negative']} negative rejections (not necessarily additive).")
    if not mc:mc=['Both100-sample Monte Carlo methods timed out at180 seconds; acceptance/rejection counts are unavailable.']
    negative=[]
    for k,v in d['negative_group_totals_all_scope'].items():negative.append(f"{k}: {len(v)} negative aggregate groups, including {sum(r['catch']==0 for r in v)} unfished groups; minimum SPPR {min(r['sppr'] for r in v):.10g}.")
    if not negative:negative=['No negative aggregate group SPPR in completed methods; unavailable methods were not treated as passing.']
    unavailable=[f"{r['topic'].removeprefix('method: ')}: {r['status']}" for r in d['run_notes'] if r['status'] not in [None,'ok']]
    audits='; '.join(a['checks'])+f". Round-trip basic/diet cells independently verified: {a.get('roundtrip_core_and_diet_cells_verified','JSON-only repository route; reconstruction retained')}."
    text='\n\n'.join([f'## {mid}',details[mid],'\n'.join(h),' '.join(mc),' '.join(negative),'Unavailable methods: '+('; '.join(unavailable) or 'none')+'.',audits,'Evidence: `model.json`, `source_provenance.json`, `EXTRACTION_AUDIT.json`, `SPPR_DIAGNOSTICS.json`, `sppr_source.xlsx`, `candidate_diagnostics.xlsx`, `loaded_groups.csv`, `LOADER_TRANSFORMATIONS.csv`, executed-code snapshot/hashes and run log in this candidate folder. Canonical model SHA256: '+d['model_json_sha256']+'.'])
    if mid==MIDS[1]:text+='\n\nUser preference (explicit instruction, 2026-09-28): this exact model is preferred because it has the "least SPPR failures". GE and WithEgestion are OK, but TE remains FAIL. This does not change production Overview or adopt computed results.'
    if mid==MIDS[3]:text+='\n\nUser-requested deferred review (2026-09-28): investigate why this model fails flow balancing despite passing the independent source check. The verified Discards/import/migration discrepancy above is evidence, not an established cause. No debugging experiment or repair was performed in this preference update.'
    text=readable(text);sections.append(text)
    et=dest/'extracted_tables';report=et/'REPORT.md' if et.exists() else dest/'REPORT.md';report.write_text(text+'\n\nNo production model selected. Exact diagnostic configurations and source/loader distinctions are described in the extraction-set report.\n',encoding='utf8')
    compact.append({'candidate':mid,'health':{r['TE_option']:r['status'] for r in d['health']},'negative_counts':{k:len(v) for k,v in d['negative_group_totals_all_scope'].items()},'mc':d['mc'],'unavailable':unavailable})
tail='''## Unavailable1973 version and sources

The report discusses a fitted1973 model. No complete separate static parameter/diet/fishery set was found in the requested source bundle. EcoBase628 advertises a1973 model but its retrieved record exposes zero groups/fleets. It is documented as unavailable, not reconstructed from1991 values and not counted among the four extracted candidates.

- Saygu et al. (2025), doi10.3389/fmars.2025.1646031: https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2025.1646031/full
- Mackinson and Daskalov (requested citation2007; copyright2008), Cefas Technical Report142: https://www.cefas.co.uk/publications/techrep/tech142.pdf
- EcoBase457 and628 records: archived HTML and retrieval hashes in the report paper folder. The457 record gives the source linkage and numerical-variant identity; the628 record supports the present availability limitation.

Central metadata changes are defined in `central_metadata_proposal.json`, coordinated by the parent task; `CENTRAL_REGISTRATION_VERIFICATION.json` records application and preservation checks. The exact model preference and deferred EcoBase457 review are now recorded. Existing regional selection/results and prior validation evidence are preserved. Production execution remains pending further instruction.
'''
(OUT/'EXTRACTION_AND_SPPR_REPORT.md').write_text(readable(intro+'\n\n'+'\n\n'.join(sections)+'\n\n'+tail),encoding='utf8')
dump(OUT/'FINAL_COMPACT_RESULTS.json',compact)
print('Reports written for four candidates.')
