"""Summarize retained extraction and SPPR evidence; no numerical rerun."""
from pathlib import Path
import json,hashlib
import openpyxl
ROOT=next(p for p in Path(__file__).resolve().parents if (p/'Project.xlsx').exists());OUT=Path(__file__).parent;REG=ROOT/'regions/LME_038';bid='38_38001_Java_Sea_(mid1970s)';nid='38_38002_North_Coast_Central_Java_(1979)'
b=REG/'models'/bid;n=REG/'models'/nid
d=json.loads((b/'evidence/sppr_diagnostic_audit.json').read_text(encoding='utf8'));flows=json.loads((b/'evidence/loader_completed_flows.json').read_text(encoding='utf8'))['rows'];w=openpyxl.load_workbook(b/'sppr_source.xlsx',read_only=True,data_only=True);rr=list(w['groups_df'].values);gr=[dict(zip(rr[0],r)) for r in rr[1:]]
near=[]
for r in gr:
 if r['group_type']=='Regular':
  te=(r['p']/r['q'])*(1-r['M0']/r['p'])
  if 0<abs(te)<.001:near.append({'seq':r['seq'],'group_name':r['group_name'],'P':r['p'],'Q':r['q'],'M0':r['M0'],'GE':r['ge'],'EE':r['ee'],'TE':te,'inverse_TE':1/te})
assert len(near)==1 and near[0]['seq']==27
negba=[r for r in flows if r['biomass_accum'] is not None and r['biomass_accum']<0];detba=next(r['biomass_accum'] for r in flows if r['group_type']=='DET')
result={'unit_id':'LME_038','created_from':'Existing final retained run only; no SPPR rerun','registration':'Existing INDO-1999 paper reconciled to supplied thesis; Nurhakim updated; both numeric candidates unselected','models':[{'model_id':bid,'source_publication_year':1999,'model_period':'mid-1970s','groups':28,'taxonomy_documented':28,'source_admission':'FAIL: Macrozoobenthos diet0.660; no missing0.340 inserted','source_balance':'Source massbalance0 errors/1 warning; converter BALANCED within tolerance but28/28 BA unknown; cannot override diet failure','loader_transformations':{'Macrozoobenthos_diet_normalization_factor':1/.66,'BA_source_unknown_count':28,'negative_solved_BA_count':len(negba),'negative_solved_BA':negba,'detritus_solved_BA':detba,'limitation':'Signed completion reconciles budgets; small residuals may reflect rounding. Neither negative nor positive BA is a source-supported ecological trend. A causal attribution of all BA differences to diet normalization was not tested.'},'configurations':d['health'],'TE_warning_group_confirmed_from_saved_rates':near,'method_status':d['method_status'],'negative_scoped_group_coefficients':d['negative_scoped_group_coefficients_all_groups'],'negative_source_counts_three_configs':d['negative_source_counts_for_three_health_configs'],'negative_source_limit':d['negative_source_limit'],'mc':d['mc'],'settings':d['settings'],'spatial':'Java Sea approx471000 km2; subregional; no verified LME coverage fraction','canonical_sha256':hashlib.sha256((b/'model.json').read_bytes()).hexdigest(),'eligibility':'Isolated loader-transformed diagnostic only; not source-valid or adopted'},{'model_id':nid,'source_publication_year':2003,'model_period':'1979; diet caption mid-1970s','groups':27,'taxonomy_documented':27,'source_admission':'FAIL: literal217 prey22/predator25, subtotal217.78; adult shrimp0.28; SAF0.87;29 censored diets and censored producerEE','source_validation':{'import_errors':4,'import_warnings':29,'source_massbalance_errors':3,'source_massbalance_warnings':14,'canonical_massbalance_indeterminate_groups':11,'BA_missing':27,'GS_missing':27,'detritus_fate_missing':27},'SPPR_status':'NOT RUN: unsupported printed source; no repaired comparison variant requested','configurations':None,'spectral_radii':None,'source_contribution_signs':None,'method_outcomes':'All22 downstream methods NOT RUN, not failed/timed out or zero','mc':{'status':'NOT RUN','n_samples':None,'accepted':None,'rejected':None},'spatial':'North coast Central Java1979 survey; area and LME fraction unknown','canonical_sha256':hashlib.sha256((n/'model.json').read_bytes()).hexdigest(),'eligibility':'Archived later-test candidate only; authoritative correction needed'}]}
(OUT/'SPPR_RESULTS_SUMMARY.json').write_text(json.dumps(result,indent=2,ensure_ascii=False),encoding='utf8')
lines=['# LME038 extraction and full SPPR diagnostic report - 28 September 2026','',
'Two source-faithful candidates are archived and registered unselected. Buchary is the user-preferred spatial candidate; Nurhakim is retained only for later tests. Neither passes strict admission as printed. The Buchary run below is a loader-transformed diagnostic; Nurhakim downstream tests were not run. No production regional selection, catch matching, annual PPR, PPR/NPP or map publication changed.','',
'## Source identity, geography and missingness','',
'The BUCHARY-1991 folder contains Eny Anggraini Buchary’s April1999 UBC MSc thesis, *Evaluating the effect of the 1980 trawl ban in the Java Sea, Indonesia: An ecosystem-based approach*.1991 is the earlier degree year. The existing INDO-1999 catalog placeholder is reconciled to this supplied thesis using author/year/place and its explicit thesis-recovery note; it had no source PDF/hash or verified full citation. This bibliographic association is documented as an inference. Its old title and EcoBase410 URL are preserved as history; numerical equivalence to EcoBase410 remains unverified. The legacy36% bbox estimate was cleared from active coverage, not reused. Details: IDENTITY_AND_PATH_RECONCILIATION.json.','',
'Buchary: one28-group mid-1970s static baseline (2 producers,25 consumers,1 detritus), Java Sea approximately471000 km² (PDF29/printed20); no verified LME intersection fraction. Later Ecosim trajectories are not distinct printed Ecopath parameter sets. All28 taxonomy descriptions captured from Table3.1; source spellings and stage distinctions retained. BA is unknown28/28. GS is source-stated0.2 for consumers except small/large herbivorous zooplankton0.4; basal3 groups remain blank. Single-pool detritus fate1 is explicitly stated. Discards are not independently quantified; the aggregate harvest includes an assumed LBS bycatch proxy. No modern synonym reconciliation or regional catch assignment performed.','',
'Nurhakim2003: one27-group1979 north-coast Central Java survey baseline (2 producers,24 consumers,1 detritus); diet caption refers to mid-1970s. Model area and LME fraction unknown. All27 taxonomy descriptions captured; no separate Medium demersals group. BA, GS and numeric detritus fate remain missing for27/27;29 diet entries and producer EE are censored, with bounds retained. Printed GE is ambiguous/inconsistent with PB/QB and was not imported as PQ.','',
'## '+bid+' - source admission and loader transformations','',
'Strict source admission **FAILS**: Macrozoobenthos predator9 sums0.660. The source detritus cell is a dash, not0.340. The other24 consumer diets sum1.000. Required-import validation has1 error/2 warnings. The source-table mass-balance check has0 errors/1 endotherm warning, and the canonical converter check says BALANCED at its tolerance (maximum EE difference0.019 at Demersal rays). These limited balance results do not establish a complete diet or known BA. Canonical JSON preserves printed proportions and all unknown BA values.','',
f'The loader normalizes that consumer diet by **1/0.660 = {1/.66:.15g}** and completes underdetermined flows. It adds a zero-catch Import bookkeeping row, distinct from the28 biological groups. It recomputes trophic information and solves28 unknown BA values;17 are negative, while detritus BA is **{detba:.15g} t/km²/year**. These completions reconcile the loaded budgets. Several negative values are tiny rounding-sized residuals; others are material. None is a demonstrated ecological biomass decline/gain, and no experiment isolated diet normalization as the sole cause of the17 values.','',
'## Exact configuration health from the saved run','',
'| Configuration | Status | Living spectral radius | Detritus recycling gain b | Relative flow gap | Max P residual | Max Q residual | Negative basal source columns |','|---|---|---:|---:|---:|---:|---:|---:|']
for h in d['health']:lines.append(f"| {h['TE_option']} | {h['status']} | {h['divergence_rho_living']:.12g} | {h['divergence_b']:.12g} | {h['balance_rel_gap']:.12g} | {h['model_input_p_max_rel_residual']:.12g} | {h['model_input_q_max_rel_residual']:.12g} | {h['divergence_n_negative_sources']} |")
r=near[0];lines+=['',f"All three use det_collapse_mode=never, det_open_mode=none, det_theta=1 and det_external_sppr=0; no explicit sampled TE matrix for the health rows. GE/egestion use the single-detritus route. TE **WARN** is confirmed at **group27 Marine mammals** using retained rates and the engine formula TE=(P/Q)(1−M0/P): P={r['P']}, Q={r['Q']}, M0={r['M0']}, GE={r['GE']:.15g}, EE={r['EE']:.15g}, TE={r['TE']:.15g}, inverseTE={r['inverse_TE']:.15g}. It is the only regular group below the near-zero threshold0.001. The network spectral radius is below1, so this warning is not network divergence. Saved TE diagnostic has2 warnings and1 near-singular group. Near-zero TE can amplify SPPR; marine-mammal total SPPR is269815.0941253361 under TE versus20954.80161516027 under GE. These are candidate coefficients, not adopted regional results.",'',
'## All22 method outcomes','', '| Method | Outcome |','|---|---|']
for r in d['method_status']:lines.append(f"| {r['topic'].removeprefix('method: ')} | {r['status']} |")
lines+=['','All22 computations returned; no unavailable, failed or timed-out method. This computational success does not override source admission failure. SPPR_1986 and SPPR_1995 scalar variants have no source-resolved PP decomposition; their PP-only cells remain unavailable rather than zero. All28 biological groups, including6 with zero catch (the health count7 also includes the artificial Import row), were retained in sign checks. No negative scoped group coefficient appears in all/inner/PP among available values. GE, TE and With Egestion each report0 basal source columns containing negatives. Per-source matrices for the other methods were not retained by the exporter; no blanket claim about those unretained contributions is made.','',
'## Monte Carlo and bounded-run settings','',
'Each method/health row had a180-second limit via tools/run_region.py. The two Monte Carlo configurations used100 draws,10% TE error,20% cutoff, kind=new, exclude_diverged=True; TE additionally fixes EE=0 cases. No seed was explicitly fixed; these are the retained realization, summarized without a rerun.','',
'| Method | Draws | Accepted | Rejected negative | Rejected diverged |','|---|---:|---:|---:|---:|']
for r in d['mc']:lines.append(f"| {r['method']} | {r['n_samples']} | {r['n_accepted']} | {r['n_rejected_negative']} | {r['n_rejected_diverged']} |")
lines+=['','## Every negative loader-solved BA','', '| Group | Solved BA (t/km²/year) |','|---|---:|']
for r in negba:lines.append(f"| {r['seq']} {r['group_name']} | {r['biomass_accum']:.15g} |")
lines+=['','These are solved bookkeeping quantities; source BA remains missing. Complete signed flows, including positive BA and detritus completion, are in the candidate evidence/loader_completed_flows.json.','',
'## '+nid+' - blocked numerical diagnostics','',
'Strict source admission **FAILS**. Table3 visually prints217 at prey22/predator25, giving a217.78 diet subtotal. Adult-shrimp subtotal0.28 plus two<0.01 entries cannot close to1; SAF0.87 plus one<0.01 likewise cannot close.29 censored diet cells include one>0.01. Producer EE is also censored. Bounds remain recorded; neither217→0.217 nor predecessor fractions were substituted. Required imports:4 errors/29 warnings. Source mass-balance:3 errors/14 warnings; recomputed EE exceeds1 for Rastrelliger1.039, juvenile large demersals110.103 and marine mammals2.722. Canonical converter check labels11 groups indeterminate because BA is unknown; that is not numerical validity.','',
'**All22 SPPR methods, configuration health, spectral radii, flow-balance tests on an engine-loaded model, source sign tests and Monte Carlo are NOT RUN.** There are no accepted/rejected draws or calculated zero counts to report. The source is scientifically unsupported without authoritative corrected data. No later comparison experiment performed merely to complete this report. Source extraction, all27 taxonomy records and canonical/reconstructed numeric round trips are archived for future review.','',
'## Provenance and eligibility','',
'Original source bytes/hashes are preserved; folder alignment to exact engine IDs did not change either canonical JSON. Each candidate retains extracted_tables/REPORT.md, all eight imports, Taxonomy.xlsx, reconstructed workbook, evidence/source_manifest.json, source_cells.csv, censored_values.json, roundtrip_validation.json and page renders/coordinates. Converter-normalized intermediates remain separate from canonical source-faithful JSON. Compatibility round trips may display unknown diet cells as zeros; canonical source evidence/bounds are authoritative.','',
f'Buchary canonical SHA256: `{result["models"][0]["canonical_sha256"]}`. Its sppr_source.xlsx, isolated candidate_diagnostics.xlsx, final run log, executed-code snapshot/hashes and detailed diagnostic/flow audits preserve the numerical run. Nurhakim canonical SHA256: `{result["models"][1]["canonical_sha256"]}`. It has no SPPR run.','',
'Central registration is recorded in CENTRAL_REGISTRATION_VERIFICATION.json; the existing INDO-1999 and Nurhakim paper records were updated and both unselected models added. Native tables/filter controls, other-region preferences/results, and existing ranks/scores were preserved. No updater or map rebuild ran. Compact machine-readable results: SPPR_RESULTS_SUMMARY.json. Neither candidate is production-eligible as printed; source preference does not constitute adoption.']
(OUT/'EXTRACTION_AND_SPPR_REPORT.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
print('EXTRACTION_AND_SPPR_REPORT.md and SPPR_RESULTS_SUMMARY.json saved; existing run only')
