from pathlib import Path
import json,csv,hashlib
from openpyxl import load_workbook
ROOT=next(p for p in Path(__file__).resolve().parents if (p/'Project.xlsx').exists());REG=ROOT/'regions/LME_038'
def save(p,x):p.write_text(json.dumps(x,indent=2,ensure_ascii=False),encoding='utf8')
def records(w,s):
 rr=list(w[s].values);return [dict(zip(rr[0],r)) for r in rr[1:]]
bmid='38_38001_Java_Sea_(mid1970s)';nmid='38_38002_North_Coast_Central_Java_(1979)'
for mid in [bmid,nmid]:
 dest=REG/'models'/mid;et=dest/'extracted_tables';ev=dest/'evidence';raw=json.loads((dest/'extraction.json').read_text(encoding='utf8'));can=json.loads((dest/'model.json').read_text(encoding='utf8'));w=load_workbook(next(et.glob('*reconstructed.xlsx')),read_only=True,data_only=True)
 basic=records(w,'Basic input');diet=list(w['Diet composition'].values);tax=records(w,'Taxonomy');check=[]
 for g,row in zip(raw['groups'],basic):
  assert g['name']==row['Group name'] and g['n']==row['Group seq']
  for key,col in [('biomass','Biomass in habitat area (t/km^2)'),('pb','Production / biomass (/year)'),('qb','Consumption / biomass (/year)'),('ee','Ecotrophic Efficiency'),('unassim','Unassim. consumption')]:
   expected=g.get(key);assert (row[col] is None if expected is None else float(row[col])==float(expected)),(g['n'],key,row[col],expected)
 for pred,dd in raw['diet'].items():
  col=diet[0].index(pred)
  for prey,val in dd.items():assert float(diet[int(prey)][col])==float(val)
 for g,t in zip(can['group'],tax):assert g['group_name']==t['Group name'] and g['taxon_descr']==t['Taxon Description']
 save(ev/'roundtrip_validation.json',{'groups':len(basic),'taxonomy_rows':len(tax),'canonical_JSON_to_source':'pass; exact printed numeric values retained','reconstructed_workbook_basic_inputs':'pass','reconstructed_workbook_printed_diet_values':'pass','reconstructed_taxonomy':'pass','limitations':'Reconstructed workbook represents absent/censored diet cells as zero; canonical source_cells and censored_values retain missing/bounds. Reconstructed workbook is not the source-faithful import artifact. Canonical numeric JSON omits censored diets and retains bounds in source_audit; do not run Nurhakim.'})
 if mid==bmid:
  sw=load_workbook(dest/'sppr_source.xlsx',read_only=True,data_only=True);health=records(sw,'model_health');mc=records(sw,'mc_diagnostics');notes=records(sw,'run_notes');neg=[]
  for s in ['sppr_all','sppr_inner','sppr_PP']:
   rows=list(sw[s].values)
   for r in rows[1:]:
    for j,v in enumerate(r[2:],2):
     if isinstance(v,(int,float)) and v<0:neg.append({'scope':s,'seq':r[0],'group':r[1],'method':rows[0][j],'sppr':v})
  methods=[r for r in notes if str(r['topic']).startswith('method:')]
  diag={'interpretation':'UNSELECTED LOADER-TRANSFORMED DIAGNOSTICS ONLY. Strict source admission fails. Macrozoobenthos diet normalized from0.660; engine also completes flows and recomputes TL/EE.','settings':{'wrapper':'tools/run_region.py --region candidate_diagnostics.xlsx --stage sppr --timeout 180','timeout_per_method_seconds':180,'MC_samples_per_method':100,'TE_error_percent':10,'TE_error_cut_percent':20,'exclude_diverged':True,'seed':'not explicitly fixed; fresh realization','comparison_experiments_run':False},'health':health,'mc':mc,'method_status':methods,'negative_scoped_group_coefficients_all_groups':neg,'negative_source_counts_for_three_health_configs':{r['TE_option']:r['divergence_n_negative_sources'] for r in health},'negative_source_limit':'The exporter retains per-source health counts only for GE, TE, With Egestion; it does not export per-source matrices of every other method. No blanket per-source claim is made for untested configurations.'}
  save(ev/'sppr_diagnostic_audit.json',diag)
  # Prove taxonomy propagated through the final isolated run.
  all_sr=records(sw,'groups_df');sr=[r for r in all_sr if r['group_type']!='Import'];gkey=next(k for k in sr[0] if k in ['group_name','name']);tkey='taxon_descr';assert len(sr)==28
  assert {r[gkey]:r[tkey] for r in sr}=={g['group_name']:g['taxon_descr'] for g in can['group']}
  save(ev/'diagnostic_taxonomy_check.json',{'groups':28,'all_taxon_descr_match_canonical':True})
  save(ev/'loader_completed_flows.json',{'note':'All baseline source BA values are unknown. Engine-completed values below are diagnostic assumptions/solutions, never source data or canonical repairs. Artificial Import group is excluded from biological count.','rows':[{k:r.get(k) for k in ['seq','group_name','group_type','biomass_accum','emigration','immigration','net_migration','M0','flow_to_det','respiration']} for r in sr]})

B='''# Java Sea, mid-1970s - Buchary (1999)

Source: Eny Anggraini Buchary. 1999. Evaluating the effect of the 1980 trawl ban in the Java Sea, Indonesia: An ecosystem-based approach. MSc thesis, University of British Columbia, April 1999. Supplied folder BUCHARY-1991 is a label;1991 is the earlier degree date, not this thesis publication or model year.

Model ID:38_38001_Java_Sea_(mid1970s). Project-local identifier38001 is not an EcoBase accession.28 groups:2 producers,25 consumers,1 detritus; one aggregate Harvest column. One static Ecopath baseline is printed. Later Ecosim time trajectories and management scenarios do not supply independent complete Ecopath parameter sets.

## Spatial and selection evidence
Thesis PDF29/printed20 describes the Java Sea domain, approximately471,000 km2, bounded roughly3 S to6 degrees50 minutes S and105 degrees50 minutes E to116 degrees30 minutes-117 degrees30 minutes E. Source figures1.1/2.1 define its setting. This is a subregion of Indonesian Sea LME38, not verified full-LME coverage. No target coverage percentage calculated. Existing INDO-1999 catalog's36% and EcoBase410 link are unverified legacy claims and are not inherited here. User prefers this spatial candidate because alternatives have inadequate fit; this preference is separate from source coverage and model validity. No exact model is selected.

## Source tables and extraction
Table3.9 PDF80/printed71 was visually transcribed after a90-degree render rotation: Group,B,P/B,Q/B,EE,GE,Harvest,flow to detritus,TL,omnivory,R/A,R/B. B and harvest are t/km2 and t/km2/year; annual PB/QB. GE maps to P/Q (checked against PB/QB). Parentheses mean Ecopath estimated outputs; exact markers remain in source_cells.csv. Table3.10 PDF81/printed72 contains28 prey rows and25 predator columns3-27. Manual transcription from rotated200dpi render; nonzero values retained to printed3 decimals. Original OCR/text coordinates are archived but were not trusted for the rotated numeric table. All biological groups including unfished groups are retained.

Taxonomy:Table3.1 PDF58-59/printed49-50 gives membership for all28 groups. Exact source group names from Table3.9 key the import files and Taxonomy.xlsx. Group22 is Medium demersals, distinct from the juvenile large demersal group23. Source family/species spellings retained, not synonym-resolved or mapped to regional catch.

## Prose, biomass accumulation and conventions
PDF60/printed51 states unassimilated food0.2 unless otherwise specified. PDF65/printed56 states0.4 for both small and large herbivorous zooplankton. PDF61/printed52 explicitly sends detritus produced by all groups to the single detritus pool, so detritus fate1 is source-supported. Source detritus biomass120 comes from the Brunei model. BA was swept throughout thesis, methods and results; no group-specific numeric BA for this baseline was identified, and BA remains blank/-9999. Dynamic Ecosim trajectories are not substituted for baseline BA.

Harvest is the printed aggregate, not a fabricated fleet split. Table4.1 contains gear allocation for dynamic simulations and is archived as evidence only. LBS harvest0.100 is an assumed bycatch proxy10 times SAF landing (PDF68-69/printed59-60), although the thesis calls it landing; no independent discard total is given. Discards stay blank. Habitat area absent in imports; converter uses1 as representation convention. Diet import0 is writer/converter convention (no reported external diet fraction). Primary-producer/detritus GS blank; no invented rate. Missing BA is never repaired with balance suggestions.

## Source defect and strict admission
Macrozoobenthos predator9 diet sums0.660. The detritus28 cell is visibly a dash in Table3.10; no0.340 value is printed. Caption claims every column sums1, but24 other consumer columns actually do sum1 and this one does not. Prose PDF67/printed58 identifies inherited diet sources but gives no numeric correction. No missing fraction inserted and no canonical diet normalization. This is a severe source omission, not3-decimal rounding. Required import validation:1 error,2 warnings (unknown BA; basal GS blank).

Source-table mass balance script:0 errors,1 warning (marine-mammal PQ approximately0.003). Source-faithful converter balance verdict BALANCED within its tolerance, but BA remains unknown28/28. A balance-only pass cannot validate an incomplete diet; strict source admission FAILS. The normalized converter intermediate is retained separately and every restored diet cell logged. Canonical model.json and reconstructed workbook were checked against source numbers and all28 taxonomy rows.

## Isolated SPPR diagnostic
candidate_diagnostics.xlsx is fresh and contains no production catch or matching. Live LME_038.xlsx was never changed. The bounded wrapper ran22 methods with180-second per-method limit; settings, method statuses, negative coefficients and MC counts are in evidence/sppr_diagnostic_audit.json. The loader normalizes Macrozoobenthos0.660 to1 and completes flows/recomputes group metrics. Consequently its healthy/balanced labels describe a transformed diagnostic, not the printed model. GE and With Egestion health were OK; TE WARN for a near-singular transfer efficiency. Both MC configurations used100 draws,10% error with20% cutoff and excluded divergence; exact final accepted/rejected counts in audit. All28 groups, including unfished, were scanned for negative scoped coefficients; per-source health checked the three named configurations. Scalar methods have no invented PP decomposition. No later comparative tests, catch matching, annual regional PPR, NPP ratio or production publication performed.
'''
N='''# North coast of Central Java,1979 - Nurhakim (2003)

Source:Subhat Nurhakim.2003. Marine Fisheries Resources of the North Coast of Central Java, Indonesia: An Ecosystem Analysis. In Assessment, Management and Future Directions for Coastal Fisheries in Asian Countries, WorldFish Center Conference Proceedings67, pp299-312. Source archive PDF has14 pages. Official WorldFish page confirms1979 trawl survey and27 ecological groups:https://worldfishcenter.org/publication/marine-fisheries-resources-north-coast-central-java-indonesia . No separate supplement or erratum was located in the checked official record/search on2026-09-28.

Model ID:38_38002_North_Coast_Central_Java_(1979), project-local38002, not EcoBase accession.27 groups:2 producers,24 consumers,1 detritus. One1979 baseline; Table3 caption calls diets mid-1970s, preserved as a source-period distinction. User requested this solely for later comparison/testing; it is not selected and no comparative experiment was run.

## Spatial evidence and taxonomy
Figure1 PDF2/printed300 shows1979 survey area on north coast of Central Java around109-112 E and5-7 S. These are map extent/context, not a defensible full model polygon or area. Area and LME fraction remain missing. This small subregional model must not be represented as full Indonesian Sea coverage. Table1 PDF4-5/printed302-303 supplies membership for all27 groups. It lacks Buchary's distinct Medium demersals group; later numbers shift by one. Taxonomy keyed to exact Table2 group names, source spellings retained; no catch mapping or synonym adjudication.

## Tables and evidence
Table2 PDF7/printed305:Group,B,PB,QB,EE,GE,Landings,flow to detritus,TL,omnivory,R/A,R/B. Coordinate row/column extraction anchored on biomass rows, visually checked. Printed parentheses denote model outputs. Units t/km2 and annual rates. GE is systematically inconsistent with PB/QB (e.g.small herbivorous zooplankton0.46 versus60.22/220=0.274); it mostly resembles production/assimilation. Its ambiguous labeled values are retained in source_cells but NOT imported as P/Q. Benthic-producer EE is censored '<(0.01)', retained as missing plus bound.

Table3 PDF8/printed306:27 prey rows,24 predator columns3-26, exact geometric cells and rotated visual verification.29 censored diet cells (<0.01 or one >0.01) remain missing with printed bounds recorded in censored_values.json and canonical source_audit. Printed dashes are structurally absent prey, not measured unknown contributions. The literal217 at prey22/predator25 is visibly printed as217, not an OCR error; retained numerically with an invalid-proportion flag, not guessed to be0.217. Diet subtotals exclude censored unknowns; they are not full numerical diets.

## Deliberate blanks and severe defects
Biomass accumulation absent throughout14-page article; remains blank/-9999 for27/27. GS and detritus fate not explicitly quantified in this chapter; remain blank/-9999. Buchary predecessor parameters were not silently inherited. Discards unknown; Landings column used as printed. Converter habitat area1 and diet import0 are representation conventions, not independent source values. Reconstructed workbook fills structural/unknown diet cells with zeros; it is a compatibility view, not source evidence. Canonical bounds and source import blanks retain the distinction.

Printed predator25 diet subtotal217.78; adult-shrimp predator13 subtotal0.28 plus two<0.01 entries cannot close to1. SAF predator8 subtotal0.87 plus one<0.01 likewise cannot close. Miscellaneous pelagics predator14 subtotal0.98 with bounds including>0.01. Other small sum differences may involve rounding/censoring, but cannot excuse the large defects. No corrections, normalization or borrowed predecessor fractions were inserted.

## Validation and admission
Required imports:4 diet-sum errors,29 warnings (GS,BA and absent detritus fates). Source-table massbalance_check.py:3 errors,14 warnings; recomputed EE>1 for Rastrelliger1.039, juvenile large demersal110.103 and marine mammals2.722. Source-faithful database check classifies11 groups indeterminate because BA is unknown; its0 hard errors is NOT validity and no suggested BA adopted. Printed217 causes an impossible predation fraction regardless of missing BA. Exact basic input/diet round trip and all27 taxonomy descriptions checked; printed defects preserved. The legacy converter-normalized intermediate is retained only to audit conversion, and canonical diets restored.

SPPR NOT RUN: the literal217 proportion, severely incomplete diets and29 censored diet values do not support a defensible numerical model. This is a real source obstacle requiring authoritative corrected tables/model data before later numeric comparisons. Extraction is archived for those later tests, without pretending the paper is usable as printed. No production workbook, selection, catch matching, annual regional PPR, NPP ratio or map was changed.
'''
for mid,txt in [(bmid,B),(nmid,N)]:
 if mid==bmid:
  flows=json.loads((REG/'models'/mid/'evidence/loader_completed_flows.json').read_text(encoding='utf8'))['rows'];negba=[r for r in flows if isinstance(r.get('biomass_accum'),(int,float)) and r['biomass_accum']<0]
  txt+='\nLoader completion produced '+str(len(negba))+' negative BA values although every source BA is unknown. These include phytoplankton -4.51530, benthic producers -3.06715, small herbivorous zooplankton -2.15263 and carnivorous zooplankton -1.11317 t/km2/year. Full signed values for every group are preserved in evidence/loader_completed_flows.json. These completions reconcile the loaded group budgets; the separate contributions of source rounding and diet normalization were not isolated. Tiny negative residuals and material values must be distinguished, and none is a source-supported biomass trend.\n'
 (REG/'models'/mid/'extracted_tables/REPORT.md').write_text(txt,encoding='utf8')
 (REG/'models'/mid/'extracted_tables/MODEL_PROFILE.md').write_text('Axis: mixed taxonomic, size/habitat and life-stage groups.\nPrefixes: none; (J)/(A) distinguish juveniles/adults, not geography.\nArea and exclusions: see REPORT.md spatial evidence.\nMembership: complete source Table membership for every group; exact source names preserved in Taxonomy.xlsx.\nCatch eligibility: no regional catch assignment made; basal and plankton groups retained for source accounting.\nStatus: archived unselected candidate; strict numerical admission fails; do not use in production.\n',encoding='utf8')

bp={'article_id':'BUCHARY-1991__LME_038','unit_id':'LME_038','region_name':'Indonesian Sea','authors':'Eny Anggraini Buchary','publication_year':1999,'title':'Evaluating the effect of the 1980 trawl ban in the Java Sea, Indonesia: An ecosystem-based approach','model_years':'mid-1970s','functional_groups':28,'coverage_class':'subregional','target_coverage_ratio':None,'geometry_method':'Source-defined Java Sea; no digital polygon intersection computed','geometry_confidence':'textual area verified; LME fraction unavailable','full_model_loadable':'Strict source admission fails; isolated loader-normalized diagnostic completed','loadability_class':'Extracted source with severe missing diet fraction; diagnostic only','extraction_readiness':'Extracted; author model/correction needed for Macrozoobenthos missing0.340 diet fraction','download_status':'user_supplied_verified','main_file_status':'user_supplied_verified','supplement_status':'not identified','model_file_status':'Source-faithful JSON and eight imports archived','downloaded_file_count':1,'language':'English','recommendation':'User-preferred spatial candidate; not exact model selection and not source-valid as printed','article_dir':'regions/LME_038/papers/BUCHARY-1991','source_article_id':'BUCHARY-1991','selected':False,'correction_notes':'Supplied folder says1991; title page is April1999 thesis,1991 is prior degree. Potential INDO-1999/EcoBase410 relation unverified; no inherited36% coverage.','loadability_evidence':'Table3.9 PDF80 and3.10 PDF81;28 groups; Macrozoobenthos diet0.660.22 bounded transformed diagnostic methods; report and method audit archived.','documentation_evidence':'All28 taxonomy rows in Table3.1 PDF58-59. BA unknown; GS and detritus fate explicitly stated in prose.','coverage_note':'Java Sea approximately471000 km2 (PDF29/printed20), a subregion of Indonesian Sea LME38; no verified target fraction.','provenance':'User supplied thesis; source-byte SHA256 and cell evidence reviewed2026-09-28','notes':f'regions/LME_038/models/{bmid}/extracted_tables/REPORT.md'}
np={'article_id':'LME038-Nurhakim-2003__LME_038','unit_id':'LME_038','full_model_loadable':'No: printed217 proportion, severely incomplete and censored diets; SPPR not run','loadability_class':'Extracted source; strict admission blocked by printed defects','extraction_readiness':'Extracted for later tests; authoritative corrected model/tables needed','model_file_status':'Source-faithful JSON and eight imports archived; not numerically admitted','quality_rationale':'27-group1979 baseline. Table3 literal217 at prey22/predator25; diet subtotal217.78, adult-shrimp0.28;29 censored diets. Legacy pre-extraction scores retained for history, not revised validity.','loadability_evidence':'PDF7 Table2 and PDF8 Table3 checked visually and by coordinates. Required import4 errors; source massbalance3 errors. No repair or SPPR.','documentation_evidence':'Table1 PDF4-5 membership captured for27/27; GS/BA/fate unknown; censored EE retained.','recommendation':'Test/comparison candidate only per user; later tests not run; requires corrected numerical data','selected':False,'notes':f'regions/LME_038/models/{nmid}/extracted_tables/REPORT.md','provenance':'Expanded ecosystem search2026-09-04; extraction and source audit2026-09-28'}
models=[]
for mid,id,paper,year,pub,area,note in [(bmid,'38_38001_Java_Sea_(mid1970s)','BUCHARY-1991__LME_038','mid-1970s',1999,471000,bp['coverage_note']),(nmid,'38_38002_North_Coast_Central_Java_(1979)','LME038-Nurhakim-2003__LME_038',1979,2003,None,'North coast of Central Java1979 trawl-survey baseline; source map only, target fraction unknown.')]:
 models.append({'unit_id':'LME_038','model_id':id,'model_path':f'regions/LME_038/models/{mid}/model.json','source_filename':'ubc_1999-0254.pdf.pdf' if pub==1999 else 'content-ce43630c.pdf','selected':False,'selection_rationale':'Unselected; user-preferred spatial candidate' if pub==1999 else 'Unselected; later-test comparison candidate only','paper_ids':paper,'model_year':year,'model_years':str(year),'variant':'Printed static baseline; severe source defects preserved','model_area_km2':area,'availability':'Extracted; source admission fails; isolated loader-normalized SPPR only' if pub==1999 else 'Extracted; source admission fails; SPPR not run','publication_year':pub,'target_coverage_ratio':None,'coverage_class':'subregional','coverage_note':note})
save(Path(__file__).parent/'metadata_proposal.json',{'paper_upserts':[bp,np],'model_upserts':models,'write_policy':'Parent-coordinated exclusive write required. Preserve existing nonprovided fields, existing native tables and ranks; new ranks inherit current LME038 atlas rank. Do not modify production selection or unrelated metadata.'})
save(Path(__file__).parent/'source_use_audit.json',{'Buchary':'Source numeric extraction and isolated transformed diagnostics; not production','Nurhakim':'Source numeric extraction only, blocked numeric model; expressly later comparison candidate','official_record_checked':'https://worldfishcenter.org/publication/marine-fisheries-resources-north-coast-central-java-indonesia','supplements':'No separate identified supplement/erratum in checked official record/search2026-09-28; no unverified download claimed','legacy_relationship':'INDO-1999/EcoBase410 association with supplied thesis not independently verified; old36% coverage not inherited','production_workbook_sha256':hashlib.sha256((REG/'LME_038.xlsx').read_bytes()).hexdigest()})
print('reports, round-trip audits, source-use evidence and exact metadata proposal written')
