from pathlib import Path
import json,hashlib,sys
sys.stdout.reconfigure(encoding='utf-8');OUT=Path(__file__).parent;REG=OUT.parents[2]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
notes=['Main grid, selected-model identity and saved GE WARN readable; no clipping.','Manual fields, TE/With Egestion WARN and geographic/temporal limits retained; no clipping.','All confidence rows and corrected assumed-composition rule percentages readable; evidence links separated.','Allocation rules and weak squid evidence readable; long decision rows flow within margins.','Retained fish and cartilaginous Very low groupings readable; exact taxon labels visible.','Residual categories, jellyfish and grenadier reasoning readable; no text loss.','New numerical changes and historical Rajiformes scope readable; no stranded headings.','Target/source-location figure and caption retained and readable.','Source reconstruction figure and overlap denominators retained and readable.','Original source Figure 1 and discrepancy note retained and readable.']
manifest=json.loads((OUT/'final_render/render_manifest.json').read_text(encoding='utf-8'));assert manifest['pages']==len(notes)==10
data={'status':'PASS','inspection':'All ten final Word page PNGs were visually inspected individually through view_image. Appendix top, small contribution, zero-catch and Sources views were also inspected.','document_sha256':sha(REG/'Model_validation_13_1_Chilean_Patagonia_(1980).docx'),'appendix_sha256':sha(REG/'LME013_taxon_mapping_appendix.xlsx'),'pdf_sha256':sha(OUT/'final_render/report.pdf'),'pages':[{'page':i+1,'image':'final_render/'+name,'sha256':sha(OUT/'final_render'/name),'finding':notes[i]} for i,name in enumerate(manifest['images'])],'appendix_views':[{'image':n,'sha256':sha(OUT/n)} for n in ['live_top.png','live_small.png','live_zero.png','live_sources.png','live_current_evidence.png','live_elasm_evidence.png']],'layout':'No clipped text, overlap or missing figure. Existing page breaks, table formatting and manual cells preserved.','renderer_limitation':'Bundled render_docx.py could not run because LibreOffice is absent. A new independent hidden read-only Word instance exported PDF, then bundled Poppler rendered all pages.'}
(OUT/'visual_inspection.json').write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
print('Visual inspection recorded for ten final Word pages and six appendix views.')
