import json,pathlib,hashlib,collections,math
root=pathlib.Path('original_research_archive/research/size_allocation_20260929/lme_east')
search={
35:{'queries':['Gulf Thailand sharks juvenile adult catch size composition Christensen 1980','Gulf Thailand Epinephelus Lutjanus juvenile adult catch length composition','Gulf Thailand Trichiurus Muraenesox Chirocentrus Sphyraena catch length composition juvenile','Gulf of Thailand juvenile sharks catch size distribution'],'sources':[{'url':'https://repository.seafdec.or.th/handle/20.500.12067/226','finding':'Read primary institutional record: historical demersal species/community composition; no catch-mass fractions by the exact model stage boundaries.'},{'url':'https://onlinelibrary.wiley.com/doi/10.5402/2012/860768','finding':'Primary research search abstract describes nine preserved shark specimens from 1993; not a representative fishery catch mass distribution.'},{'url':'https://www4.fisheries.go.th/local/file_document/20210426100329_1_file.pdf','finding':'Search-returned official fisheries table contains species catch composition; no verified stage mass fractions. No model-specific age cutoff recovered.'}]},
36:{'queries':['northern South China Sea hairtail croaker juvenile adult catch proportion Cheung 2007','South China Sea croaker large pelagic demersal juvenile 18 months catch size Cheung 2007','South China Sea croaker catch juvenile 24'],'sources':[{'url':'https://schinafish.cn/cn/article/doi/10.3969/j.issn.1673-2227.2009.06.012','finding':'Primary research search abstract concerns light-purse-seine composition and high juvenile catches; page fetch timed out. No recovered wet-mass shares at 18-month model boundary.'},{'url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC8284606/','finding':'Primary study search abstract concerns gear selectivity of Pennahia argentata, which belongs to a dedicated small-croaker pool, not the Larimichthys large-croaker juvenile/adult pair.'},{'url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC12358585/','finding':'Research samples for ontogenetic diet analyses (including six juvenile fish) do not estimate population catch mass fractions.'},{'url':'https://www.mdpi.com/2076-2615/12/22/3078','finding':'Search abstract describes multi-species hairtail distributions and age composition elsewhere; no usable exact-model 18-month wet-catch split.'}]},
37:{'queries':['Visayan Sea sardines mackerel scads immature adult catch 1997 Bacalso size composition','Visayan Sea Scomberomorus catch length frequency 55 cm immature adult Bacalso','Visayan Sea length frequency sardine mackerel scad catch'],'sources':[{'url':'https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2023.1099400/full','finding':'Read source Tables 1/2 and baseline description. Exact FL boundaries and representative memberships recovered. Baseline 1996-97 local model catch estimates available, but are not observed species-specific mass fractions for Sulu-Celebes LME037.'},{'url':'https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2021.640772/full','finding':'Read/search page: seasonal closure analysis of sardine/mackerel catches; no length-frequency mass split recovered at the model cutoffs.'},{'url':'https://digitalarchive.worldfishcenter.org/items/2de1e29f-3de4-4172-bc38-27e6a7de555d','finding':'Read institutional primary article abstract. Visayan mackerel length frequencies 1983-87 explicitly lack small fish; not representative juvenile/adult catch-mass shares at 16 cm FL.'},{'url':'https://nfrdi.da.gov.ph/tpjf/etc/assessment_of_the_commercial_fisheries_of_western_and_central_visayan_sea.pdf','finding':'Official primary fisheries assessment discovered with length-frequency material; fetch failed 502. No numeric distribution recovered or applied.'}]},
38:{'queries':['Java Sea Penaeus shrimp juvenile adult catch size composition trawl','Java Sea large pelagic predators juvenile adult catch size composition Scomberomorus Trichiurus','Java Sea sharks Arius Muraenesox juvenile adult catch length composition'],'sources':[{'url':'https://ejournal-balitbang.kkp.go.id/index.php/jppi/article/view/1354','finding':'Read primary government fisheries research abstract: 2015 survey species composition and mean carapace lengths. Neither species proportions nor mean lengths are the required juvenile/adult catch-mass split.'},{'url':'https://ejournal-balitbang.kkp.go.id/index.php/bawal/article/view/10632','finding':'Primary fisheries search abstract: Indramayu gillnet shark/ray catches juvenile/subadult, but no matching model age cutoff or mass weights; full page failed 502.'},{'url':'https://www.sciencedirect.com/org/science/article/pii/S0137159225000056','finding':'Primary hairtail length study search result covers southern Java Indian Ocean FMA573, not the Java Sea model; excluded spatial transfer as observed data.'}]},
52:{'queries':['Okhotsk Sea pollock fishery catch age composition juveniles 1980 2023 stock assessment length'],'sources':[{'url':'https://russianpollock.com/upload/iblock/b38/summary-tinro-soo-observers-2019.pdf','finding':'Primary TINRO observer summary discovered; search snippet mentions juvenile percentages, full fetch timed out. Model juvenile boundary not documented, so these are not a verified mass split for model groups.'},{'url':'https://osci.ru/ru/nauka/article/100610/view','finding':'Primary pollock trawl study search snippet gives size statistics. Open failed; no full catch-mass distribution recovered at the unknown model boundary.'},{'url':'https://apps-afsc.fisheries.noaa.gov/Plan_Team/2023/EBSPollock.pdf','finding':'NOAA assessment includes age compositions but is Eastern Bering Sea, not Okhotsk. Excluded as observed regional evidence.'}]}}
for v in search.values():v.update({'searched_on':'2026-09-29','usable_observed_mass_weights':False,'conclusion':'Targeted online search attempted before fallback. No applicable observed catch wet-mass shares recovered; source/model proxy remains an explicit assumption, not a no-data-exists claim.'})
(root/'online_search_audit.json').write_text(json.dumps(search,indent=2),encoding='utf8')
splits={35:[([8,2],'Sharks: juvenile/adult; source age/length cutoff not documented.'),([9,3],'Large piscivores Trichiurus/Muraenesox/Chirocentrus/Sphyraena: juvenile/adult; age/length cutoff not documented.'),([10,4],'Grouper AND snapper stages (source prose includes Lutjanus in shortened Juv. groupers label); cutoff not documented.')],36:[([16,17],'Trichiuridae split at 18 months.'),([22,23],'Large Sciaenidae including Larimichthys crocea, species maximum length >30 cm; juvenile/adult split at 24 months. Small-croaker group is not same-species juvenile pool.'),([25,26],'Residual large demersal species >30 cm maximum length; juvenile/adult split at 18 months. Dedicated taxa excluded.'),([30,31],'Residual large pelagic species >30 cm maximum length; juvenile/adult split at 18 months.')],38:[([11,13],'All juvenile/adult shrimps; parameterization based on Penaeus/Metapenaeus. Numeric age/size boundary not documented.'),([12,25],'Juvenile/adult Chirocentridae, large Scombridae and Trichiuridae. Numeric age/size boundary not documented.'),([23,26],'Juvenile/adult source-defined large demersal predators. Numeric age/size boundary not documented.')]}
none={32:'Size-labelled Karnataka guilds comprise different source taxonomic memberships; no unambiguous same-taxon juvenile/adult pair found. Existing supported mappings preserved.',34:'Numeric prefixes are geographic regions, not stages; small/large guilds include different memberships. Spatial biomass allocations are outside this size-only authorization and unchanged.',47:'Large yellow croakers and Small yellow croakers are distinct taxa (Larimichthys crocea/polyactis), not size stages; no same-taxon stage pair.',49:'Repeated OYC/KC/OF groups are spatial distributions; no size-stage pair. Spatial/unknown species mixtures remain unresolved.',50:'No repeated same-taxon juvenile/adult size pair; no applicable allocation.'}
output={'schema_version':1,'scope':'Selected eastern LMEs only; research proposals, no production edits','pairs':[]}
for num in [32,34,35,36,37,38,47,49,50,52]:
 d=json.loads((root/f'LME_{num:03}_audit.json').read_text(encoding='utf8'));u=d['unit_id'];mid=d['settings']['selected_model_id'];cp=pathlib.Path('regions')/u/d['settings']['model_path'];canonical=json.loads(cp.read_text(encoding='utf-8-sig'));cg={int(g['group_seq']):g for g in canonical['group']};gg={int(g.get('seq',g.get('group_seq',0))):g for g in d['groups']};bytax=collections.defaultdict(list)
 for m in d['matching']:bytax[m['taxon']].append(m)
 pair={'unit_id':u,'model_id':mid,'workbook_sha256':d['workbook_sha256'],'review_status':'none_applicable' if num in none else 'reviewed_stage_candidates','proposals':[],'unresolved':[],'canonical_source_path':cp.as_posix(),'canonical_sha256':hashlib.sha256(cp.read_bytes()).hexdigest(),'numeric_sppr_exists':any(isinstance(x.get('sppr'),(int,float)) for x in d['sppr'])}
 if num in none:pair['unresolved'].append({'reason':none[num]})
 else:pair['online_search_audit']=search[num]
 def prop(taxon,ids,definition,weights=None,action='document_existing_model_catch_proxy'):
  groups=[gg[i] for i in ids];catches=[float(cg[i]['export']) for i in ids]
  for i,g,y in zip(ids,groups,catches):assert math.isclose(g['catch'],y,abs_tol=1e-10),(u,i,g['catch'],y)
  if weights is None:weights=[y/sum(catches) for y in catches]
  pr={'taxon':taxon,'rule':'assumed_adult_only_no_catch_basis' if sum(catches)==0 else 'model_catch_proportions_proxy','action':action,'evidence':f'{cp.as_posix()} group.export; exact matching loaded catch values verified; regional workbook Selected model groups/Groups; online_search_audit.json LME{num:03}; source taxonomy definitions retained in canonical taxon_descr.','definition':definition,'limitations':'Assumed fixed stage allocation across catch years; model-group aggregate catches need not represent species-specific, regional, annual or gear-specific size composition. No biomass weighting or SAU speciesmaxsize used. Source and numerical diagnostic limitations remain.','source_period':{35:'1980 by source identity audit; inherited filename says 1963',36:'2000s',37:'1997 Visayan baseline',38:'mid1970s',52:'1980'}[num],'candidates':[{'group':g['group_name'],'seq':i,'source_catch':y,'weight':w,'source_definition':cg[i].get('taxon_descr'),'numeric_sppr_exists':any(s.get('group')==g['group_name'] and isinstance(s.get('sppr'),(int,float)) for s in d['sppr'])} for i,g,y,w in zip(ids,groups,catches,weights)],'existing_matching':bytax[taxon],'source_path':cp.as_posix(),'source_sha256':pair['canonical_sha256'],'catch_units':'model t wet weight km^-2 yr^-1; ratios dimensionless','online_search_audit':'online_search_audit.json#'+str(num)}
  pair['proposals'].append(pr)
 if num in splits:
  for ids,definition in splits[num]:
   names={gg[i]['group_name'] for i in ids}
   for taxon,ms in bytax.items():
    positive={m['group'] for m in ms if m['group'] and m['weight'] and m['weight']>0}
    if positive and positive<=names:
     prop(taxon,ids,definition)
  stage_names={gg[i]['group_name'] for ids,_ in splits[num] for i in ids}
  for t,ms in bytax.items():
   names={m['group'] for m in ms if m['group']}
   if names&stage_names and not any(p['taxon']==t for p in pair['proposals']):pair['unresolved'].append({'taxon':t,'reason':'Existing composite includes non-stage taxonomic/size/guild ambiguity; preserved without redistributing whole taxon across stage groups.','existing_matching':ms})
 if num==37:
  cases=[(['Sardinella fimbriata','Sardinella lemuru'],[7,8],'Sardines: 4.3-10.5 / 10.5-22 cm FL; named source species only.'),(['Rastrelliger brachysoma','Rastrelliger kanagurta'],[9,10],'Mackerels: 8-16 / 16-28 cm FL; named source species only.'),(['Decapterus','Decapterus macrosoma','Decapterus russelli'],[11,12],'Scads: 6-15 / 15-31 cm FL; source explicitly lists other Decapterus spp.'),(['Scomberomorus','Scomberomorus commerson','Scomberomorus guttatus'],[4,5],'Pelagic predators: 14-55 / 55-125 cm FL; source explicitly Scomberomorous spp. (misspelling normalized Scomberomorus).')]
  for taxa,ids,de in cases:
   for t in taxa:
    if t in bytax:prop(t,ids,de,action='add_assumed_stage_mapping')
  for t in ['Sardinella','Sardinella albella','Rastrelliger','Scombridae','Carangidae','Clupeidae','Marine fishes not identified']:
   if t in bytax:pair['unresolved'].append({'taxon':t,'reason':'Representative species list does not authorize exhaustive genus/family or mixed-guild membership. Retain unresolved; no invented taxonomic proportions.'})
 if num==52:
  prop('Gadus chalcogrammus',[7,6],'Same species juvenile/adult pollock; model age/length threshold absent from available chapter. All model catches zero; adult-only is expressly assumed.',[0.0,1.0],'replace_existing_biomass_stage_weights')
  for t in ['Gadidae','Gadiformes']:pair['unresolved'].append({'taxon':t,'reason':'Existing biomass-weighted composite also includes non-pollock taxa. Stage-only rule does not establish taxonomic proportions; no wholesale adult-pollock allocation proposed. Existing mapping retained for separate review.','existing_matching':bytax[t]})
 output['pairs'].append(pair)
for p in output['pairs']:
 for q in p['proposals']:assert abs(sum(c['weight'] for c in q['candidates'])-1)<1e-10
(root/'proposals.json').write_text(json.dumps(output,ensure_ascii=False,indent=2),encoding='utf8')
print([(p['unit_id'],len(p['proposals']),len(p['unresolved'])) for p in output['pairs']])
