"""Prepare exact central fields and adapt the reviewed narrow package-preservation helper."""
from pathlib import Path
import json
ROOT=next(p for p in Path(__file__).resolve().parents if (p/'Project.xlsx').exists());OUT=Path(__file__).parent
source=json.loads((OUT/'metadata_registration_proposal.json').read_text(encoding='utf-8'));proposal={'status':'READY','paper_updates':[],'model_rows_to_register':[]}
for p in source['paper_updates']:
    m=next(x for x in source['models'] if x['paper_id']==p['paper_id']);old=p['paper_id']=='KUR-2019';paper_id=p['paper_id']+'__LME_049';report=m['report_path'].replace('\\','/');diagnostic=m['diagnostic_path'].replace('\\','/')
    fields=['authors','title','doi','functional_groups','model_years','main_file_status','supplement_status','full_model_loadable','loadability_class','model_file_status','extraction_readiness','download_status','downloaded_file_count','download_failure_reason','quality_rationale','recommendation']
    changes={k:p[k] for k in fields}
    changes.update({'loadability_evidence':report+'; '+diagnostic,'documentation_evidence':report,'notes':('USER-PREFERRED SOURCE: Watari 2019, because its group structure is more detailed (41 groups). Exact model not selected. ' if old else 'Chen 2023 candidate has 25 groups. Exact model not selected. ')+'Source-faithful extraction preserves censored inputs and missing BA/GS/routing. Source hashes, import files, canonical JSON, taxonomy and validation retained. '+('Seven table cells are censored (seabird biomass twice and five landings); no numeric values invented. Bounded SPPR loading fails because routing among detritus pools39/40/41 is missing. No methods or MC draws executed. Detailed species supplement not archived due publisher HTTP401; pooled taxonomy incomplete.' if old else 'Fifty-four diet cells are censored + values. Bounded conditional loader run used100 draws per MC method and180s/method. GE/TE/With Egestion all FAIL; both MC methods accepted0/100 and rejected100/100 as divergent. Numeric outputs depend on loader zeroing censored diet entries, normalization and filling missing inputs, and are not source-faithful production results. Negative source groups retained, including groups whose catch was unknown and loader-completed to zero.')+' Evidence: '+report,'coverage_note':('The three linked OYC/KC/OF blocks form one2013 model; source areas186128/186220/540754km2 sum to913102km2. ' if old else '2023 offshore Kuroshio-Oyashio Extension survey domain148–164E,35–45N. ')+'Partial LME applicability. Inherited paper coverage ratio retained as history and not newly validated; no numerical ratio assigned to the new candidate.','retrieval_audit':('regions/LME_049/papers/KUR-2019/supplement_retrieval_log.json' if old else 'Local main PDF and DOCX verified by source_manifest.json in the candidate folder.')})
    if not old:
        changes['legacy_authors']='Gan et al.';changes['legacy_title']='Ecosystem structure and trophodynamics in the Kuroshio–Oyashio Extension area';changes['correction_notes']='Verified main PDF page1 identifies author Gan Chen; citation corrected to Chen et al. Exact printed title: Study in the ecosystem structure and trophodynamics in the Kuroshio-Oyashio Extension area. Main Table1 is the species composition source, while supplement S1 lists parameter/diet-study references.'
    else:changes['correction_notes']='Verified main PDF supplies DOI10.3354/meps12508 and one2013 model. Source preference is not exact-model adoption. Model has35 consumers,3 producers,3 spatial detritus pools.'
    proposal['paper_updates'].append({'article_id':paper_id,'changes':changes})
    proposal['model_rows_to_register'].append({'unit_id':'LME_049','model_id':m['model_id'],'model_path':m['model_path'].replace('\\','/'),'source_filename':m['model_id']+'.json','selected':False,'selection_rationale':None,'paper_ids':paper_id,'model_year':int(m['model_years']),'variant':'Published static Ecopath model; printed precision and unresolved inputs preserved','model_area_km2':913102 if old else None,'availability':m['extraction_status']+'. '+changes['notes']+' Candidate-only evidence; no production selection.','publication_year':p['publication_year'],'model_years':m['model_years'],'target_coverage_ratio':None,'coverage_class':'partial','doi':p['doi'],'coverage_note':changes['coverage_note']})
(OUT/'central_metadata_proposal.json').write_text(json.dumps(proposal,ensure_ascii=False,indent=2),encoding='utf-8')
helper=(ROOT/'regions/LME_022/models/extraction_review_20260928/register_central_metadata.py').read_text(encoding='utf-8')
helper=helper.replace('LME_022','LME_049').replace('LME022','LME049').replace('assert rank==11','assert rank==12').replace('atlas rank11','atlas rank12')
helper=helper.replace("if isinstance(old,str) and old and isinstance(value,str):value=old+'\\n\\n[2026-09-28 extraction assessment] '+value", "if field in {'notes','recommendation','correction_notes','coverage_note','loadability_evidence','documentation_evidence','quality_rationale','retrieval_audit','legacy_authors','legacy_title'} and isinstance(old,str) and old and isinstance(value,str):value=old+'\\n\\n[2026-09-28 extraction assessment] '+value")
helper=helper.replace("allowed=set();paper_changes=[]", "allowed=set();paper_changes=[]\nregional_hash=sha(ROOT/'regions/LME_049/LME_049.xlsx')\nassert all((ROOT/item['model_path']).is_file() for item in proposal['model_rows_to_register'])")
helper=helper.replace("# Cell-level audit of all touched sheets; untouched ZIP parts must remain identical.", "# Cell-level audit of all touched sheets; untouched ZIP parts must remain identical.\nassert sha(ROOT/'regions/LME_049/LME_049.xlsx')==regional_hash\n# All existing selected flags, ranks, scores and LME022 cells are outside the allowlist.\nfor field in ['selected','region_rank','atlas_region_rank','legacy_documentation_score_60','legacy_applicability_score_40','model_loadability_score_55','documentation_score_20','spatial_fit_score_15','recency_validation_score_10','quality_score_cap','quality_score_100']:\n assert all(change['field']!=field for change in paper_changes)\n")
(OUT/'register_central_metadata.py').write_text(helper,encoding='utf-8')
print('Prepared two exact paper-id updates and two unselected model rows; helper preserves unrelated package parts.')
