import pathlib,json,hashlib,csv,math,os,sys
import openpyxl
HERE=pathlib.Path(__file__).resolve().parent;ROOT=HERE.parents[4];REGION=ROOT/'regions/LME_036';MID='36_1_South_China_Sea_SCS-2007_Northern_South_China_Sea_(2000s)'
sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
load=lambda n:json.loads((HERE/n).read_text(encoding='utf-8'))
save=lambda n,v:(HERE/n).write_text(json.dumps(v,ensure_ascii=False,indent=2,allow_nan=False)+'\n',encoding='utf-8')
sys.path.insert(0,str(ROOT/'tools/skills/original_skill_resources/combined-src/scripts'))
from check_evidence import check
assert sha(REGION/'LME_036.xlsx')==load('adoption_checks.json')['final_region_sha256']
runtime={int(r['group_seq']):r for r in csv.DictReader((HERE/'direct_diagnostics/runtime_groups_before.csv').open(encoding='utf-8'))}
foot=[]
for method in ['GE','TE','With_Egestion']:
 d=load('direct_diagnostics/'+method+'_SPPR_lossless.json');report=load('direct_diagnostics/'+method+'_report.json')
 assert len(set(d['row_ids']))==len(d['row_ids']) and len(set(d['column_ids']))==len(d['column_ids'])
 for scope,field in [('all','ppr_all'),('inner','ppr_inner'),('PP','ppr_pp_only')]:
  jj=[j for j,i in enumerate(d['column_ids']) if scope=='all' or scope=='inner' and i!=39 or scope=='PP' and runtime[i]['trophic_info']=='PP']
  value=math.fsum(float(runtime[i]['catch'])*math.fsum(row[j] for j in jj) for i,row in zip(d['row_ids'],d['values']))
  assert math.isclose(value,report['footprint'][field],rel_tol=1e-10,abs_tol=1e-10)
  foot.append({'method':method,'scope':scope,'source_ids':[d['column_ids'][j] for j in jj],'matrix_recomputed_ppr':value,'diagnostic_ppr':report['footprint'][field],'units':'project runtime wet-mass PP areal annual units','relative_tolerance':1e-10,'reconciled':True})
save('direct_diagnostics/footprint_reconciliation.json',{'scope_checks':foot,'all_retained_groups_including_unfished':True,'b_definition':'GE/With Egestion detrital recycling loop gain from the coupled detritus scaling. TE returns b=0 as a formulation convention; this is not evidence of zero physical recycling.','detritus_id':38,'synthetic_external_import_id':39})
visual=load('visual_checks.json');visual['baseline_frozen_panes']=['A8','A10','A370','A53'];visual['header_freeze_correction_reason']='The allocation pane froze369rows and Sources52rows; header-only panes now expose the data in ordinary windows. Low filter and saved cell selections are preserved.';visual['final_render_input_sha256']=sha(REGION/'LME036_taxon_mapping_appendix.xlsx');save('visual_checks.json',visual)
index=load('evidence_index.json')
for a in index['artifacts']:
 if a['availability']=='present':a['sha256']=sha(HERE/a['path'])
extra=HERE/'direct_diagnostics/footprint_reconciliation.json'
index['artifacts'].append({'role':'direct_diagnostic_footprint_reconciliation','path':os.path.relpath(extra,HERE).replace('\\','/'),'sha256':sha(extra),'availability':'present'})
index['required_roles'].append('direct_diagnostic_footprint_reconciliation');index['reconciliation']['source_matrix_scope_and_footprints_reconciled']=True
save('evidence_index.json',index);complete=check(HERE/'evidence_index.json');save('completeness.json',complete);assert not complete['errors']
metadata_path=ROOT/'original_research_archive/research/selected_regions_validation_20260930/central_source_metadata_current.json';metadata=json.loads(metadata_path.read_text(encoding='utf-8'))
assert metadata['project_sha256']==sha(ROOT/'Project.xlsx')
modelrow=next(r for r in metadata['tables']['Models & coverage'] if r['unit_id']=='LME_036' and r['model_id']==MID)
paperrow=next(r for r in metadata['tables']['Papers'] if r['article_id']=='SCS-2007__LME_036')
metadata_patches=[]
for field,new in {'model_year':'2000s','publication_year':2007,'model_years':'1970s and 2000s','coverage_class':'subregional','doi':'10.14288/1.0074894','availability':'Accepted selected project runtime locally load-tested; GE/TE WARN and With Egestion OK. Source discrepancies remain; native Ecopath import unverified.','coverage_note':'Northern shelf source; visual overlap/region about15–25% and overlap/study about90–100%, without measured polygon intersection. Fixed2000s source transferred to1950–2019 whole-LME catch; provisional.'}.items():
 metadata_patches.append({'table':'Models & coverage','key':{'unit_id':'LME_036','model_id':MID},'field':field,'expected_old':modelrow[field],'proposed_new':new,'evidence':['source PDF Figure6.1 printed170/PDF185; Tables6.1–6.2 and Appendix6.1','coverage_geography_test_note.md','selected_regions_review_20260930/direct_diagnostics/complete_input_identity.json']})
for field,new in {'full_model_loadable':'Accepted project runtime locally load-tested; native Ecopath import unverified','loadability_evidence':str((HERE/'direct_diagnostics/complete_input_identity.json').relative_to(ROOT)).replace('\\','/'),'documentation_evidence':str((HERE.parent/'source/reconstruction_2000s/SOURCE_CATCH_TOTALS.json').relative_to(ROOT)).replace('\\','/')}.items():
 metadata_patches.append({'table':'Papers','key':{'unit_id':'LME_036','article_id':'SCS-2007__LME_036'},'field':field,'expected_old':paperrow[field],'proposed_new':new,'evidence':['retained reconstruction evidence; accepted runtime reproduced and directly diagnosed without parameter changes'],'limitations':'No native EwE database/import verification and no score/loadability-class regrade proposed.'})
changes=load('mapping_changes.json');by={r['taxon']:r for r in changes};summary=load('summary.json');effects=load('dependent_result_changes.json');checks=load('adoption_checks.json');artifact=load('artifact_edit_checks.json')
main_effect=[r for r in effects if r['scope']=='all' and r['basis']=='landings' and r['unidentified']=='method' and r['method'] in ['new_GE','new_TE_EEfix','new_WithEgestion']]
report=REGION/f'Model_validation_{MID}.docx';appendix=REGION/'LME036_taxon_mapping_appendix.xlsx'
handoff={'schema_version':1,'region_id':'LME_036','model_id':MID,'article_id':'SCS-2007__LME_036','run_id':'selected_regions_review_20260930','regional_work_complete':True,'shared_alignment_complete':False,'ownership_released_to_coordinator':True,
 'identities':{'baseline_region_sha256':checks['freshness_guard_expected_sha256'],'current_region_sha256':sha(REGION/'LME_036.xlsx'),'model_sha256':sha(REGION/'models'/MID/'model.json'),'saved_sppr_source_sha256':sha(REGION/'models'/MID/'sppr_source.xlsx'),'input_sha256':checks['final_input_sha256'],'result_sha256':checks['final_result_sha256'],'reference':{'year':2019,'basis':'landings','scope':'all','treatment':'method','independent_method':'simple trophic chain','TE':0.1,'carbon_divisor':9},'baseline_report_sha256':sha(HERE/('baseline_'+report.name)),'baseline_appendix_sha256':sha(HERE/'baseline_LME036_taxon_mapping_appendix.xlsx'),'report_sha256':sha(report),'appendix_sha256':sha(appendix)},
 'preservation_checks':checks,'protected_numerical_parameters':'Canonical model JSON and every Groups value unchanged: B/PB/QB/EE/diet/BA/catch/balancing/routing/runtime conventions; Group SPPR/raw Catch/classic TL and all independent classic results/NPP/independent ratios preserved. Source-fidelity concerns remain documentary.',
 'proposal_dispositions':load('proposal_dispositions.json'),'adopted_changes':changes,'summary':summary,'method_effects_default_2019_all_landings':main_effect,'all_effects_path':'selected_regions_review_20260930/dependent_result_changes.json','maximum_absolute_2019_percentage_effect':max(effects,key=lambda r:abs(r['change_pct'])),
 'diagnostics':{'fresh_options':['GE','TE','With Egestion'],'reason':'Required full source matrices were absent from aggregate saved export; scoped authorization confirmed before direct run.','input_identity_path':'selected_regions_review_20260930/direct_diagnostics/complete_input_identity.json','statuses':{s:load('direct_diagnostics/'+s.replace(' ','_')+'_report.json')['status'] for s in ['GE','TE','With Egestion']},'returned_matrices':'All SPPR/A/L arrays from each call, named ordered axes, explicit null/NaN/±infinity masks, synthetic flags and hashes retained and reopened.','negative_source_SPPR_entries':0,'nonfinite_source_SPPR_entries':0,'scope_and_footprint_reconciliation':True,'coefficient_comparison':load('direct_diagnostics/coefficient_comparison.json'),'numerical_adoption':'Preserved exact saved Group SPPR; fresh-vs-saved differences only round-trip scale.','other_saved_methods':'Existing coefficients reused on identical accepted model/configuration. No global or Monte Carlo solve. Dependent arithmetic updated using every accepted saved method.','manual_note_discrepancy':'Saved/runtime groups34–37 present with finite direct coefficients; manual exclusion note preserved and qualified in Other. No exclusions applied.'},
 'artifacts':{'report':str(report.relative_to(ROOT)).replace('\\','/'),'appendix':str(appendix.relative_to(ROOT)).replace('\\','/'),'evidence_index':'selected_regions_review_20260930/evidence_index.json','completeness':'selected_regions_review_20260930/completeness.json','artifact_checks':artifact,'numeric_verification':load('numeric_verification.json'),'visual_checks':visual,'report_links':'selected_regions_review_20260930/report_link_checks.json','appendix_links':'selected_regions_review_20260930/appendix_links.json','manual_rows':'Selection rationale, complete SPPR calculation, Open issues/next action and Review/reproducibility XML including links/deletions exactly preserved.','portable_links':'Every final link stored relative to containing document where local; all linked text blue0563C1 and single underline; empty HyperlinkBase has no machine-specific value.'},
 'pending_shared_metadata_patches':metadata_patches,'metadata_expected_old_snapshot':{'path':str(metadata_path.relative_to(ROOT)).replace('\\','/'),'project_sha256':metadata['project_sha256'],'verified_against_live_project':True},
 'pending_shared_integration':[{'target':'Project.xlsx generated summaries/inventories; maps/trends/archive','key':{'unit_id':'LME_036','selected_model_id':MID,'article_id':'SCS-2007__LME_036'},'expected_old':{'confidence_counts':{'High':142,'Medium':133,'Low':89,'Very low':10,'Unresolved':0},'baseline_region_sha256':checks['freshness_guard_expected_sha256']},'new':{'confidence_counts':{r['confidence']:r['taxa'] for r in summary['categories']},'region_sha256':sha(REGION/'LME_036.xlsx'),'mapping_changes':36},'action':'Re-read latest Project, consolidate canonical regional workbook with freshness guard; preserve selection and accepted parameters. Rebuild/verify shared outputs and actual browser controls. Current local index retains six required shared roles as missing/pending.'},
 {'target':str(report.relative_to(ROOT)).replace('\\','/'),'field':'opening paragraph','expected_old':'Pending alignment draft for the selected 2000s northern South China Sea model. All 374 taxa were reviewed; 36 supported group corrections are adopted regionally. The linked appendix records confidence and assumptions. Estimates remain provisional.','new_after_verified_alignment':'Validation record for the selected 2000s northern South China Sea model. All 374 taxa were reviewed; 36 supported group corrections are adopted. The linked appendix records confidence and assumptions. Estimates remain provisional.','action':'Only clear pending-alignment wording after all six shared roles verified; re-render and refresh report/index hashes.'}],
 'transferable_lessons':[
 {'lesson':'Use region-specific species maximum TL at the operative boundary; common individual sizes cannot add a small-species candidate.','taxon':'Psettodidae','evidence':by['Psettodidae']['source_locators'],'application':by['Psettodidae'],'limit':'Regional FAO family enumeration supports pruning24 here; no automatic group transfer elsewhere.'},
 {'lesson':'Broad rank alone is not mixed-size proof. Check regionally relevant small and large constituents and disclose representative extension separately from weight confidence.','taxon':'Ariidae','evidence':by['Ariidae']['source_locators'],'application':by['Ariidae'],'limit':'M9/Medium is representative-based regional membership; catch-proxy weights are separately W4/Medium.'},
 {'lesson':'Restricted historical source family/reporting concepts control named pools; current nomenclature does not silently broaden them.','taxon':'Caesionidae','evidence':by['Caesionidae']['source_locators'],'application':by['Caesionidae'],'limit':'Source-era fusiliers are not automatically group19snappers; final27 scope remains explicit Low ambiguity.'},
 {'lesson':'Separately identified family/genus catch does not by itself measure a residual target-label composition.','evidence':['selected_regions_review_20260930/search_record.json','selected_regions_review_20260930/allocation_audit.json'],'limit':'No W5 used in036. Evidence must establish target reporting relationship and representativeness before adopting identified-congener proxies; all185 splits here use complete source catches.'},
 {'lesson':'Manual removal notes require actual saved/runtime configuration verification.','evidence':['selected_regions_review_20260930/direct_diagnostics/runtime_vs_saved_groups.json','selected_regions_review_20260930/direct_diagnostics/manual_exclusion_discrepancy.json'],'limit':'Do not alter accepted numerical configuration from a note.'},
 {'lesson':'Explicit UTF-8 prevents new locale corruption; exact canonical group keys must remain stable even when retained description text contains mojibake.','evidence':['selected_regions_review_20260930/adoption_checks.json','selected_regions_review_20260930/mapping_changes.json'],'limit':'No blanket repair to accepted model or historical source strings.'}],
 'scientific_limitations':load('scientific_limitations.json'),'genuine_scientific_blockers':[],'required_evidence_pending':complete['missing_roles'],'descendants':{'spawned':0,'active':0},'git_actions':{'staged':False,'committed':False,'pushed':False}}
target=HERE.parent/'coordination_handoff.json';target.write_text(json.dumps(handoff,ensure_ascii=False,indent=2,allow_nan=False)+'\n',encoding='utf-8');reopened=json.loads(target.read_text(encoding='utf-8'));assert reopened['identities']['current_region_sha256']==sha(REGION/'LME_036.xlsx')
print(json.dumps({'handoff':str(target.relative_to(ROOT)).replace('\\','/'),'sha256':sha(target),'regional_work_complete':True,'pending_shared_roles':complete['missing_roles'],'metadata_patches':len(metadata_patches)},ensure_ascii=True))
