"""Migrate existing validation.csv files to the checks validate_region now emits.

Drops four removed rows (commercial_ppr_reconciled, functional_ppr_reconciled,
commercial_jensen_violations, functional_jensen_violations) and appends two new
rows (tl_coverage_complete, group_ppr_within_convexity_bound).

Both new checks are computed directly from each unit's species.csv,
commercial.csv and functional.csv - the files migrate_group_columns.py already
rewrote and value-identity-checked - using the exact same formula as
ppr_pipeline.validation.validate_region (tolerance=1e-10 default, one-sided
convexity bound). They are deliberately NOT derived from the species_ppr /
commercial_ppr / functional_ppr / *_ppr_difference rows already sitting in
validation.csv: those rows predate the Jensen-only group aggregation (they were
generated by an older pipeline run, before group tables were narrowed to a
single Jensen-affected `ppr` column) and are stale - on every unit checked,
the stored commercial_ppr/functional_ppr equal species_ppr almost exactly,
which is only possible if they were computed from the old sum-of-matched-taxa
("correct") aggregation, not the current catch-weighted-mean-TL aggregation.
Reusing them would produce a technically-non-fabricated-looking but factually
wrong convexity check. This script does not touch those stale rows - fixing
them is out of scope for this migration and is reported separately.

Every surviving row's value is proven byte-identical to its pre-migration
counterpart. If a unit's species/commercial/functional CSVs cannot be found or
parsed, the corresponding new check is left absent for that unit and reported
- never invented.
"""
from __future__ import annotations
import sys
from pathlib import Path
import pandas as pd

REMOVE_CHECKS = [
    "commercial_ppr_reconciled",
    "functional_ppr_reconciled",
    "commercial_jensen_violations",
    "functional_jensen_violations",
]
TOLERANCE = 1e-10


def region_dir(validation_path: Path, unit_id: str) -> Path:
    """Directory holding unit_id's species/commercial/functional.csv."""
    if validation_path.parent.name == unit_id:
        # per-region file: tables/regions/<unit_id>/validation.csv
        return validation_path.parent
    # combined file: tables/validation.csv -> tables/regions/<unit_id>/
    return validation_path.parent / "regions" / unit_id


def compute_checks(unit_dir: Path) -> tuple[bool | None, bool | None]:
    """Return (tl_coverage_complete, group_ppr_within_convexity_bound) or None each if not computable."""
    species_path = unit_dir / "species.csv"
    commercial_path = unit_dir / "commercial.csv"
    functional_path = unit_dir / "functional.csv"
    if not (species_path.exists() and commercial_path.exists() and functional_path.exists()):
        return None, None
    species = pd.read_csv(species_path, encoding="utf-8-sig", float_precision="round_trip")
    commercial = pd.read_csv(commercial_path, encoding="utf-8-sig", float_precision="round_trip")
    functional = pd.read_csv(functional_path, encoding="utf-8-sig", float_precision="round_trip")
    if "tl" not in species.columns or "ppr" not in species.columns:
        return None, None
    tl_ok = bool(species["tl"].notna().all())

    if "ppr" not in commercial.columns or "ppr" not in functional.columns:
        return tl_ok, None
    matched = species.loc[species["tl"].notna()]
    species_ppr = float(pd.to_numeric(matched["ppr"], errors="coerce").sum())
    commercial_ppr = float(pd.to_numeric(commercial["ppr"], errors="coerce").sum())
    functional_ppr = float(pd.to_numeric(functional["ppr"], errors="coerce").sum())
    convexity_bound = TOLERANCE * abs(species_ppr) + 1e-8
    convexity_ok = bool(
        commercial_ppr - species_ppr <= convexity_bound
        and functional_ppr - species_ppr <= convexity_bound
    )
    return tl_ok, convexity_ok


def migrate(path: Path) -> tuple[str, list[str]]:
    before = pd.read_csv(path, encoding="utf-8-sig", float_precision="round_trip")
    declined: list[str] = []

    kept = before.loc[~before["check"].isin(REMOVE_CHECKS)].copy()
    # prove every surviving row is untouched
    survivors_before = before.loc[~before["check"].isin(REMOVE_CHECKS)]
    if not kept.reset_index(drop=True).equals(survivors_before.reset_index(drop=True)):
        raise AssertionError(f"{path}: a surviving row changed")

    # A file may hold rows for more than one unit_id (the concatenated
    # tables/validation.csv), so each new check must be computed per unit_id.
    new_rows = []
    for unit_id in before["unit_id"].unique():
        unit_dir = region_dir(path, unit_id)
        tl_ok, convexity_ok = compute_checks(unit_dir)
        if tl_ok is None:
            declined.append(f"{unit_id}/tl_coverage_complete")
        else:
            new_rows.append(
                {"unit_id": unit_id, "check": "tl_coverage_complete", "value": tl_ok, "unit": "boolean"}
            )
        if convexity_ok is None:
            declined.append(f"{unit_id}/group_ppr_within_convexity_bound")
        else:
            new_rows.append(
                {
                    "unit_id": unit_id,
                    "check": "group_ppr_within_convexity_bound",
                    "value": convexity_ok,
                    "unit": "boolean",
                }
            )

    after = pd.concat([kept, pd.DataFrame(new_rows)], ignore_index=True) if new_rows else kept
    removed_present = [c for c in REMOVE_CHECKS if c in set(before["check"])]
    added = len(new_rows)
    if removed_present or added:
        after.to_csv(path, index=False, encoding="utf-8-sig")
        summary = f"-{len(before) - len(kept)} rows, +{added} rows across {before['unit_id'].nunique()} unit(s)"
    else:
        summary = "unchanged"
    return summary, declined


def main() -> int:
    touched = 0
    all_declined: dict[str, list[str]] = {}
    for root in (Path("SeaAroundUsExtraction/global_output"), Path("SeaAroundUsExtraction/eez_output")):
        if not root.exists():
            continue
        for f in sorted(root.rglob("validation.csv")):
            summary, declined = migrate(f)
            print(f"  {f}: {summary}")
            touched += 1
            if declined:
                all_declined[str(f)] = declined
    print(f"\nmigrated {touched} validation.csv files")
    if all_declined:
        print(f"declined (left absent, not invented) in {len(all_declined)} files:")
        for f, checks in all_declined.items():
            print(f"  {f}: {checks}")
    else:
        print("no checks declined - all files got both new checks")
    return 0


if __name__ == "__main__":
    sys.exit(main())
