"""Assemble the Excel deliverable from the CSVs the pipeline has already written.

Derived cells (medians, ranges, spreads, system totals) are written as **formulas** rather
than as Python-computed literals, so the workbook recalculates if anyone edits an input
and a reader can see exactly how each figure was produced.

The benthic sheet is included only when ``benthic.enabled`` and the CSV exists, and it
carries its own provenance block. Nothing on the main sheets depends on it.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from .config import MODEL_LABELS, Config
from .fill import CATEGORIES
from .log import log

BODY = Font(name="Arial", size=10)
HEAD = Font(name="Arial", size=9, bold=True, color="FFFFFF")
BOLD = Font(name="Arial", size=10, bold=True)
TITLE = Font(name="Arial", size=13, bold=True)
SUBTLE = Font(name="Arial", size=10, italic=True, color="555555")
NOTE = Font(name="Arial", size=9, color="666666")
HFILL = PatternFill("solid", fgColor="0B6F63")
BAND = PatternFill("solid", fgColor="EEF4F3")
EDGE = Border(bottom=Side(style="thin", color="D0DAD9"))
INT, ONE, TWO, PCT = "#,##0", "#,##0.0", "0.00", "0.0"


def _clean(v):
    """NaN must become an empty cell: openpyxl writes float('nan') as a literal that
    LibreOffice and Excel then read as #VALUE!."""
    if v is None:
        return None
    if isinstance(v, str):
        return v
    try:
        f = float(v)
    except (TypeError, ValueError):
        return v
    return None if not np.isfinite(f) else f


def _sheet(wb, name, headers, rows, widths=None, fmts=None, notes=()):
    ws = wb.create_sheet(name)
    for j, h in enumerate(headers, 1):
        c = ws.cell(1, j, h)
        c.font, c.fill = HEAD, HFILL
        c.alignment = Alignment(wrap_text=True, vertical="bottom",
                                horizontal="left" if j <= 4 else "right")
    for i, row in enumerate(rows, 2):
        for j, v in enumerate(row, 1):
            c = ws.cell(i, j, _clean(v))
            c.font, c.border = BODY, EDGE
            if fmts and fmts.get(j):
                c.number_format = fmts[j]
            if i % 2 == 0:
                c.fill = BAND
    ws.freeze_panes = "A2"
    if rows:
        ws.auto_filter.ref = f"A1:{get_column_letter(len(headers))}{len(rows)+1}"
    for j, w in enumerate(widths or [], 1):
        ws.column_dimensions[get_column_letter(j)].width = w
    ws.row_dimensions[1].height = 44
    for k, t in enumerate(notes):
        ws.cell(len(rows) + 3 + k, 1, t).font = NOTE
    return ws


def _readme(wb, cfg: Config, base: pd.DataFrame, ens: pd.DataFrame) -> None:
    ws = wb.create_sheet("README")
    central = ", ".join(cfg.fill.central_categories())
    donors = ", ".join(str(y) for y in cfg.donor_years()) or "none"
    models = ", ".join(MODEL_LABELS[m] for m in cfg.ensemble.models)
    lines: list[tuple[str, Font]] = [
        (f"Net primary production for the Sea Around Us region systems, {cfg.year}", TITLE),
        (f"{models} -- generated by the ppr-npp pipeline; see METHODS.md in the repository", SUBTLE),
        ("", BODY),
        ("!! THE THREE REGION SYSTEMS OVERLAP. DO NOT ADD THEM TOGETHER.",
         Font(name="Arial", size=11, bold=True, color="A3402C")),
        ("   About half of all EEZ area lies inside an LME, and the Arctic Sea high-seas area is almost entirely", BODY),
        ("   inside the Central Arctic Ocean LME. The Overlap sheet gives the share per region. The disjoint", BODY),
        ("   alternative is EEZ + high seas, which is how SAU defines the high seas and which closes to the global total.", BODY),
        ("", BODY),
        ("RUN CONFIGURATION", Font(name="Arial", size=11, bold=True)),
        (f"   target year           {cfg.year}", BODY),
        (f"   window years          {cfg.window_years}   (water mask and fill climatology)", BODY),
        (f"   climatology donors    {donors}", BODY),
        (f"   baseline grid         {cfg.baseline_grid}      ensemble grid  {cfg.ensemble.grid}", BODY),
        (f"   reference model       {MODEL_LABELS[cfg.ensemble.reference_model]}", BODY),
        (f"   fill stages central   {central}", BODY),
        (f"   nearest-neighbour     {'on' if cfg.fill.use_nearest_neighbour else 'off'}, "
         f"near/far split {cfg.fill.nn_split_km:.0f} km, far in central: {cfg.fill.nn_far_in_central}", BODY),
        (f"   anomaly rescale       {'on' if cfg.fill.anomaly_rescale else 'off'}, clip {cfg.fill.anomaly_clip}", BODY),
        (f"   benthic module        {'ENABLED' if cfg.benthic.enabled else 'disabled (main results exclude it)'}", BODY),
        ("", BODY),
        ("WHAT EACH NPP COLUMN MEANS", Font(name="Arial", size=11, bold=True)),
        ("   npp_central_tC_yr     the headline number: the fill stages listed above", BODY),
        ("   npp_observed_tC_yr    retrievals only -- what a naive sum over observed months gives", BODY),
        ("   npp_no_nn_tC_yr       observed + polar-night zeros + pixel climatology, no spatial fill", BODY),
        ("   npp_all_fills_tC_yr   every stage, including the pack-ice nearest-neighbour fill (an upper bound)", BODY),
        ("   npp_mean_year_tC_yr   the same integration on the multi-year mean field, as an independent check", BODY),
        ("   area_<stage>_pct      share of the region's water area supplied by each fill stage", BODY),
        ("   npp_<stage>_pct       share of its annual carbon supplied by each fill stage", BODY),
        ("", BODY),
        ("THE FIVE ALGORITHMS", Font(name="Arial", size=11, bold=True)),
        ("   All five are integrated over the same pixels of the same grid -- those where every model has a", BODY),
        ("   retrieval that month. Each model's ratio to the reference on that common mask is then applied to the", BODY),
        ("   reference model's gap-filled total, so the five columns are absolute and complete rather than", BODY),
        ("   restricted to the common mask. Blank model cells mean that algorithm has no data for that region;", BODY),
        ("   'Models used' and 'Ensemble basis' record it. Some OSU products do not cover certain semi-enclosed", BODY),
        ("   seas at all (no VGPM or Eppley-VGPM in the Black Sea, no CbPM2 in the Persian Gulf).", BODY),
        ("", BODY),
        ("HOW TO USE IT", Font(name="Arial", size=11, bold=True)),
        ("   Take the reference model as the central value and the ensemble min-max as the uncertainty band.", BODY),
        ("   Algorithm choice dominates every other uncertainty here by an order of magnitude, and the", BODY),
        ("   disagreement is structural rather than random: the models distribute production differently between", BODY),
        ("   coast and open ocean, which is exactly the axis a fisheries denominator depends on. Report a range.", BODY),
        ("   Four of the five share one MODIS input chain, so sensor and atmospheric-correction error is largely", BODY),
        ("   common to them and this band is a LOWER BOUND on total uncertainty.", BODY),
        ("", BODY),
        ("SOURCES", Font(name="Arial", size=11, bold=True)),
        ("   Copernicus Marine Service, OCEANCOLOUR_GLO_BGC_L4_MY_009_104, dataset", BODY),
        ("   cmems_obs-oc_glo_bgc-pp_my_l4-multi-4km_P1M (Antoine-Morel, 4 km, monthly).", BODY),
        ("   Ocean Productivity, Oregon State University: VGPM, Eppley-VGPM, CbPM2, CAFE, MODIS R2022, 1/12 deg,", BODY),
        ("   monthly. Region geometries and published primary-production values: Sea Around Us, UBC.", BODY),
        ("   Units: tC/yr = tonnes carbon per year (1e9 tC = 1 Pg C); rates in mgC m-2 d-1.", NOTE),
    ]
    for i, (text, font) in enumerate(lines, 1):
        ws.cell(i, 1, text).font = font
    ws.column_dimensions["A"].width = 128
    ws.sheet_view.showGridLines = False


def _summary(wb, cfg: Config, ens: pd.DataFrame, n_rows: int) -> None:
    models = list(cfg.ensemble.models)
    ws = wb.create_sheet("Summary")
    ws["A1"] = f"System totals, {cfg.year}"
    ws["A1"].font = TITLE
    ws["A2"] = "Pg C per year. Every value is a formula over the Ensemble sheet."
    ws["A2"].font = SUBTLE
    cols = ["System", "Regions", "Water area (M km2)"] + [MODEL_LABELS[m] for m in models] + \
           ["Ensemble median", "Ensemble min", "Ensemble max", "Spread (% of median)"]
    r0 = 4
    for j, h in enumerate(cols, 1):
        c = ws.cell(r0, j, h)
        c.font, c.fill = HEAD, HFILL
        c.alignment = Alignment(wrap_text=True, horizontal="left" if j == 1 else "right")
    last = n_rows + 1
    first_model_col = 4
    nm = len(models)
    med_col = get_column_letter(first_model_col + nm)
    systems = [(lay, lab) for lay, lab in
               (("lme", "LME"), ("highseas", "HighSeas"), ("eez", "EEZ")) if lay in cfg.layers]
    for k, (lay, tag) in enumerate(systems):
        i = r0 + 1 + k
        ws.cell(i, 1, f"{tag}")
        ws.cell(i, 2, f'=COUNTIF(Ensemble!$A$2:$A${last},"{tag}")')
        ws.cell(i, 3, f'=SUMIF(Ensemble!$A$2:$A${last},"{tag}",Ensemble!$D$2:$D${last})/1000')
        for j, m in enumerate(models):
            cl = get_column_letter(5 + j)          # model columns start at E on Ensemble
            ws.cell(i, first_model_col + j,
                    f'=SUMIF(Ensemble!$A$2:$A${last},"{tag}",Ensemble!${cl}$2:${cl}${last})/1000000000')
        a = get_column_letter(first_model_col)
        b = get_column_letter(first_model_col + nm - 1)
        ws.cell(i, first_model_col + nm, f"=MEDIAN({a}{i}:{b}{i})")
        ws.cell(i, first_model_col + nm + 1, f"=MIN({a}{i}:{b}{i})")
        ws.cell(i, first_model_col + nm + 2, f"=MAX({a}{i}:{b}{i})")
        ws.cell(i, first_model_col + nm + 3,
                f'=IFERROR(({get_column_letter(first_model_col+nm+2)}{i}'
                f'-{get_column_letter(first_model_col+nm+1)}{i})/{med_col}{i}*100,"")')
        for j in range(1, len(cols) + 1):
            c = ws.cell(i, j)
            c.font, c.border = BODY, EDGE
            c.number_format = INT if j == 2 else (ONE if j in (3, len(cols)) else TWO)
    i = r0 + 1 + len(systems) + 1
    ws.cell(i, 1, "Median per-region spread (%)").font = SUBTLE
    for k, (lay, _tag) in enumerate(systems):
        v = float(ens[ens.layer == lay].spread_pct.median())
        c = ws.cell(i, first_model_col + k, v)
        c.font, c.number_format = SUBTLE, ONE
    notes = [
        "",
        'The "Spread" column on the system rows is the spread of the five SYSTEM TOTALS. The spread that applies',
        "to a single region is much larger - see the row of medians above and the per-region column on Ensemble.",
        "The median per-region spread is computed by the build script, not by a cell formula (Excel cannot take a",
        "conditional median without an array formula, which openpyxl cannot mark as one).",
        "",
        "The system rows must NOT be added together: the region systems overlap. See the Overlap sheet.",
    ]
    for k, t in enumerate(notes):
        ws.cell(i + 2 + k, 1, t).font = NOTE
    ws.column_dimensions["A"].width = 34
    for j in range(2, len(cols) + 1):
        ws.column_dimensions[get_column_letter(j)].width = 15
    ws.sheet_view.showGridLines = False


def build_workbook(cfg: Config) -> Path:
    models = list(cfg.ensemble.models)
    out_dir = Path(cfg.out_dir)
    base = pd.read_csv(out_dir / f"npp_{cfg.year}_baseline_by_region.csv")
    ens = pd.read_csv(out_dir / f"npp_{cfg.year}_ensemble_by_region.csv")
    monthly = pd.read_csv(out_dir / f"npp_{cfg.year}_baseline_monthly.csv")
    ov_path = out_dir / "region_system_overlap.csv"
    ov = pd.read_csv(ov_path) if ov_path.exists() else None
    ben_path = out_dir / f"benthic_{cfg.year}_by_LME_firstorder.csv"
    ben = pd.read_csv(ben_path) if (cfg.benthic.enabled and ben_path.exists()) else None

    wb = Workbook()
    wb.remove(wb.active)
    _readme(wb, cfg, base, ens)

    # ---------------------------------------------------------------- Ensemble
    labels = [MODEL_LABELS[m] for m in models]
    hdr = (["System", "Region ID", "Region", "Water area (1000 km2)"]
           + [f"{l} (tC/yr)" for l in labels]
           + ["Ensemble median (tC/yr)", "Ensemble min (tC/yr)", "Ensemble max (tC/yr)",
              "Spread (% of median)", "CV (%)", "Median rate (mgC/m2/d)",
              "Models used", "Ensemble basis", "Common mask (% of water)",
              "SAU published PP (mgC/m2/d)", "Ours / SAU"])
    sau = dict(zip(zip(base.layer, base.region_id), base.get("sau_pp_mgC_m2_d", pd.Series(dtype=float))))
    rows = []
    for _, x in ens.iterrows():
        rows.append([x.system, int(x.region_id), x.title, x.water_area_km2 / 1e3]
                    + [x[f"scaled_{m}_tC_yr"] for m in models]
                    + [None] * 6
                    + [int(x.n_models), x.ensemble_basis, x.common_area_pct_of_water,
                       sau.get((x.layer, int(x.region_id))), None])
    nm = len(models)
    first, last_model = 5, 4 + nm
    fmts = {4: ONE, **{k: INT for k in range(first, last_model + 4)},
            last_model + 4: PCT, last_model + 5: PCT, last_model + 6: ONE,
            last_model + 7: INT, last_model + 10: PCT, last_model + 11: ONE, last_model + 12: TWO}
    widths = [11, 10, 34, 14] + [15] * nm + [16, 15, 15, 12, 9, 14, 9, 15, 15, 15, 10]
    ws = _sheet(wb, "Ensemble", hdr, rows, widths=widths, fmts=fmts, notes=[
        "Median / min / max / spread / CV / rate / ratio are formulas over the model columns of each row.",
        "Model columns are the ensemble carried onto the gap-filled baseline, so they are absolute and complete.",
        "A blank model cell means that algorithm has no data for that region - check 'Models used'.",
    ])
    A, B = get_column_letter(first), get_column_letter(last_model)
    for i in range(2, len(rows) + 2):
        med = get_column_letter(last_model + 1)
        mn = get_column_letter(last_model + 2)
        mx = get_column_letter(last_model + 3)
        ws.cell(i, last_model + 1, f"=MEDIAN({A}{i}:{B}{i})")
        ws.cell(i, last_model + 2, f"=MIN({A}{i}:{B}{i})")
        ws.cell(i, last_model + 3, f"=MAX({A}{i}:{B}{i})")
        ws.cell(i, last_model + 4, f'=IFERROR(({mx}{i}-{mn}{i})/{med}{i}*100,"")')
        ws.cell(i, last_model + 5, f'=IFERROR(STDEV({A}{i}:{B}{i})/AVERAGE({A}{i}:{B}{i})*100,"")')
        ws.cell(i, last_model + 6, f'=IFERROR({med}{i}/(D{i}*1000)/365*1000,"")')
        ws.cell(i, last_model + 12,
                f'=IFERROR({get_column_letter(last_model+6)}{i}/{get_column_letter(last_model+11)}{i},"")')
        for j in range(last_model + 1, last_model + 7):
            ws.cell(i, j).font = BODY
        ws.cell(i, last_model + 12).font = BODY
    _summary(wb, cfg, ens, len(rows))

    # ---------------------------------------------------------------- Baseline
    bh = (["System", "Region ID", "Region", "Polygon area (1000 km2)", "Water area (1000 km2)",
           "NPP central (tC/yr)", "NPP observed only (tC/yr)", "NPP no spatial fill (tC/yr)",
           "NPP all fills (tC/yr)", "NPP multi-year mean (tC/yr)", "Fill uplift (%)",
           "Mean rate (mgC/m2/d)"]
          + [f"Area {c} (%)" for c in CATEGORIES] + [f"NPP {c} (%)" for c in CATEGORIES]
          + ["Anomaly factor min", "Anomaly factor max",
             "SAU published PP (mgC/m2/d)", "Ours / SAU"])
    brows = []
    for _, x in base.iterrows():
        brows.append([x.system, int(x.region_id), x.title, x.polygon_area_km2 / 1e3,
                      x.water_area_km2 / 1e3, x.npp_central_tC_yr, x.npp_observed_tC_yr,
                      x.npp_no_nn_tC_yr, x.npp_all_fills_tC_yr, x.npp_mean_year_tC_yr,
                      x.fill_uplift_pct, x.mean_rate_mgC_m2_d]
                     + [x[f"area_{c}_pct"] for c in CATEGORIES]
                     + [x[f"npp_{c}_pct"] for c in CATEGORIES]
                     + [x.anomaly_factor_min, x.anomaly_factor_max,
                        x.get("sau_pp_mgC_m2_d"), x.get("ratio_vs_sau")])
    nc = len(CATEGORIES)
    bf = {4: ONE, 5: ONE, **{k: INT for k in range(6, 11)}, 11: PCT, 12: ONE,
          **{k: PCT for k in range(13, 13 + 2 * nc)},
          13 + 2 * nc: TWO, 14 + 2 * nc: TWO, 15 + 2 * nc: ONE, 16 + 2 * nc: TWO}
    _sheet(wb, "Baseline", bh, brows,
           widths=[11, 10, 34, 14, 14, 15, 16, 16, 15, 16, 10, 13] + [9] * (2 * nc) + [11, 11, 15, 10],
           fmts=bf, notes=[
               "One row per region. 'central' uses the fill stages listed on the README sheet.",
               "'Fill uplift' is central / observed-only - 1: how much the year's gaps were worth.",
               "SAU's published value is a 1998-2007 SeaWiFS climatology at 9 km, so it is a sanity check, not truth.",
           ])

    # ---------------------------------------------------------------- Overlap
    if ov is not None:
        cols = [c for c in ov.columns if c.startswith("pct_also_in_") or c.startswith("km2_also_in_")]
        oh = ["System", "Region ID", "Region", "Area (1000 km2)"] + [
            c.replace("pct_also_in_", "Share also in ").replace("km2_also_in_", "Area also in ")
            .replace("lme", "LME (%)" if c.startswith("pct") else "LME (1000 km2)")
            .replace("highseas", "high seas (%)" if c.startswith("pct") else "high seas (1000 km2)")
            .replace("eez", "an EEZ (%)" if c.startswith("pct") else "an EEZ (1000 km2)")
            for c in cols]
        orows = [[x.system, int(x.region_id), x.title, x.area_km2 / 1e3]
                 + [(x[c] / 1e3 if c.startswith("km2_") else x[c]) for c in cols]
                 for _, x in ov.iterrows()]
        _sheet(wb, "Overlap", oh, orows,
               widths=[11, 10, 34, 14] + [16] * len(cols),
               fmts={4: ONE, **{5 + k: (PCT if c.startswith("pct") else ONE) for k, c in enumerate(cols)}},
               notes=[
                   "Overlap per cell is min(coverage_a, coverage_b) x cell area - exact where one region nests",
                   "inside the other within a cell, which is the normal case for regions this large.",
                   "About half of all EEZ area sits inside an LME; the Arctic Sea high-seas area is ~100% inside",
                   "the Central Arctic Ocean LME. Use EEZ + high seas if you need a disjoint partition.",
               ])

    # ---------------------------------------------------------------- Monthly
    mh = ["System", "Region ID", "Region", "Month", "Days", "NPP central (tC)",
          "NPP observed (tC)", "Rate central (gC/m2/d)"] + [f"Area {c} (%)" for c in CATEGORIES] + \
         ["Anomaly factor"]
    mrows = [[x.system, int(x.region_id), x.title, int(x.month), int(x.days),
              x.npp_central_tC, x.npp_observed_tC, x.rate_central_gC_m2_d]
             + [x[f"area_{c}_pct"] for c in CATEGORIES] + [x.anomaly_factor]
             for _, x in monthly.iterrows()]
    _sheet(wb, "Monthly", mh, mrows,
           widths=[11, 10, 34, 7, 7, 14, 14, 13] + [9] * nc + [11],
           fmts={4: INT, 5: INT, 6: INT, 7: INT, 8: "0.000",
                 **{9 + k: PCT for k in range(nc)}, 9 + nc: TWO})

    # ---------------------------------------------------------------- Benthic (optional)
    if ben is not None:
        habitats = [c[:-3] for c in ben.columns if c.endswith("_tC")
                    and not c.startswith(("benthic", "coral"))
                    and not c.endswith(("_low_tC", "_high_tC", "_available_tC"))]
        bh2 = (["Region ID", "LME", "Mean |lat| (deg)", "Shelf area (1000 km2)", "Light index",
                "Pelagic NPP central (tC/yr)", "Benthic NPP (tC/yr)", "Benthic low (tC/yr)",
                "Benthic high (tC/yr)", "Benthic availability-weighted (tC/yr)",
                "Benthic as % of pelagic", "Availability-weighted (%)"]
               + [f"{h} (tC/yr)" for h in habitats]
               + ["Coral reef GROSS PP (tC/yr) - NOT additive", "Dominant habitat"])
        brows2 = [[int(x.region_id), x.title, x.abs_lat, (x.sau_shelf_km2 or 0) / 1e3, x.light_index,
                   x.npp_central_tC_yr, x.benthic_tC, x.benthic_low_tC, x.benthic_high_tC,
                   x.benthic_available_tC, x.pct_of_pelagic, x.pct_available_of_pelagic]
                  + [x[f"{h}_tC"] for h in habitats]
                  + [x.coral_reef_gross_tC, x.dominant_habitat]
                  for _, x in ben.iterrows()]
        _sheet(wb, "Benthic_LME", bh2, brows2,
               widths=[10, 32, 12, 14, 10, 16, 14, 14, 14, 17, 13, 13] + [15] * len(habitats) + [20, 18],
               fmts={3: ONE, 4: ONE, 5: TWO, **{k: INT for k in range(6, 11)}, 11: PCT, 12: PCT,
                     **{13 + k: INT for k in range(len(habitats))}, 13 + len(habitats): INT},
               notes=[
                   "FIRST-ORDER ESTIMATE, not a measurement. Per-region values are within about a factor of two;",
                   "the global habitat totals are far better constrained than their distribution across regions.",
                   "NONE OF THE MAIN SHEETS INCLUDE THIS. It is an optional add-on, off by default.",
                   "Global totals from the literature, distributed by shelf area / inshore fishing area / SAU coral",
                   "share, each scaled by a light index (insolation at that latitude x the ice-free lit fraction of",
                   "the year). Macroalgae 1.32 Pg C/yr (Duarte et al. 2022, doi 10.1111/geb.13515) is a NICHE MODEL",
                   "and is three quarters of the total. Microphytobenthos ~0.42 Pg C/yr (Cahoon 1999) has no global",
                   "map at all. Mangrove 218+/-72 Tg C/yr (Bouillon et al. 2008). Seagrass ~0.064 Pg C/yr (McKenzie",
                   "et al. 2020). Salt marsh ~0.066 Pg C/yr (Mcowen et al. 2017, 43 countries only).",
                   "Coral reef NET community production is near zero (Gattuso et al. 1998) - the gross column is",
                   "context only and MUST NOT be added to a denominator.",
                   "Availability weighting is the fraction grazed or exported as consumable detritus rather than",
                   "buried or respired in place (Duarte & Cebrian 1996). Classical PPR uses UNWEIGHTED NPP, so do",
                   "not mix conventions: either add raw to raw, or weight both sides.",
                   "See npp/benthic.py for every parameter and citation, and METHODS.md for the fuller discussion.",
               ])

    order = [n for n in ["README", "Summary", "Ensemble", "Baseline", "Overlap", "Monthly", "Benthic_LME"]
             if n in wb.sheetnames]
    wb._sheets = [wb[n] for n in order]
    out = out_dir / f"NPP_{cfg.year}_SAU_regions.xlsx"
    wb.save(out)
    log(f"workbook: -> {out} ({len(order)} sheets)")
    return out
